// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package visitordb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddAllowedDeviceType(ctx context.Context, deviceTypeID uuid.UUID) error
	AssignVisitorRole(ctx context.Context, arg AssignVisitorRoleParams) error
	ClearAllowedDeviceTypes(ctx context.Context) error
	ConsumeEnrollmentContext(ctx context.Context, id uuid.UUID) (int64, error)
	CreateEnrollmentContext(ctx context.Context, arg CreateEnrollmentContextParams) (VisitorEnrollmentContext, error)
	CreateLabRulesRequest(ctx context.Context, arg CreateLabRulesRequestParams) (LaborordnungRequest, error)
	CreateVisitorAccount(ctx context.Context, arg CreateVisitorAccountParams) (Account, error)
	CreateVisitorInvitation(ctx context.Context, arg CreateVisitorInvitationParams) (AuthChallenge, error)
	CreateVisitorPINCredential(ctx context.Context, arg CreateVisitorPINCredentialParams) error
	CreateVisitorPINIdentity(ctx context.Context, arg CreateVisitorPINIdentityParams) (AuthIdentity, error)
	CreateVisitorPasswordIdentity(ctx context.Context, arg CreateVisitorPasswordIdentityParams) (AuthIdentity, error)
	CreateVisitorPerson(ctx context.Context, arg CreateVisitorPersonParams) (Person, error)
	DeviceTypeExists(ctx context.Context, id uuid.UUID) (bool, error)
	GetAssignableRole(ctx context.Context, id uuid.UUID) (Role, error)
	GetConfiguration(ctx context.Context) (VisitorEnrollmentConfiguration, error)
	GetConfigurationForUpdate(ctx context.Context) (VisitorEnrollmentConfiguration, error)
	GetCurrentLabRulesVersion(ctx context.Context) (LaborordnungVersion, error)
	GetEnrollmentContext(ctx context.Context, tokenDigest []byte) (VisitorEnrollmentContext, error)
	GetEnrollmentContextForUpdate(ctx context.Context, id uuid.UUID) (VisitorEnrollmentContext, error)
	GetRolePermissionGrants(ctx context.Context, roleID uuid.UUID) ([]GetRolePermissionGrantsRow, error)
	IsDeviceTypeAllowed(ctx context.Context, managedDeviceID uuid.UUID) (*bool, error)
	ListAllowedDeviceTypes(ctx context.Context) ([]uuid.UUID, error)
	SetChallengeDelivery(ctx context.Context, arg SetChallengeDeliveryParams) error
	UpdateConfiguration(ctx context.Context, arg UpdateConfigurationParams) (VisitorEnrollmentConfiguration, error)
}

var _ Querier = (*Queries)(nil)
