// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package brandingdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const bumpConfigurationVersion = `-- name: BumpConfigurationVersion :one
UPDATE branding_configuration SET
    version = version + 1,
    updated_by_account_id = $1,
    updated_at = now()
WHERE singleton = true AND version = $2
RETURNING singleton, legal_organization_name, display_name, application_name, tagline, primary_color, secondary_color, accent_color, background_color, imprint_mode, imprint_markdown, imprint_external_url, privacy_mode, privacy_markdown, privacy_external_url, version, updated_by_account_id, updated_at
`

type BumpConfigurationVersionParams struct {
	UpdatedByAccountID *uuid.UUID
	ExpectedVersion    int64
}

func (q *Queries) BumpConfigurationVersion(ctx context.Context, arg BumpConfigurationVersionParams) (BrandingConfiguration, error) {
	row := q.db.QueryRow(ctx, bumpConfigurationVersion, arg.UpdatedByAccountID, arg.ExpectedVersion)
	var i BrandingConfiguration
	err := row.Scan(
		&i.Singleton,
		&i.LegalOrganizationName,
		&i.DisplayName,
		&i.ApplicationName,
		&i.Tagline,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.AccentColor,
		&i.BackgroundColor,
		&i.ImprintMode,
		&i.ImprintMarkdown,
		&i.ImprintExternalUrl,
		&i.PrivacyMode,
		&i.PrivacyMarkdown,
		&i.PrivacyExternalUrl,
		&i.Version,
		&i.UpdatedByAccountID,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAssetOverride = `-- name: DeleteAssetOverride :exec
DELETE FROM branding_asset_overrides WHERE slot = $1
`

func (q *Queries) DeleteAssetOverride(ctx context.Context, slot string) error {
	_, err := q.db.Exec(ctx, deleteAssetOverride, slot)
	return err
}

const getAssetOverride = `-- name: GetAssetOverride :one
SELECT bao.slot, bao.mode, bao.file_id, bao.updated_at,
       f.original_filename, f.content_type, f.size_bytes, f.sha256
FROM branding_asset_overrides bao
LEFT JOIN files f ON f.id = bao.file_id
WHERE bao.slot = $1
`

type GetAssetOverrideRow struct {
	Slot             string
	Mode             string
	FileID           *uuid.UUID
	UpdatedAt        time.Time
	OriginalFilename *string
	ContentType      *string
	SizeBytes        *int64
	Sha256           []byte
}

func (q *Queries) GetAssetOverride(ctx context.Context, slot string) (GetAssetOverrideRow, error) {
	row := q.db.QueryRow(ctx, getAssetOverride, slot)
	var i GetAssetOverrideRow
	err := row.Scan(
		&i.Slot,
		&i.Mode,
		&i.FileID,
		&i.UpdatedAt,
		&i.OriginalFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
	)
	return i, err
}

const getConfiguration = `-- name: GetConfiguration :one
SELECT singleton, legal_organization_name, display_name, application_name, tagline, primary_color, secondary_color, accent_color, background_color, imprint_mode, imprint_markdown, imprint_external_url, privacy_mode, privacy_markdown, privacy_external_url, version, updated_by_account_id, updated_at FROM branding_configuration WHERE singleton = true
`

func (q *Queries) GetConfiguration(ctx context.Context) (BrandingConfiguration, error) {
	row := q.db.QueryRow(ctx, getConfiguration)
	var i BrandingConfiguration
	err := row.Scan(
		&i.Singleton,
		&i.LegalOrganizationName,
		&i.DisplayName,
		&i.ApplicationName,
		&i.Tagline,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.AccentColor,
		&i.BackgroundColor,
		&i.ImprintMode,
		&i.ImprintMarkdown,
		&i.ImprintExternalUrl,
		&i.PrivacyMode,
		&i.PrivacyMarkdown,
		&i.PrivacyExternalUrl,
		&i.Version,
		&i.UpdatedByAccountID,
		&i.UpdatedAt,
	)
	return i, err
}

const getConfigurationForUpdate = `-- name: GetConfigurationForUpdate :one
SELECT singleton, legal_organization_name, display_name, application_name, tagline, primary_color, secondary_color, accent_color, background_color, imprint_mode, imprint_markdown, imprint_external_url, privacy_mode, privacy_markdown, privacy_external_url, version, updated_by_account_id, updated_at FROM branding_configuration WHERE singleton = true FOR UPDATE
`

func (q *Queries) GetConfigurationForUpdate(ctx context.Context) (BrandingConfiguration, error) {
	row := q.db.QueryRow(ctx, getConfigurationForUpdate)
	var i BrandingConfiguration
	err := row.Scan(
		&i.Singleton,
		&i.LegalOrganizationName,
		&i.DisplayName,
		&i.ApplicationName,
		&i.Tagline,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.AccentColor,
		&i.BackgroundColor,
		&i.ImprintMode,
		&i.ImprintMarkdown,
		&i.ImprintExternalUrl,
		&i.PrivacyMode,
		&i.PrivacyMarkdown,
		&i.PrivacyExternalUrl,
		&i.Version,
		&i.UpdatedByAccountID,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublicAssetByDigest = `-- name: GetPublicAssetByDigest :one
SELECT bao.slot, f.id, f.storage_key, f.original_filename, f.content_type, f.size_bytes, f.sha256, f.created_by_account_id, f.created_at, f.updated_at
FROM branding_asset_overrides bao
JOIN files f ON f.id = bao.file_id
WHERE bao.slot = $1 AND bao.mode = 'custom' AND encode(f.sha256, 'hex') = $2::text
`

type GetPublicAssetByDigestParams struct {
	Slot   string
	Digest string
}

type GetPublicAssetByDigestRow struct {
	Slot               string
	ID                 uuid.UUID
	StorageKey         string
	OriginalFilename   string
	ContentType        string
	SizeBytes          int64
	Sha256             []byte
	CreatedByAccountID *uuid.UUID
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

func (q *Queries) GetPublicAssetByDigest(ctx context.Context, arg GetPublicAssetByDigestParams) (GetPublicAssetByDigestRow, error) {
	row := q.db.QueryRow(ctx, getPublicAssetByDigest, arg.Slot, arg.Digest)
	var i GetPublicAssetByDigestRow
	err := row.Scan(
		&i.Slot,
		&i.ID,
		&i.StorageKey,
		&i.OriginalFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.CreatedByAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssetOverrides = `-- name: ListAssetOverrides :many
SELECT bao.slot, bao.mode, bao.file_id, bao.updated_at,
       f.original_filename, f.content_type, f.size_bytes, f.sha256
FROM branding_asset_overrides bao
LEFT JOIN files f ON f.id = bao.file_id
ORDER BY bao.slot
`

type ListAssetOverridesRow struct {
	Slot             string
	Mode             string
	FileID           *uuid.UUID
	UpdatedAt        time.Time
	OriginalFilename *string
	ContentType      *string
	SizeBytes        *int64
	Sha256           []byte
}

func (q *Queries) ListAssetOverrides(ctx context.Context) ([]ListAssetOverridesRow, error) {
	rows, err := q.db.Query(ctx, listAssetOverrides)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssetOverridesRow{}
	for rows.Next() {
		var i ListAssetOverridesRow
		if err := rows.Scan(
			&i.Slot,
			&i.Mode,
			&i.FileID,
			&i.UpdatedAt,
			&i.OriginalFilename,
			&i.ContentType,
			&i.SizeBytes,
			&i.Sha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConfiguration = `-- name: UpdateConfiguration :one
UPDATE branding_configuration SET
    legal_organization_name = $1,
    display_name = $2,
    application_name = $3,
    tagline = $4,
    primary_color = $5,
    secondary_color = $6,
    accent_color = $7,
    background_color = $8,
    imprint_mode = $9,
    imprint_markdown = $10,
    imprint_external_url = $11,
    privacy_mode = $12,
    privacy_markdown = $13,
    privacy_external_url = $14,
    version = version + 1,
    updated_by_account_id = $15,
    updated_at = now()
WHERE singleton = true AND version = $16
RETURNING singleton, legal_organization_name, display_name, application_name, tagline, primary_color, secondary_color, accent_color, background_color, imprint_mode, imprint_markdown, imprint_external_url, privacy_mode, privacy_markdown, privacy_external_url, version, updated_by_account_id, updated_at
`

type UpdateConfigurationParams struct {
	LegalOrganizationName string
	DisplayName           string
	ApplicationName       string
	Tagline               *string
	PrimaryColor          string
	SecondaryColor        string
	AccentColor           string
	BackgroundColor       string
	ImprintMode           string
	ImprintMarkdown       string
	ImprintExternalUrl    string
	PrivacyMode           string
	PrivacyMarkdown       string
	PrivacyExternalUrl    string
	UpdatedByAccountID    *uuid.UUID
	ExpectedVersion       int64
}

func (q *Queries) UpdateConfiguration(ctx context.Context, arg UpdateConfigurationParams) (BrandingConfiguration, error) {
	row := q.db.QueryRow(ctx, updateConfiguration,
		arg.LegalOrganizationName,
		arg.DisplayName,
		arg.ApplicationName,
		arg.Tagline,
		arg.PrimaryColor,
		arg.SecondaryColor,
		arg.AccentColor,
		arg.BackgroundColor,
		arg.ImprintMode,
		arg.ImprintMarkdown,
		arg.ImprintExternalUrl,
		arg.PrivacyMode,
		arg.PrivacyMarkdown,
		arg.PrivacyExternalUrl,
		arg.UpdatedByAccountID,
		arg.ExpectedVersion,
	)
	var i BrandingConfiguration
	err := row.Scan(
		&i.Singleton,
		&i.LegalOrganizationName,
		&i.DisplayName,
		&i.ApplicationName,
		&i.Tagline,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.AccentColor,
		&i.BackgroundColor,
		&i.ImprintMode,
		&i.ImprintMarkdown,
		&i.ImprintExternalUrl,
		&i.PrivacyMode,
		&i.PrivacyMarkdown,
		&i.PrivacyExternalUrl,
		&i.Version,
		&i.UpdatedByAccountID,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCustomAsset = `-- name: UpsertCustomAsset :one
INSERT INTO branding_asset_overrides (slot, mode, file_id, updated_by_account_id)
VALUES ($1, 'custom', $2, $3)
ON CONFLICT (slot) DO UPDATE SET
    mode = 'custom', file_id = EXCLUDED.file_id,
    updated_by_account_id = EXCLUDED.updated_by_account_id, updated_at = now()
RETURNING slot, mode, file_id, updated_by_account_id, updated_at
`

type UpsertCustomAssetParams struct {
	Slot               string
	FileID             *uuid.UUID
	UpdatedByAccountID *uuid.UUID
}

func (q *Queries) UpsertCustomAsset(ctx context.Context, arg UpsertCustomAssetParams) (BrandingAssetOverride, error) {
	row := q.db.QueryRow(ctx, upsertCustomAsset, arg.Slot, arg.FileID, arg.UpdatedByAccountID)
	var i BrandingAssetOverride
	err := row.Scan(
		&i.Slot,
		&i.Mode,
		&i.FileID,
		&i.UpdatedByAccountID,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRemovedAsset = `-- name: UpsertRemovedAsset :one
INSERT INTO branding_asset_overrides (slot, mode, file_id, updated_by_account_id)
VALUES ($1, 'none', NULL, $2)
ON CONFLICT (slot) DO UPDATE SET
    mode = 'none', file_id = NULL,
    updated_by_account_id = EXCLUDED.updated_by_account_id, updated_at = now()
RETURNING slot, mode, file_id, updated_by_account_id, updated_at
`

type UpsertRemovedAssetParams struct {
	Slot               string
	UpdatedByAccountID *uuid.UUID
}

func (q *Queries) UpsertRemovedAsset(ctx context.Context, arg UpsertRemovedAssetParams) (BrandingAssetOverride, error) {
	row := q.db.QueryRow(ctx, upsertRemovedAsset, arg.Slot, arg.UpdatedByAccountID)
	var i BrandingAssetOverride
	err := row.Scan(
		&i.Slot,
		&i.Mode,
		&i.FileID,
		&i.UpdatedByAccountID,
		&i.UpdatedAt,
	)
	return i, err
}
