// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package maildb

import (
	"context"

	"github.com/google/uuid"
)

const getConfiguration = `-- name: GetConfiguration :one
SELECT singleton, enabled, provider, smtp_host, smtp_port, smtp_tls_mode, smtp_username, encrypted_smtp_password, from_address, from_name, base_url, version, updated_by_account_id, updated_at FROM mail_configuration WHERE singleton=true
`

func (q *Queries) GetConfiguration(ctx context.Context) (MailConfiguration, error) {
	row := q.db.QueryRow(ctx, getConfiguration)
	var i MailConfiguration
	err := row.Scan(
		&i.Singleton,
		&i.Enabled,
		&i.Provider,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpTlsMode,
		&i.SmtpUsername,
		&i.EncryptedSmtpPassword,
		&i.FromAddress,
		&i.FromName,
		&i.BaseUrl,
		&i.Version,
		&i.UpdatedByAccountID,
		&i.UpdatedAt,
	)
	return i, err
}

const getConfigurationForUpdate = `-- name: GetConfigurationForUpdate :one
SELECT singleton, enabled, provider, smtp_host, smtp_port, smtp_tls_mode, smtp_username, encrypted_smtp_password, from_address, from_name, base_url, version, updated_by_account_id, updated_at FROM mail_configuration WHERE singleton=true FOR UPDATE
`

func (q *Queries) GetConfigurationForUpdate(ctx context.Context) (MailConfiguration, error) {
	row := q.db.QueryRow(ctx, getConfigurationForUpdate)
	var i MailConfiguration
	err := row.Scan(
		&i.Singleton,
		&i.Enabled,
		&i.Provider,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpTlsMode,
		&i.SmtpUsername,
		&i.EncryptedSmtpPassword,
		&i.FromAddress,
		&i.FromName,
		&i.BaseUrl,
		&i.Version,
		&i.UpdatedByAccountID,
		&i.UpdatedAt,
	)
	return i, err
}

const updateConfiguration = `-- name: UpdateConfiguration :one
UPDATE mail_configuration SET
  enabled=$1, provider='smtp', smtp_host=$2,
  smtp_port=$3, smtp_tls_mode=$4,
  smtp_username=$5, encrypted_smtp_password=$6,
  from_address=$7, from_name=$8, base_url=$9,
  version=version+1, updated_by_account_id=$10, updated_at=now()
WHERE singleton=true AND version=$11
RETURNING singleton, enabled, provider, smtp_host, smtp_port, smtp_tls_mode, smtp_username, encrypted_smtp_password, from_address, from_name, base_url, version, updated_by_account_id, updated_at
`

type UpdateConfigurationParams struct {
	Enabled               bool
	SmtpHost              string
	SmtpPort              int32
	SmtpTlsMode           string
	SmtpUsername          string
	EncryptedSmtpPassword []byte
	FromAddress           string
	FromName              string
	BaseUrl               string
	UpdatedByAccountID    *uuid.UUID
	ExpectedVersion       int64
}

func (q *Queries) UpdateConfiguration(ctx context.Context, arg UpdateConfigurationParams) (MailConfiguration, error) {
	row := q.db.QueryRow(ctx, updateConfiguration,
		arg.Enabled,
		arg.SmtpHost,
		arg.SmtpPort,
		arg.SmtpTlsMode,
		arg.SmtpUsername,
		arg.EncryptedSmtpPassword,
		arg.FromAddress,
		arg.FromName,
		arg.BaseUrl,
		arg.UpdatedByAccountID,
		arg.ExpectedVersion,
	)
	var i MailConfiguration
	err := row.Scan(
		&i.Singleton,
		&i.Enabled,
		&i.Provider,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpTlsMode,
		&i.SmtpUsername,
		&i.EncryptedSmtpPassword,
		&i.FromAddress,
		&i.FromName,
		&i.BaseUrl,
		&i.Version,
		&i.UpdatedByAccountID,
		&i.UpdatedAt,
	)
	return i, err
}
