// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package laborordnungdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmRequest = `-- name: ConfirmRequest :one
UPDATE laborordnung_requests
SET status = 'completed', completed_at = now(), confirmed_by_account_id = $1,
    physical_document_reference = $2, signed_date = $3,
    archive_note = $4, updated_at = now()
WHERE id = $5 AND status = 'pending'
RETURNING id, person_id, required_version_id, previous_version_id, status, requested_at, completed_at, superseded_at, confirmed_by_account_id, physical_document_reference, signed_date, archive_note, created_at, updated_at
`

type ConfirmRequestParams struct {
	ConfirmedByAccountID      *uuid.UUID
	PhysicalDocumentReference *string
	SignedDate                pgtype.Date
	ArchiveNote               *string
	ID                        uuid.UUID
}

func (q *Queries) ConfirmRequest(ctx context.Context, arg ConfirmRequestParams) (LaborordnungRequest, error) {
	row := q.db.QueryRow(ctx, confirmRequest,
		arg.ConfirmedByAccountID,
		arg.PhysicalDocumentReference,
		arg.SignedDate,
		arg.ArchiveNote,
		arg.ID,
	)
	var i LaborordnungRequest
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.RequiredVersionID,
		&i.PreviousVersionID,
		&i.Status,
		&i.RequestedAt,
		&i.CompletedAt,
		&i.SupersededAt,
		&i.ConfirmedByAccountID,
		&i.PhysicalDocumentReference,
		&i.SignedDate,
		&i.ArchiveNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRequest = `-- name: CreateRequest :one
INSERT INTO laborordnung_requests (id, person_id, required_version_id, previous_version_id)
VALUES ($1, $2, $3, $4)
RETURNING id, person_id, required_version_id, previous_version_id, status, requested_at, completed_at, superseded_at, confirmed_by_account_id, physical_document_reference, signed_date, archive_note, created_at, updated_at
`

type CreateRequestParams struct {
	ID                uuid.UUID
	PersonID          uuid.UUID
	RequiredVersionID uuid.UUID
	PreviousVersionID *uuid.UUID
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (LaborordnungRequest, error) {
	row := q.db.QueryRow(ctx, createRequest,
		arg.ID,
		arg.PersonID,
		arg.RequiredVersionID,
		arg.PreviousVersionID,
	)
	var i LaborordnungRequest
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.RequiredVersionID,
		&i.PreviousVersionID,
		&i.Status,
		&i.RequestedAt,
		&i.CompletedAt,
		&i.SupersededAt,
		&i.ConfirmedByAccountID,
		&i.PhysicalDocumentReference,
		&i.SignedDate,
		&i.ArchiveNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVersion = `-- name: CreateVersion :one
INSERT INTO laborordnung_versions (id, human_revision, pdf_file_id, pdf_sha256, created_by_account_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, status, human_revision, pdf_file_id, pdf_sha256, effective_at, published_at, created_by_account_id, created_at, updated_at
`

type CreateVersionParams struct {
	ID                 uuid.UUID
	HumanRevision      string
	PdfFileID          uuid.UUID
	PdfSha256          []byte
	CreatedByAccountID *uuid.UUID
}

func (q *Queries) CreateVersion(ctx context.Context, arg CreateVersionParams) (LaborordnungVersion, error) {
	row := q.db.QueryRow(ctx, createVersion,
		arg.ID,
		arg.HumanRevision,
		arg.PdfFileID,
		arg.PdfSha256,
		arg.CreatedByAccountID,
	)
	var i LaborordnungVersion
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.HumanRevision,
		&i.PdfFileID,
		&i.PdfSha256,
		&i.EffectiveAt,
		&i.PublishedAt,
		&i.CreatedByAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurrentVersion = `-- name: GetCurrentVersion :one
SELECT id, status, human_revision, pdf_file_id, pdf_sha256, effective_at, published_at, created_by_account_id, created_at, updated_at FROM laborordnung_versions
WHERE status = 'published' AND effective_at <= now()
ORDER BY effective_at DESC, id DESC LIMIT 1
`

func (q *Queries) GetCurrentVersion(ctx context.Context) (LaborordnungVersion, error) {
	row := q.db.QueryRow(ctx, getCurrentVersion)
	var i LaborordnungVersion
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.HumanRevision,
		&i.PdfFileID,
		&i.PdfSha256,
		&i.EffectiveAt,
		&i.PublishedAt,
		&i.CreatedByAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestCompletedRequest = `-- name: GetLatestCompletedRequest :one
SELECT id, person_id, required_version_id, previous_version_id, status, requested_at, completed_at, superseded_at, confirmed_by_account_id, physical_document_reference, signed_date, archive_note, created_at, updated_at FROM laborordnung_requests
WHERE person_id = $1 AND status = 'completed'
ORDER BY completed_at DESC, id DESC LIMIT 1
`

func (q *Queries) GetLatestCompletedRequest(ctx context.Context, personID uuid.UUID) (LaborordnungRequest, error) {
	row := q.db.QueryRow(ctx, getLatestCompletedRequest, personID)
	var i LaborordnungRequest
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.RequiredVersionID,
		&i.PreviousVersionID,
		&i.Status,
		&i.RequestedAt,
		&i.CompletedAt,
		&i.SupersededAt,
		&i.ConfirmedByAccountID,
		&i.PhysicalDocumentReference,
		&i.SignedDate,
		&i.ArchiveNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingRequest = `-- name: GetPendingRequest :one
SELECT id, person_id, required_version_id, previous_version_id, status, requested_at, completed_at, superseded_at, confirmed_by_account_id, physical_document_reference, signed_date, archive_note, created_at, updated_at FROM laborordnung_requests
WHERE person_id = $1 AND status = 'pending'
FOR UPDATE
`

func (q *Queries) GetPendingRequest(ctx context.Context, personID uuid.UUID) (LaborordnungRequest, error) {
	row := q.db.QueryRow(ctx, getPendingRequest, personID)
	var i LaborordnungRequest
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.RequiredVersionID,
		&i.PreviousVersionID,
		&i.Status,
		&i.RequestedAt,
		&i.CompletedAt,
		&i.SupersededAt,
		&i.ConfirmedByAccountID,
		&i.PhysicalDocumentReference,
		&i.SignedDate,
		&i.ArchiveNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingRequestForStatus = `-- name: GetPendingRequestForStatus :one
SELECT id, person_id, required_version_id, previous_version_id, status, requested_at, completed_at, superseded_at, confirmed_by_account_id, physical_document_reference, signed_date, archive_note, created_at, updated_at FROM laborordnung_requests
WHERE person_id = $1 AND status = 'pending'
`

func (q *Queries) GetPendingRequestForStatus(ctx context.Context, personID uuid.UUID) (LaborordnungRequest, error) {
	row := q.db.QueryRow(ctx, getPendingRequestForStatus, personID)
	var i LaborordnungRequest
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.RequiredVersionID,
		&i.PreviousVersionID,
		&i.Status,
		&i.RequestedAt,
		&i.CompletedAt,
		&i.SupersededAt,
		&i.ConfirmedByAccountID,
		&i.PhysicalDocumentReference,
		&i.SignedDate,
		&i.ArchiveNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPersonMode = `-- name: GetPersonMode :one
SELECT CASE COALESCE(max(CASE r.laborordnung_mode WHEN 'blocking' THEN 2 WHEN 'warning' THEN 1 ELSE 0 END), 0)
    WHEN 2 THEN 'blocking' WHEN 1 THEN 'warning' ELSE 'not_required' END::text AS mode
FROM accounts a
LEFT JOIN account_roles ar ON ar.account_id = a.id
LEFT JOIN roles r ON r.id = ar.role_id
WHERE a.person_id = $1
`

func (q *Queries) GetPersonMode(ctx context.Context, personID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getPersonMode, personID)
	var mode string
	err := row.Scan(&mode)
	return mode, err
}

const getPersonName = `-- name: GetPersonName :one
SELECT first_name, last_name FROM people WHERE id = $1
`

type GetPersonNameRow struct {
	FirstName string
	LastName  string
}

func (q *Queries) GetPersonName(ctx context.Context, id uuid.UUID) (GetPersonNameRow, error) {
	row := q.db.QueryRow(ctx, getPersonName, id)
	var i GetPersonNameRow
	err := row.Scan(&i.FirstName, &i.LastName)
	return i, err
}

const getRequestForUpdate = `-- name: GetRequestForUpdate :one
SELECT id, person_id, required_version_id, previous_version_id, status, requested_at, completed_at, superseded_at, confirmed_by_account_id, physical_document_reference, signed_date, archive_note, created_at, updated_at FROM laborordnung_requests WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetRequestForUpdate(ctx context.Context, id uuid.UUID) (LaborordnungRequest, error) {
	row := q.db.QueryRow(ctx, getRequestForUpdate, id)
	var i LaborordnungRequest
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.RequiredVersionID,
		&i.PreviousVersionID,
		&i.Status,
		&i.RequestedAt,
		&i.CompletedAt,
		&i.SupersededAt,
		&i.ConfirmedByAccountID,
		&i.PhysicalDocumentReference,
		&i.SignedDate,
		&i.ArchiveNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVersion = `-- name: GetVersion :one
SELECT id, status, human_revision, pdf_file_id, pdf_sha256, effective_at, published_at, created_by_account_id, created_at, updated_at FROM laborordnung_versions WHERE id = $1
`

func (q *Queries) GetVersion(ctx context.Context, id uuid.UUID) (LaborordnungVersion, error) {
	row := q.db.QueryRow(ctx, getVersion, id)
	var i LaborordnungVersion
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.HumanRevision,
		&i.PdfFileID,
		&i.PdfSha256,
		&i.EffectiveAt,
		&i.PublishedAt,
		&i.CreatedByAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRequests = `-- name: ListRequests :many
SELECT id, person_id, required_version_id, previous_version_id, status, requested_at, completed_at, superseded_at, confirmed_by_account_id, physical_document_reference, signed_date, archive_note, created_at, updated_at FROM laborordnung_requests ORDER BY CASE status WHEN 'pending' THEN 0 WHEN 'completed' THEN 1 ELSE 2 END, requested_at, id
`

func (q *Queries) ListRequests(ctx context.Context) ([]LaborordnungRequest, error) {
	rows, err := q.db.Query(ctx, listRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LaborordnungRequest{}
	for rows.Next() {
		var i LaborordnungRequest
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.RequiredVersionID,
			&i.PreviousVersionID,
			&i.Status,
			&i.RequestedAt,
			&i.CompletedAt,
			&i.SupersededAt,
			&i.ConfirmedByAccountID,
			&i.PhysicalDocumentReference,
			&i.SignedDate,
			&i.ArchiveNote,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersions = `-- name: ListVersions :many
SELECT id, status, human_revision, pdf_file_id, pdf_sha256, effective_at, published_at, created_by_account_id, created_at, updated_at FROM laborordnung_versions ORDER BY COALESCE(effective_at, created_at) DESC, id DESC
`

func (q *Queries) ListVersions(ctx context.Context) ([]LaborordnungVersion, error) {
	rows, err := q.db.Query(ctx, listVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LaborordnungVersion{}
	for rows.Next() {
		var i LaborordnungVersion
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.HumanRevision,
			&i.PdfFileID,
			&i.PdfSha256,
			&i.EffectiveAt,
			&i.PublishedAt,
			&i.CreatedByAccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPerson = `-- name: LockPerson :exec
SELECT id FROM people WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockPerson(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockPerson, id)
	return err
}

const publishVersion = `-- name: PublishVersion :one
UPDATE laborordnung_versions
SET status = 'published', effective_at = $1, published_at = now(), updated_at = now()
WHERE id = $2 AND status = 'draft'
RETURNING id, status, human_revision, pdf_file_id, pdf_sha256, effective_at, published_at, created_by_account_id, created_at, updated_at
`

type PublishVersionParams struct {
	EffectiveAt pgtype.Timestamptz
	ID          uuid.UUID
}

func (q *Queries) PublishVersion(ctx context.Context, arg PublishVersionParams) (LaborordnungVersion, error) {
	row := q.db.QueryRow(ctx, publishVersion, arg.EffectiveAt, arg.ID)
	var i LaborordnungVersion
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.HumanRevision,
		&i.PdfFileID,
		&i.PdfSha256,
		&i.EffectiveAt,
		&i.PublishedAt,
		&i.CreatedByAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const supersedePendingRequest = `-- name: SupersedePendingRequest :exec
UPDATE laborordnung_requests
SET status = 'superseded', superseded_at = now(), updated_at = now()
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) SupersedePendingRequest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, supersedePendingRequest, id)
	return err
}
