// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package laborordnungdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ConfirmRequest(ctx context.Context, arg ConfirmRequestParams) (LaborordnungRequest, error)
	CreateRequest(ctx context.Context, arg CreateRequestParams) (LaborordnungRequest, error)
	CreateVersion(ctx context.Context, arg CreateVersionParams) (LaborordnungVersion, error)
	GetCurrentVersion(ctx context.Context) (LaborordnungVersion, error)
	GetLatestCompletedRequest(ctx context.Context, personID uuid.UUID) (LaborordnungRequest, error)
	GetPendingRequest(ctx context.Context, personID uuid.UUID) (LaborordnungRequest, error)
	GetPendingRequestForStatus(ctx context.Context, personID uuid.UUID) (LaborordnungRequest, error)
	GetPersonMode(ctx context.Context, personID uuid.UUID) (string, error)
	GetPersonName(ctx context.Context, id uuid.UUID) (GetPersonNameRow, error)
	GetRequestForUpdate(ctx context.Context, id uuid.UUID) (LaborordnungRequest, error)
	GetVersion(ctx context.Context, id uuid.UUID) (LaborordnungVersion, error)
	ListRequests(ctx context.Context) ([]LaborordnungRequest, error)
	ListVersions(ctx context.Context) ([]LaborordnungVersion, error)
	LockPerson(ctx context.Context, id uuid.UUID) error
	PublishVersion(ctx context.Context, arg PublishVersionParams) (LaborordnungVersion, error)
	SupersedePendingRequest(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
