// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package auditdb

import (
	"context"
	"time"
)

type Querier interface {
	DeleteAuditEventsBefore(ctx context.Context, beforeTime time.Time) (int64, error)
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (AuditEvent, error)
	ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]ListAuditEventsRow, error)
}

var _ Querier = (*Queries)(nil)
