// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package auditdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAuditEventsBefore = `-- name: DeleteAuditEventsBefore :execrows
DELETE FROM audit_events WHERE occurred_at < $1
`

func (q *Queries) DeleteAuditEventsBefore(ctx context.Context, beforeTime time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAuditEventsBefore, beforeTime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertAuditEvent = `-- name: InsertAuditEvent :one
INSERT INTO audit_events (id, actor_account_id, action, resource_type, resource_id, request_id, changed_fields, metadata, source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8::text::jsonb, $9)
RETURNING id, actor_account_id, action, resource_type, resource_id, occurred_at, request_id, changed_fields, metadata, source
`

type InsertAuditEventParams struct {
	ID             uuid.UUID
	ActorAccountID *uuid.UUID
	Action         string
	ResourceType   string
	ResourceID     *uuid.UUID
	RequestID      *uuid.UUID
	ChangedFields  []string
	Metadata       string
	Source         string
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, insertAuditEvent,
		arg.ID,
		arg.ActorAccountID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.RequestID,
		arg.ChangedFields,
		arg.Metadata,
		arg.Source,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.ActorAccountID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.OccurredAt,
		&i.RequestID,
		&i.ChangedFields,
		&i.Metadata,
		&i.Source,
	)
	return i, err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT ae.id, ae.actor_account_id, ae.action, ae.resource_type, ae.resource_id, ae.occurred_at, ae.request_id, ae.changed_fields, ae.metadata, ae.source FROM audit_events ae
WHERE ($1::timestamptz IS NULL OR (occurred_at, id) < ($1::timestamptz, $2::uuid))
  AND ($3::uuid IS NULL OR ae.actor_account_id = $3::uuid)
  AND ($4::text IS NULL OR ae.action = $4::text)
  AND ($5::text IS NULL OR ae.resource_type = $5::text)
  AND ($6::uuid IS NULL OR ae.resource_id = $6::uuid)
  AND ($7::timestamptz IS NULL OR ae.occurred_at >= $7::timestamptz)
  AND ($8::timestamptz IS NULL OR ae.occurred_at <= $8::timestamptz)
ORDER BY ae.occurred_at DESC, ae.id DESC LIMIT $9
`

type ListAuditEventsParams struct {
	BeforeTime     pgtype.Timestamptz
	BeforeID       *uuid.UUID
	ActorAccountID *uuid.UUID
	Action         *string
	ResourceType   *string
	ResourceID     *uuid.UUID
	OccurredFrom   pgtype.Timestamptz
	OccurredTo     pgtype.Timestamptz
	PageLimit      int32
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents,
		arg.BeforeTime,
		arg.BeforeID,
		arg.ActorAccountID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.OccurredFrom,
		arg.OccurredTo,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ActorAccountID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.OccurredAt,
			&i.RequestID,
			&i.ChangedFields,
			&i.Metadata,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
