// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package ordersdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activeReceipts = `-- name: ActiveReceipts :many
SELECT p.id, p.reference, p.entry_kind, p.method, p.amount, p.currency, p.occurred_at, p.recorded_at, p.actor_account_id, p.reverses_payment_id, p.reversed_payment_reference, p.reversal_reason_kind, p.reason, p.external_source, p.external_reference, p.external_invoice_request_id FROM payments p JOIN payment_allocations a ON a.payment_id=p.id WHERE a.order_id=$1 GROUP BY p.id HAVING sum(a.amount)>0 ORDER BY p.id
`

func (q *Queries) ActiveReceipts(ctx context.Context, orderID *uuid.UUID) ([]Payment, error) {
	rows, err := q.db.Query(ctx, activeReceipts, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.Reference,
			&i.EntryKind,
			&i.Method,
			&i.Amount,
			&i.Currency,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.ActorAccountID,
			&i.ReversesPaymentID,
			&i.ReversedPaymentReference,
			&i.ReversalReasonKind,
			&i.Reason,
			&i.ExternalSource,
			&i.ExternalReference,
			&i.ExternalInvoiceRequestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const activeRequest = `-- name: ActiveRequest :one
SELECT id, reference, order_id, order_reference, provider, state, currency, requested_amount, supersedes_request_id, version, created_at FROM external_invoice_requests WHERE order_id=$1 AND state<>'cancelled'
`

func (q *Queries) ActiveRequest(ctx context.Context, orderID *uuid.UUID) (ExternalInvoiceRequest, error) {
	row := q.db.QueryRow(ctx, activeRequest, orderID)
	var i ExternalInvoiceRequest
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.OrderID,
		&i.OrderReference,
		&i.Provider,
		&i.State,
		&i.Currency,
		&i.RequestedAmount,
		&i.SupersedesRequestID,
		&i.Version,
		&i.CreatedAt,
	)
	return i, err
}

const allocatedOrderID = `-- name: AllocatedOrderID :one
SELECT order_id FROM payment_allocations WHERE payment_id=$1 GROUP BY order_id HAVING sum(amount)>0
`

func (q *Queries) AllocatedOrderID(ctx context.Context, paymentID *uuid.UUID) (*uuid.UUID, error) {
	row := q.db.QueryRow(ctx, allocatedOrderID, paymentID)
	var order_id *uuid.UUID
	err := row.Scan(&order_id)
	return order_id, err
}

const bumpOrder = `-- name: BumpOrder :exec
UPDATE orders SET version=version+1,updated_at=now() WHERE id=$1
`

func (q *Queries) BumpOrder(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, bumpOrder, id)
	return err
}

const captureCustomer = `-- name: CaptureCustomer :exec
INSERT INTO order_customer_snapshots(order_id,display_name,organization_kind) VALUES($1,$2,$3)
`

type CaptureCustomerParams struct {
	OrderID          uuid.UUID
	DisplayName      string
	OrganizationKind *string
}

func (q *Queries) CaptureCustomer(ctx context.Context, arg CaptureCustomerParams) error {
	_, err := q.db.Exec(ctx, captureCustomer, arg.OrderID, arg.DisplayName, arg.OrganizationKind)
	return err
}

const claimJob = `-- name: ClaimJob :exec
INSERT INTO order_job_claims(machine_job_id,order_item_id) VALUES($1,$2)
`

type ClaimJobParams struct {
	MachineJobID uuid.UUID
	OrderItemID  uuid.UUID
}

func (q *Queries) ClaimJob(ctx context.Context, arg ClaimJobParams) error {
	_, err := q.db.Exec(ctx, claimJob, arg.MachineJobID, arg.OrderItemID)
	return err
}

const committedReplacement = `-- name: CommittedReplacement :one
SELECT id,reference FROM orders WHERE replaces_order_id=$1 AND status IN ('finalized','reversed')
`

type CommittedReplacementRow struct {
	ID        uuid.UUID
	Reference string
}

func (q *Queries) CommittedReplacement(ctx context.Context, replacesOrderID *uuid.UUID) (CommittedReplacementRow, error) {
	row := q.db.QueryRow(ctx, committedReplacement, replacesOrderID)
	var i CommittedReplacementRow
	err := row.Scan(&i.ID, &i.Reference)
	return i, err
}

const countOrders = `-- name: CountOrders :one
SELECT count(*) FROM orders WHERE ($1::text='' OR reference ILIKE '%'||$1||'%') AND ($2::text='' OR status=$2)
`

type CountOrdersParams struct {
	Search string
	Status string
}

func (q *Queries) CountOrders(ctx context.Context, arg CountOrdersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrders, arg.Search, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPayments = `-- name: CountPayments :one
SELECT count(*) FROM payments WHERE ($1::text='' OR method=$1) AND ($2::timestamptz IS NULL OR occurred_at>=$2) AND ($3::timestamptz IS NULL OR occurred_at<$3)
`

type CountPaymentsParams struct {
	Method   string
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

func (q *Queries) CountPayments(ctx context.Context, arg CountPaymentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPayments, arg.Method, arg.FromTime, arg.ToTime)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRequests = `-- name: CountRequests :one
SELECT count(*) FROM external_invoice_requests WHERE ($1::text='' OR reference ILIKE '%'||$1||'%') AND ($2::text='' OR state=$2)
`

type CountRequestsParams struct {
	Search string
	Status string
}

func (q *Queries) CountRequests(ctx context.Context, arg CountRequestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRequests, arg.Search, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders(id,reference,customer_kind,customer_person_id,customer_organization_id,fulfillment_mode,created_by_account_id,replaces_order_id,replaces_order_reference)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id, reference, status, currency, customer_kind, customer_person_id, customer_organization_id, fulfillment_mode, total_amount, replaces_order_id, replaces_order_reference, version, created_at, updated_at, created_by_account_id, finalized_at, cancelled_at, reversed_at
`

type CreateOrderParams struct {
	ID                     uuid.UUID
	Reference              string
	CustomerKind           string
	CustomerPersonID       *uuid.UUID
	CustomerOrganizationID *uuid.UUID
	FulfillmentMode        string
	CreatedByAccountID     *uuid.UUID
	ReplacesOrderID        *uuid.UUID
	ReplacesOrderReference *string
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.Reference,
		arg.CustomerKind,
		arg.CustomerPersonID,
		arg.CustomerOrganizationID,
		arg.FulfillmentMode,
		arg.CreatedByAccountID,
		arg.ReplacesOrderID,
		arg.ReplacesOrderReference,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.Status,
		&i.Currency,
		&i.CustomerKind,
		&i.CustomerPersonID,
		&i.CustomerOrganizationID,
		&i.FulfillmentMode,
		&i.TotalAmount,
		&i.ReplacesOrderID,
		&i.ReplacesOrderReference,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByAccountID,
		&i.FinalizedAt,
		&i.CancelledAt,
		&i.ReversedAt,
	)
	return i, err
}

const createRequest = `-- name: CreateRequest :one
INSERT INTO external_invoice_requests(id,reference,order_id,order_reference,currency,requested_amount,supersedes_request_id) VALUES($1,$2,$3,$4,'EUR',$5,$6) RETURNING id, reference, order_id, order_reference, provider, state, currency, requested_amount, supersedes_request_id, version, created_at
`

type CreateRequestParams struct {
	ID                  uuid.UUID
	Reference           string
	OrderID             *uuid.UUID
	OrderReference      string
	RequestedAmount     pgtype.Numeric
	SupersedesRequestID *uuid.UUID
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (ExternalInvoiceRequest, error) {
	row := q.db.QueryRow(ctx, createRequest,
		arg.ID,
		arg.Reference,
		arg.OrderID,
		arg.OrderReference,
		arg.RequestedAmount,
		arg.SupersedesRequestID,
	)
	var i ExternalInvoiceRequest
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.OrderID,
		&i.OrderReference,
		&i.Provider,
		&i.State,
		&i.Currency,
		&i.RequestedAmount,
		&i.SupersedesRequestID,
		&i.Version,
		&i.CreatedAt,
	)
	return i, err
}

const createRequestDetails = `-- name: CreateRequestDetails :exec
INSERT INTO external_invoice_request_details(request_id,recipient_kind,recipient_person_id,recipient_organization_id,item_summary) VALUES($1,$2,$3,$4,$5)
`

type CreateRequestDetailsParams struct {
	RequestID               uuid.UUID
	RecipientKind           string
	RecipientPersonID       *uuid.UUID
	RecipientOrganizationID *uuid.UUID
	ItemSummary             []byte
}

func (q *Queries) CreateRequestDetails(ctx context.Context, arg CreateRequestDetailsParams) error {
	_, err := q.db.Exec(ctx, createRequestDetails,
		arg.RequestID,
		arg.RecipientKind,
		arg.RecipientPersonID,
		arg.RecipientOrganizationID,
		arg.ItemSummary,
	)
	return err
}

const getCustomerName = `-- name: GetCustomerName :one
SELECT COALESCE(s.display_name,p.first_name || ' ' || p.last_name,g.name)::text AS display_name
FROM orders o LEFT JOIN order_customer_snapshots s ON s.order_id=o.id
LEFT JOIN people p ON p.id=o.customer_person_id LEFT JOIN organizations g ON g.id=o.customer_organization_id
WHERE o.id=$1 AND COALESCE(s.display_name,p.first_name || ' ' || p.last_name,g.name) IS NOT NULL
`

func (q *Queries) GetCustomerName(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getCustomerName, id)
	var display_name string
	err := row.Scan(&display_name)
	return display_name, err
}

const getItem = `-- name: GetItem :one
SELECT id, order_id, position, kind, description, quantity, unit, unit_price, amount, source_machine_job_id, source_job_version, machine_job_snapshot, snapshot_schema_version, created_at, created_by_account_id, removed_at, removed_by_account_id FROM order_items WHERE id=$1 AND order_id=$2
`

type GetItemParams struct {
	ID      uuid.UUID
	OrderID uuid.UUID
}

func (q *Queries) GetItem(ctx context.Context, arg GetItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, getItem, arg.ID, arg.OrderID)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Position,
		&i.Kind,
		&i.Description,
		&i.Quantity,
		&i.Unit,
		&i.UnitPrice,
		&i.Amount,
		&i.SourceMachineJobID,
		&i.SourceJobVersion,
		&i.MachineJobSnapshot,
		&i.SnapshotSchemaVersion,
		&i.CreatedAt,
		&i.CreatedByAccountID,
		&i.RemovedAt,
		&i.RemovedByAccountID,
	)
	return i, err
}

const getJobClaim = `-- name: GetJobClaim :one
SELECT o.id AS order_id,o.reference,i.source_job_version,j.version AS current_job_version FROM order_job_claims c JOIN order_items i ON i.id=c.order_item_id JOIN orders o ON o.id=i.order_id JOIN machine_jobs j ON j.id=c.machine_job_id WHERE c.machine_job_id=$1
`

type GetJobClaimRow struct {
	OrderID           uuid.UUID
	Reference         string
	SourceJobVersion  *int64
	CurrentJobVersion int64
}

func (q *Queries) GetJobClaim(ctx context.Context, machineJobID uuid.UUID) (GetJobClaimRow, error) {
	row := q.db.QueryRow(ctx, getJobClaim, machineJobID)
	var i GetJobClaimRow
	err := row.Scan(
		&i.OrderID,
		&i.Reference,
		&i.SourceJobVersion,
		&i.CurrentJobVersion,
	)
	return i, err
}

const getOperation = `-- name: GetOperation :one
SELECT id, operation_key, kind, request_fingerprint, actor_account_id, order_id, payment_id, request_id, completed_at FROM order_operations WHERE operation_key=$1
`

func (q *Queries) GetOperation(ctx context.Context, operationKey uuid.UUID) (OrderOperation, error) {
	row := q.db.QueryRow(ctx, getOperation, operationKey)
	var i OrderOperation
	err := row.Scan(
		&i.ID,
		&i.OperationKey,
		&i.Kind,
		&i.RequestFingerprint,
		&i.ActorAccountID,
		&i.OrderID,
		&i.PaymentID,
		&i.RequestID,
		&i.CompletedAt,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, reference, status, currency, customer_kind, customer_person_id, customer_organization_id, fulfillment_mode, total_amount, replaces_order_id, replaces_order_reference, version, created_at, updated_at, created_by_account_id, finalized_at, cancelled_at, reversed_at FROM orders WHERE id=$1
`

func (q *Queries) GetOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.Status,
		&i.Currency,
		&i.CustomerKind,
		&i.CustomerPersonID,
		&i.CustomerOrganizationID,
		&i.FulfillmentMode,
		&i.TotalAmount,
		&i.ReplacesOrderID,
		&i.ReplacesOrderReference,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByAccountID,
		&i.FinalizedAt,
		&i.CancelledAt,
		&i.ReversedAt,
	)
	return i, err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id,name,kind,active FROM organizations WHERE id=$1
`

type GetOrganizationRow struct {
	ID     uuid.UUID
	Name   string
	Kind   string
	Active bool
}

func (q *Queries) GetOrganization(ctx context.Context, id uuid.UUID) (GetOrganizationRow, error) {
	row := q.db.QueryRow(ctx, getOrganization, id)
	var i GetOrganizationRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Active,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, reference, entry_kind, method, amount, currency, occurred_at, recorded_at, actor_account_id, reverses_payment_id, reversed_payment_reference, reversal_reason_kind, reason, external_source, external_reference, external_invoice_request_id FROM payments WHERE id=$1
`

func (q *Queries) GetPayment(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.EntryKind,
		&i.Method,
		&i.Amount,
		&i.Currency,
		&i.OccurredAt,
		&i.RecordedAt,
		&i.ActorAccountID,
		&i.ReversesPaymentID,
		&i.ReversedPaymentReference,
		&i.ReversalReasonKind,
		&i.Reason,
		&i.ExternalSource,
		&i.ExternalReference,
		&i.ExternalInvoiceRequestID,
	)
	return i, err
}

const getPerson = `-- name: GetPerson :one
SELECT id,(first_name||' '||last_name)::text AS display_name FROM people WHERE id=$1
`

type GetPersonRow struct {
	ID          uuid.UUID
	DisplayName string
}

func (q *Queries) GetPerson(ctx context.Context, id uuid.UUID) (GetPersonRow, error) {
	row := q.db.QueryRow(ctx, getPerson, id)
	var i GetPersonRow
	err := row.Scan(&i.ID, &i.DisplayName)
	return i, err
}

const getRequest = `-- name: GetRequest :one
SELECT id, reference, order_id, order_reference, provider, state, currency, requested_amount, supersedes_request_id, version, created_at FROM external_invoice_requests WHERE id=$1
`

func (q *Queries) GetRequest(ctx context.Context, id uuid.UUID) (ExternalInvoiceRequest, error) {
	row := q.db.QueryRow(ctx, getRequest, id)
	var i ExternalInvoiceRequest
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.OrderID,
		&i.OrderReference,
		&i.Provider,
		&i.State,
		&i.Currency,
		&i.RequestedAmount,
		&i.SupersedesRequestID,
		&i.Version,
		&i.CreatedAt,
	)
	return i, err
}

const getRequestDetails = `-- name: GetRequestDetails :one
SELECT request_id, recipient_kind, recipient_name, recipient_person_id, recipient_organization_id, address_line1, address_line2, postal_code, locality, region, country_code, contact_person_id, contact_name, contact_channel, service_starts_on, service_ends_on, service_description, purchase_order_reference, requirements_version, require_purchase_order_reference, item_summary, snapshot_schema_version FROM external_invoice_request_details WHERE request_id=$1
`

func (q *Queries) GetRequestDetails(ctx context.Context, requestID uuid.UUID) (ExternalInvoiceRequestDetail, error) {
	row := q.db.QueryRow(ctx, getRequestDetails, requestID)
	var i ExternalInvoiceRequestDetail
	err := row.Scan(
		&i.RequestID,
		&i.RecipientKind,
		&i.RecipientName,
		&i.RecipientPersonID,
		&i.RecipientOrganizationID,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.PostalCode,
		&i.Locality,
		&i.Region,
		&i.CountryCode,
		&i.ContactPersonID,
		&i.ContactName,
		&i.ContactChannel,
		&i.ServiceStartsOn,
		&i.ServiceEndsOn,
		&i.ServiceDescription,
		&i.PurchaseOrderReference,
		&i.RequirementsVersion,
		&i.RequirePurchaseOrderReference,
		&i.ItemSummary,
		&i.SnapshotSchemaVersion,
	)
	return i, err
}

const getRequirements = `-- name: GetRequirements :one
SELECT organization_id, require_purchase_order_reference, version, updated_at, updated_by_account_id FROM organization_invoicing_requirements WHERE organization_id=$1
`

func (q *Queries) GetRequirements(ctx context.Context, organizationID uuid.UUID) (OrganizationInvoicingRequirement, error) {
	row := q.db.QueryRow(ctx, getRequirements, organizationID)
	var i OrganizationInvoicingRequirement
	err := row.Scan(
		&i.OrganizationID,
		&i.RequirePurchaseOrderReference,
		&i.Version,
		&i.UpdatedAt,
		&i.UpdatedByAccountID,
	)
	return i, err
}

const insertAdjustment = `-- name: InsertAdjustment :exec
INSERT INTO order_adjustments(id,reference,order_id,order_reference,kind,currency,amount,reason,actor_account_id) VALUES($1,$2,$3,$4,'full_reversal','EUR',$5,$6,$7)
`

type InsertAdjustmentParams struct {
	ID             uuid.UUID
	Reference      string
	OrderID        *uuid.UUID
	OrderReference string
	Amount         pgtype.Numeric
	Reason         string
	ActorAccountID *uuid.UUID
}

func (q *Queries) InsertAdjustment(ctx context.Context, arg InsertAdjustmentParams) error {
	_, err := q.db.Exec(ctx, insertAdjustment,
		arg.ID,
		arg.Reference,
		arg.OrderID,
		arg.OrderReference,
		arg.Amount,
		arg.Reason,
		arg.ActorAccountID,
	)
	return err
}

const insertAdjustmentItems = `-- name: InsertAdjustmentItems :exec
INSERT INTO order_adjustment_items(id,adjustment_id,original_order_item_id,original_item_position,amount) VALUES($1,$2,$3,$4,$5)
`

type InsertAdjustmentItemsParams struct {
	ID                   uuid.UUID
	AdjustmentID         uuid.UUID
	OriginalOrderItemID  *uuid.UUID
	OriginalItemPosition int32
	Amount               pgtype.Numeric
}

func (q *Queries) InsertAdjustmentItems(ctx context.Context, arg InsertAdjustmentItemsParams) error {
	_, err := q.db.Exec(ctx, insertAdjustmentItems,
		arg.ID,
		arg.AdjustmentID,
		arg.OriginalOrderItemID,
		arg.OriginalItemPosition,
		arg.Amount,
	)
	return err
}

const insertAllocation = `-- name: InsertAllocation :exec
INSERT INTO payment_allocations(id,payment_id,payment_reference,order_id,order_reference,amount,currency,operation_id,actor_account_id)
VALUES($1,$2,$3,$4,$5,$6,'EUR',$7,$8)
`

type InsertAllocationParams struct {
	ID               uuid.UUID
	PaymentID        *uuid.UUID
	PaymentReference string
	OrderID          *uuid.UUID
	OrderReference   string
	Amount           pgtype.Numeric
	OperationID      uuid.UUID
	ActorAccountID   *uuid.UUID
}

func (q *Queries) InsertAllocation(ctx context.Context, arg InsertAllocationParams) error {
	_, err := q.db.Exec(ctx, insertAllocation,
		arg.ID,
		arg.PaymentID,
		arg.PaymentReference,
		arg.OrderID,
		arg.OrderReference,
		arg.Amount,
		arg.OperationID,
		arg.ActorAccountID,
	)
	return err
}

const insertItem = `-- name: InsertItem :one
INSERT INTO order_items(id,order_id,position,kind,description,quantity,unit,unit_price,amount,source_machine_job_id,source_job_version,machine_job_snapshot,created_by_account_id)
VALUES($1,$2,(SELECT COALESCE(max(position),0)+1 FROM order_items WHERE order_id=$2),$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING id, order_id, position, kind, description, quantity, unit, unit_price, amount, source_machine_job_id, source_job_version, machine_job_snapshot, snapshot_schema_version, created_at, created_by_account_id, removed_at, removed_by_account_id
`

type InsertItemParams struct {
	ID                 uuid.UUID
	OrderID            uuid.UUID
	Kind               string
	Description        string
	Quantity           pgtype.Numeric
	Unit               string
	UnitPrice          pgtype.Numeric
	Amount             pgtype.Numeric
	SourceMachineJobID *uuid.UUID
	SourceJobVersion   *int64
	MachineJobSnapshot []byte
	CreatedByAccountID *uuid.UUID
}

func (q *Queries) InsertItem(ctx context.Context, arg InsertItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, insertItem,
		arg.ID,
		arg.OrderID,
		arg.Kind,
		arg.Description,
		arg.Quantity,
		arg.Unit,
		arg.UnitPrice,
		arg.Amount,
		arg.SourceMachineJobID,
		arg.SourceJobVersion,
		arg.MachineJobSnapshot,
		arg.CreatedByAccountID,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Position,
		&i.Kind,
		&i.Description,
		&i.Quantity,
		&i.Unit,
		&i.UnitPrice,
		&i.Amount,
		&i.SourceMachineJobID,
		&i.SourceJobVersion,
		&i.MachineJobSnapshot,
		&i.SnapshotSchemaVersion,
		&i.CreatedAt,
		&i.CreatedByAccountID,
		&i.RemovedAt,
		&i.RemovedByAccountID,
	)
	return i, err
}

const insertPayment = `-- name: InsertPayment :one
INSERT INTO payments(id,reference,entry_kind,method,amount,currency,occurred_at,actor_account_id,reverses_payment_id,reversed_payment_reference,reversal_reason_kind,reason,external_source,external_reference,external_invoice_request_id)
VALUES($1,$2,$3,$4,$5,'EUR',$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING id, reference, entry_kind, method, amount, currency, occurred_at, recorded_at, actor_account_id, reverses_payment_id, reversed_payment_reference, reversal_reason_kind, reason, external_source, external_reference, external_invoice_request_id
`

type InsertPaymentParams struct {
	ID                       uuid.UUID
	Reference                string
	EntryKind                string
	Method                   string
	Amount                   pgtype.Numeric
	OccurredAt               time.Time
	ActorAccountID           *uuid.UUID
	ReversesPaymentID        *uuid.UUID
	ReversedPaymentReference *string
	ReversalReasonKind       *string
	Reason                   string
	ExternalSource           string
	ExternalReference        string
	ExternalInvoiceRequestID *uuid.UUID
}

func (q *Queries) InsertPayment(ctx context.Context, arg InsertPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, insertPayment,
		arg.ID,
		arg.Reference,
		arg.EntryKind,
		arg.Method,
		arg.Amount,
		arg.OccurredAt,
		arg.ActorAccountID,
		arg.ReversesPaymentID,
		arg.ReversedPaymentReference,
		arg.ReversalReasonKind,
		arg.Reason,
		arg.ExternalSource,
		arg.ExternalReference,
		arg.ExternalInvoiceRequestID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.EntryKind,
		&i.Method,
		&i.Amount,
		&i.Currency,
		&i.OccurredAt,
		&i.RecordedAt,
		&i.ActorAccountID,
		&i.ReversesPaymentID,
		&i.ReversedPaymentReference,
		&i.ReversalReasonKind,
		&i.Reason,
		&i.ExternalSource,
		&i.ExternalReference,
		&i.ExternalInvoiceRequestID,
	)
	return i, err
}

const insertRequestEvent = `-- name: InsertRequestEvent :exec
INSERT INTO external_invoice_request_events(id,request_id,kind,external_reference,reconciliation_kind,reason,effective_at,actor_account_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8)
`

type InsertRequestEventParams struct {
	ID                 uuid.UUID
	RequestID          uuid.UUID
	Kind               string
	ExternalReference  string
	ReconciliationKind string
	Reason             string
	EffectiveAt        time.Time
	ActorAccountID     *uuid.UUID
}

func (q *Queries) InsertRequestEvent(ctx context.Context, arg InsertRequestEventParams) error {
	_, err := q.db.Exec(ctx, insertRequestEvent,
		arg.ID,
		arg.RequestID,
		arg.Kind,
		arg.ExternalReference,
		arg.ReconciliationKind,
		arg.Reason,
		arg.EffectiveAt,
		arg.ActorAccountID,
	)
	return err
}

const latestRequest = `-- name: LatestRequest :one
SELECT id, reference, order_id, order_reference, provider, state, currency, requested_amount, supersedes_request_id, version, created_at FROM external_invoice_requests WHERE order_id=$1 ORDER BY created_at DESC,id DESC LIMIT 1
`

func (q *Queries) LatestRequest(ctx context.Context, orderID *uuid.UUID) (ExternalInvoiceRequest, error) {
	row := q.db.QueryRow(ctx, latestRequest, orderID)
	var i ExternalInvoiceRequest
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.OrderID,
		&i.OrderReference,
		&i.Provider,
		&i.State,
		&i.Currency,
		&i.RequestedAmount,
		&i.SupersedesRequestID,
		&i.Version,
		&i.CreatedAt,
	)
	return i, err
}

const listAdjustments = `-- name: ListAdjustments :many
SELECT id, reference, order_id, order_reference, kind, currency, amount, reason, actor_account_id, created_at FROM order_adjustments WHERE order_id=$1 ORDER BY created_at
`

func (q *Queries) ListAdjustments(ctx context.Context, orderID *uuid.UUID) ([]OrderAdjustment, error) {
	rows, err := q.db.Query(ctx, listAdjustments, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderAdjustment{}
	for rows.Next() {
		var i OrderAdjustment
		if err := rows.Scan(
			&i.ID,
			&i.Reference,
			&i.OrderID,
			&i.OrderReference,
			&i.Kind,
			&i.Currency,
			&i.Amount,
			&i.Reason,
			&i.ActorAccountID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllocations = `-- name: ListAllocations :many
SELECT id, payment_id, payment_reference, order_id, order_reference, amount, currency, operation_id, reverses_allocation_id, actor_account_id, created_at FROM payment_allocations WHERE order_id=$1 ORDER BY created_at,id
`

func (q *Queries) ListAllocations(ctx context.Context, orderID *uuid.UUID) ([]PaymentAllocation, error) {
	rows, err := q.db.Query(ctx, listAllocations, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentAllocation{}
	for rows.Next() {
		var i PaymentAllocation
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.PaymentReference,
			&i.OrderID,
			&i.OrderReference,
			&i.Amount,
			&i.Currency,
			&i.OperationID,
			&i.ReversesAllocationID,
			&i.ActorAccountID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
SELECT i.id, i.order_id, i.position, i.kind, i.description, i.quantity, i.unit, i.unit_price, i.amount, i.source_machine_job_id, i.source_job_version, i.machine_job_snapshot, i.snapshot_schema_version, i.created_at, i.created_by_account_id, i.removed_at, i.removed_by_account_id,j.version AS current_job_version FROM order_items i LEFT JOIN machine_jobs j ON j.id=i.source_machine_job_id WHERE i.order_id=$1 ORDER BY i.position
`

type ListItemsRow struct {
	ID                    uuid.UUID
	OrderID               uuid.UUID
	Position              int32
	Kind                  string
	Description           string
	Quantity              pgtype.Numeric
	Unit                  string
	UnitPrice             pgtype.Numeric
	Amount                pgtype.Numeric
	SourceMachineJobID    *uuid.UUID
	SourceJobVersion      *int64
	MachineJobSnapshot    []byte
	SnapshotSchemaVersion int32
	CreatedAt             time.Time
	CreatedByAccountID    *uuid.UUID
	RemovedAt             pgtype.Timestamptz
	RemovedByAccountID    *uuid.UUID
	CurrentJobVersion     *int64
}

func (q *Queries) ListItems(ctx context.Context, orderID uuid.UUID) ([]ListItemsRow, error) {
	rows, err := q.db.Query(ctx, listItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemsRow{}
	for rows.Next() {
		var i ListItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Position,
			&i.Kind,
			&i.Description,
			&i.Quantity,
			&i.Unit,
			&i.UnitPrice,
			&i.Amount,
			&i.SourceMachineJobID,
			&i.SourceJobVersion,
			&i.MachineJobSnapshot,
			&i.SnapshotSchemaVersion,
			&i.CreatedAt,
			&i.CreatedByAccountID,
			&i.RemovedAt,
			&i.RemovedByAccountID,
			&i.CurrentJobVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT id, reference, status, currency, customer_kind, customer_person_id, customer_organization_id, fulfillment_mode, total_amount, replaces_order_id, replaces_order_reference, version, created_at, updated_at, created_by_account_id, finalized_at, cancelled_at, reversed_at FROM orders WHERE ($1::text='' OR reference ILIKE '%'||$1||'%') AND ($2::text='' OR status=$2) ORDER BY created_at DESC,id DESC LIMIT $4 OFFSET $3
`

type ListOrdersParams struct {
	Search     string
	Status     string
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders,
		arg.Search,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Reference,
			&i.Status,
			&i.Currency,
			&i.CustomerKind,
			&i.CustomerPersonID,
			&i.CustomerOrganizationID,
			&i.FulfillmentMode,
			&i.TotalAmount,
			&i.ReplacesOrderID,
			&i.ReplacesOrderReference,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByAccountID,
			&i.FinalizedAt,
			&i.CancelledAt,
			&i.ReversedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayments = `-- name: ListPayments :many
SELECT id, reference, entry_kind, method, amount, currency, occurred_at, recorded_at, actor_account_id, reverses_payment_id, reversed_payment_reference, reversal_reason_kind, reason, external_source, external_reference, external_invoice_request_id FROM payments WHERE ($1::text='' OR method=$1) AND ($2::timestamptz IS NULL OR occurred_at>=$2) AND ($3::timestamptz IS NULL OR occurred_at<$3) ORDER BY occurred_at DESC,id DESC LIMIT $5 OFFSET $4
`

type ListPaymentsParams struct {
	Method     string
	FromTime   pgtype.Timestamptz
	ToTime     pgtype.Timestamptz
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListPayments(ctx context.Context, arg ListPaymentsParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPayments,
		arg.Method,
		arg.FromTime,
		arg.ToTime,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.Reference,
			&i.EntryKind,
			&i.Method,
			&i.Amount,
			&i.Currency,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.ActorAccountID,
			&i.ReversesPaymentID,
			&i.ReversedPaymentReference,
			&i.ReversalReasonKind,
			&i.Reason,
			&i.ExternalSource,
			&i.ExternalReference,
			&i.ExternalInvoiceRequestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequests = `-- name: ListRequests :many
SELECT id, reference, order_id, order_reference, provider, state, currency, requested_amount, supersedes_request_id, version, created_at FROM external_invoice_requests WHERE ($1::text='' OR reference ILIKE '%'||$1||'%') AND ($2::text='' OR state=$2) ORDER BY created_at DESC,id DESC LIMIT $4 OFFSET $3
`

type ListRequestsParams struct {
	Search     string
	Status     string
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListRequests(ctx context.Context, arg ListRequestsParams) ([]ExternalInvoiceRequest, error) {
	rows, err := q.db.Query(ctx, listRequests,
		arg.Search,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExternalInvoiceRequest{}
	for rows.Next() {
		var i ExternalInvoiceRequest
		if err := rows.Scan(
			&i.ID,
			&i.Reference,
			&i.OrderID,
			&i.OrderReference,
			&i.Provider,
			&i.State,
			&i.Currency,
			&i.RequestedAmount,
			&i.SupersedesRequestID,
			&i.Version,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOperation = `-- name: LockOperation :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text,0))
`

func (q *Queries) LockOperation(ctx context.Context, operationKey string) error {
	_, err := q.db.Exec(ctx, lockOperation, operationKey)
	return err
}

const lockOrder = `-- name: LockOrder :one
SELECT id, reference, status, currency, customer_kind, customer_person_id, customer_organization_id, fulfillment_mode, total_amount, replaces_order_id, replaces_order_reference, version, created_at, updated_at, created_by_account_id, finalized_at, cancelled_at, reversed_at FROM orders WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, lockOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.Status,
		&i.Currency,
		&i.CustomerKind,
		&i.CustomerPersonID,
		&i.CustomerOrganizationID,
		&i.FulfillmentMode,
		&i.TotalAmount,
		&i.ReplacesOrderID,
		&i.ReplacesOrderReference,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByAccountID,
		&i.FinalizedAt,
		&i.CancelledAt,
		&i.ReversedAt,
	)
	return i, err
}

const lockOrganizationRequirements = `-- name: LockOrganizationRequirements :exec
SELECT id FROM organizations WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockOrganizationRequirements(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockOrganizationRequirements, id)
	return err
}

const lockPayment = `-- name: LockPayment :one
SELECT id, reference, entry_kind, method, amount, currency, occurred_at, recorded_at, actor_account_id, reverses_payment_id, reversed_payment_reference, reversal_reason_kind, reason, external_source, external_reference, external_invoice_request_id FROM payments WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockPayment(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, lockPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.EntryKind,
		&i.Method,
		&i.Amount,
		&i.Currency,
		&i.OccurredAt,
		&i.RecordedAt,
		&i.ActorAccountID,
		&i.ReversesPaymentID,
		&i.ReversedPaymentReference,
		&i.ReversalReasonKind,
		&i.Reason,
		&i.ExternalSource,
		&i.ExternalReference,
		&i.ExternalInvoiceRequestID,
	)
	return i, err
}

const lockRequest = `-- name: LockRequest :one
SELECT id, reference, order_id, order_reference, provider, state, currency, requested_amount, supersedes_request_id, version, created_at FROM external_invoice_requests WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockRequest(ctx context.Context, id uuid.UUID) (ExternalInvoiceRequest, error) {
	row := q.db.QueryRow(ctx, lockRequest, id)
	var i ExternalInvoiceRequest
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.OrderID,
		&i.OrderReference,
		&i.Provider,
		&i.State,
		&i.Currency,
		&i.RequestedAmount,
		&i.SupersedesRequestID,
		&i.Version,
		&i.CreatedAt,
	)
	return i, err
}

const nextAdjustmentReference = `-- name: NextAdjustmentReference :one
SELECT nextval('order_adjustment_reference_sequence')::bigint
`

func (q *Queries) NextAdjustmentReference(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextAdjustmentReference)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const nextOrderReference = `-- name: NextOrderReference :one
SELECT nextval('order_reference_sequence')::bigint
`

func (q *Queries) NextOrderReference(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextOrderReference)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const nextPaymentReference = `-- name: NextPaymentReference :one
SELECT nextval('payment_reference_sequence')::bigint
`

func (q *Queries) NextPaymentReference(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextPaymentReference)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const nextRequestReference = `-- name: NextRequestReference :one
SELECT nextval('external_invoice_request_reference_sequence')::bigint
`

func (q *Queries) NextRequestReference(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextRequestReference)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const paymentAllocations = `-- name: PaymentAllocations :many
SELECT id, payment_id, payment_reference, order_id, order_reference, amount, currency, operation_id, reverses_allocation_id, actor_account_id, created_at FROM payment_allocations WHERE payment_id=$1 ORDER BY created_at,id
`

func (q *Queries) PaymentAllocations(ctx context.Context, paymentID *uuid.UUID) ([]PaymentAllocation, error) {
	rows, err := q.db.Query(ctx, paymentAllocations, paymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentAllocation{}
	for rows.Next() {
		var i PaymentAllocation
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.PaymentReference,
			&i.OrderID,
			&i.OrderReference,
			&i.Amount,
			&i.Currency,
			&i.OperationID,
			&i.ReversesAllocationID,
			&i.ActorAccountID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const paymentReversalExists = `-- name: PaymentReversalExists :one
SELECT EXISTS(SELECT 1 FROM payments WHERE reverses_payment_id=$1) AS reversed
`

func (q *Queries) PaymentReversalExists(ctx context.Context, reversesPaymentID *uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, paymentReversalExists, reversesPaymentID)
	var reversed bool
	err := row.Scan(&reversed)
	return reversed, err
}

const reconciliationTotals = `-- name: ReconciliationTotals :many
SELECT method,COALESCE(sum(CASE WHEN entry_kind='receipt' THEN amount ELSE -amount END),0)::numeric AS amount FROM payments WHERE ($1::timestamptz IS NULL OR occurred_at>=$1) AND ($2::timestamptz IS NULL OR occurred_at<$2) GROUP BY method
`

type ReconciliationTotalsParams struct {
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type ReconciliationTotalsRow struct {
	Method string
	Amount pgtype.Numeric
}

func (q *Queries) ReconciliationTotals(ctx context.Context, arg ReconciliationTotalsParams) ([]ReconciliationTotalsRow, error) {
	rows, err := q.db.Query(ctx, reconciliationTotals, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconciliationTotalsRow{}
	for rows.Next() {
		var i ReconciliationTotalsRow
		if err := rows.Scan(&i.Method, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseItemClaim = `-- name: ReleaseItemClaim :exec
DELETE FROM order_job_claims WHERE order_item_id=$1
`

func (q *Queries) ReleaseItemClaim(ctx context.Context, orderItemID uuid.UUID) error {
	_, err := q.db.Exec(ctx, releaseItemClaim, orderItemID)
	return err
}

const releaseOrderClaims = `-- name: ReleaseOrderClaims :exec
DELETE FROM order_job_claims WHERE order_item_id IN (SELECT id FROM order_items WHERE order_id=$1)
`

func (q *Queries) ReleaseOrderClaims(ctx context.Context, orderID uuid.UUID) error {
	_, err := q.db.Exec(ctx, releaseOrderClaims, orderID)
	return err
}

const removeItem = `-- name: RemoveItem :exec
UPDATE order_items SET removed_at=now(),removed_by_account_id=$2 WHERE id=$1
`

type RemoveItemParams struct {
	ID                 uuid.UUID
	RemovedByAccountID *uuid.UUID
}

func (q *Queries) RemoveItem(ctx context.Context, arg RemoveItemParams) error {
	_, err := q.db.Exec(ctx, removeItem, arg.ID, arg.RemovedByAccountID)
	return err
}

const requestEvents = `-- name: RequestEvents :many
SELECT id, request_id, kind, external_reference, reconciliation_kind, reason, effective_at, recorded_at, actor_account_id FROM external_invoice_request_events WHERE request_id=$1 ORDER BY recorded_at,id
`

func (q *Queries) RequestEvents(ctx context.Context, requestID uuid.UUID) ([]ExternalInvoiceRequestEvent, error) {
	rows, err := q.db.Query(ctx, requestEvents, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExternalInvoiceRequestEvent{}
	for rows.Next() {
		var i ExternalInvoiceRequestEvent
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.Kind,
			&i.ExternalReference,
			&i.ReconciliationKind,
			&i.Reason,
			&i.EffectiveAt,
			&i.RecordedAt,
			&i.ActorAccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveOperation = `-- name: SaveOperation :exec
INSERT INTO order_operations(id,operation_key,kind,request_fingerprint,actor_account_id,order_id,payment_id,request_id)
VALUES($1,$2,$3,$4,$5,$6,$7,$8)
`

type SaveOperationParams struct {
	ID                 uuid.UUID
	OperationKey       uuid.UUID
	Kind               string
	RequestFingerprint []byte
	ActorAccountID     *uuid.UUID
	OrderID            *uuid.UUID
	PaymentID          *uuid.UUID
	RequestID          *uuid.UUID
}

func (q *Queries) SaveOperation(ctx context.Context, arg SaveOperationParams) error {
	_, err := q.db.Exec(ctx, saveOperation,
		arg.ID,
		arg.OperationKey,
		arg.Kind,
		arg.RequestFingerprint,
		arg.ActorAccountID,
		arg.OrderID,
		arg.PaymentID,
		arg.RequestID,
	)
	return err
}

const saveRequirements = `-- name: SaveRequirements :one
INSERT INTO organization_invoicing_requirements(organization_id,require_purchase_order_reference,updated_by_account_id) VALUES($1,$2,$3)
ON CONFLICT(organization_id) DO UPDATE SET require_purchase_order_reference=excluded.require_purchase_order_reference,version=organization_invoicing_requirements.version+1,updated_at=now(),updated_by_account_id=excluded.updated_by_account_id RETURNING organization_id, require_purchase_order_reference, version, updated_at, updated_by_account_id
`

type SaveRequirementsParams struct {
	OrganizationID                uuid.UUID
	RequirePurchaseOrderReference bool
	UpdatedByAccountID            *uuid.UUID
}

func (q *Queries) SaveRequirements(ctx context.Context, arg SaveRequirementsParams) (OrganizationInvoicingRequirement, error) {
	row := q.db.QueryRow(ctx, saveRequirements, arg.OrganizationID, arg.RequirePurchaseOrderReference, arg.UpdatedByAccountID)
	var i OrganizationInvoicingRequirement
	err := row.Scan(
		&i.OrganizationID,
		&i.RequirePurchaseOrderReference,
		&i.Version,
		&i.UpdatedAt,
		&i.UpdatedByAccountID,
	)
	return i, err
}

const sumAllocations = `-- name: SumAllocations :one
SELECT COALESCE(sum(amount),0)::numeric AS amount FROM payment_allocations WHERE order_id=$1
`

func (q *Queries) SumAllocations(ctx context.Context, orderID *uuid.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumAllocations, orderID)
	var amount pgtype.Numeric
	err := row.Scan(&amount)
	return amount, err
}

const transitionOrder = `-- name: TransitionOrder :exec
UPDATE orders SET status=$2,total_amount=$3,version=version+1,updated_at=now(),
finalized_at=CASE WHEN $2::text='finalized' THEN now() ELSE finalized_at END,
cancelled_at=CASE WHEN $2::text='cancelled' THEN now() ELSE cancelled_at END,
reversed_at=CASE WHEN $2::text='reversed' THEN now() ELSE reversed_at END WHERE id=$1
`

type TransitionOrderParams struct {
	ID          uuid.UUID
	Status      string
	TotalAmount pgtype.Numeric
}

func (q *Queries) TransitionOrder(ctx context.Context, arg TransitionOrderParams) error {
	_, err := q.db.Exec(ctx, transitionOrder, arg.ID, arg.Status, arg.TotalAmount)
	return err
}

const transitionRequest = `-- name: TransitionRequest :exec
UPDATE external_invoice_requests SET state=$2,version=version+1 WHERE id=$1
`

type TransitionRequestParams struct {
	ID    uuid.UUID
	State string
}

func (q *Queries) TransitionRequest(ctx context.Context, arg TransitionRequestParams) error {
	_, err := q.db.Exec(ctx, transitionRequest, arg.ID, arg.State)
	return err
}

const updateDraft = `-- name: UpdateDraft :one
UPDATE orders SET customer_kind=$2,customer_person_id=$3,customer_organization_id=$4,fulfillment_mode=$5,version=version+1,updated_at=now() WHERE id=$1 RETURNING id, reference, status, currency, customer_kind, customer_person_id, customer_organization_id, fulfillment_mode, total_amount, replaces_order_id, replaces_order_reference, version, created_at, updated_at, created_by_account_id, finalized_at, cancelled_at, reversed_at
`

type UpdateDraftParams struct {
	ID                     uuid.UUID
	CustomerKind           string
	CustomerPersonID       *uuid.UUID
	CustomerOrganizationID *uuid.UUID
	FulfillmentMode        string
}

func (q *Queries) UpdateDraft(ctx context.Context, arg UpdateDraftParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateDraft,
		arg.ID,
		arg.CustomerKind,
		arg.CustomerPersonID,
		arg.CustomerOrganizationID,
		arg.FulfillmentMode,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.Status,
		&i.Currency,
		&i.CustomerKind,
		&i.CustomerPersonID,
		&i.CustomerOrganizationID,
		&i.FulfillmentMode,
		&i.TotalAmount,
		&i.ReplacesOrderID,
		&i.ReplacesOrderReference,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByAccountID,
		&i.FinalizedAt,
		&i.CancelledAt,
		&i.ReversedAt,
	)
	return i, err
}

const updateRequestDetails = `-- name: UpdateRequestDetails :exec
UPDATE external_invoice_request_details SET recipient_name=$2,address_line1=$3,address_line2=$4,postal_code=$5,locality=$6,region=$7,country_code=$8,contact_person_id=$9,contact_name=$10,contact_channel=$11,service_starts_on=$12,service_ends_on=$13,service_description=$14,purchase_order_reference=$15,requirements_version=$16,require_purchase_order_reference=$17 WHERE request_id=$1
`

type UpdateRequestDetailsParams struct {
	RequestID                     uuid.UUID
	RecipientName                 string
	AddressLine1                  string
	AddressLine2                  string
	PostalCode                    string
	Locality                      string
	Region                        string
	CountryCode                   string
	ContactPersonID               *uuid.UUID
	ContactName                   string
	ContactChannel                string
	ServiceStartsOn               pgtype.Date
	ServiceEndsOn                 pgtype.Date
	ServiceDescription            string
	PurchaseOrderReference        string
	RequirementsVersion           int64
	RequirePurchaseOrderReference bool
}

func (q *Queries) UpdateRequestDetails(ctx context.Context, arg UpdateRequestDetailsParams) error {
	_, err := q.db.Exec(ctx, updateRequestDetails,
		arg.RequestID,
		arg.RecipientName,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.PostalCode,
		arg.Locality,
		arg.Region,
		arg.CountryCode,
		arg.ContactPersonID,
		arg.ContactName,
		arg.ContactChannel,
		arg.ServiceStartsOn,
		arg.ServiceEndsOn,
		arg.ServiceDescription,
		arg.PurchaseOrderReference,
		arg.RequirementsVersion,
		arg.RequirePurchaseOrderReference,
	)
	return err
}
