// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package peopledb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AcquireMasterInvariantLock(ctx context.Context) error
	AssignPersonRole(ctx context.Context, arg AssignPersonRoleParams) (int64, error)
	BumpPersonVersion(ctx context.Context, arg BumpPersonVersionParams) (Person, error)
	CountEnabledMasters(ctx context.Context) (int64, error)
	CountMasterAssignments(ctx context.Context) (int64, error)
	CountPeople(ctx context.Context, arg CountPeopleParams) (int64, error)
	CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error)
	DeletePerson(ctx context.Context, arg DeletePersonParams) (uuid.UUID, error)
	GetAccountByPersonForMutation(ctx context.Context, personID uuid.UUID) (Account, error)
	GetMasterRole(ctx context.Context) (Role, error)
	GetPerson(ctx context.Context, id uuid.UUID) (Person, error)
	GetPersonForDeletion(ctx context.Context, id uuid.UUID) (Person, error)
	GetProfileImage(ctx context.Context, id uuid.UUID) (GetProfileImageRow, error)
	GetRoleForAssignment(ctx context.Context, id uuid.UUID) (Role, error)
	GetRolePermissionGrantsForAssignment(ctx context.Context, roleID uuid.UUID) ([]GetRolePermissionGrantsForAssignmentRow, error)
	IsPersonRoleAssigned(ctx context.Context, arg IsPersonRoleAssignedParams) (bool, error)
	ListPeople(ctx context.Context, arg ListPeopleParams) ([]Person, error)
	ListPersonRoles(ctx context.Context, personID uuid.UUID) ([]Role, error)
	ListPersonRolesByPeople(ctx context.Context, personIds []string) ([]ListPersonRolesByPeopleRow, error)
	ListProfileImageRequirements(ctx context.Context, personIds []string) ([]ListProfileImageRequirementsRow, error)
	PersonRequiresProfileImage(ctx context.Context, personID uuid.UUID) (bool, error)
	RemovePersonRole(ctx context.Context, arg RemovePersonRoleParams) (int64, error)
	SetProfileImage(ctx context.Context, arg SetProfileImageParams) (Person, error)
	UpdatePerson(ctx context.Context, arg UpdatePersonParams) (Person, error)
}

var _ Querier = (*Queries)(nil)
