// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package peopledb

import (
	"context"

	"github.com/google/uuid"
)

const countPeople = `-- name: CountPeople :one
SELECT count(*) FROM people p
WHERE (
       $1::text = ''
       OR p.first_name ILIKE '%' || $1::text || '%'
       OR p.last_name ILIKE '%' || $1::text || '%'
       OR COALESCE(p.email, '') ILIKE '%' || $1::text || '%'
       OR COALESCE(p.phone, '') ILIKE '%' || $1::text || '%'
       OR ($2::boolean AND COALESCE(p.matriculation_number, '') ILIKE '%' || $1::text || '%')
   )
  AND (
       cardinality($3::uuid[]) = 0
       OR EXISTS (
           SELECT 1
           FROM accounts a
           JOIN account_roles ar ON ar.account_id = a.id
           WHERE a.person_id = p.id AND ar.role_id = ANY($3::uuid[])
       )
   )
`

type CountPeopleParams struct {
	Search               string
	IncludeMatriculation bool
	RoleIds              []uuid.UUID
}

func (q *Queries) CountPeople(ctx context.Context, arg CountPeopleParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPeople, arg.Search, arg.IncludeMatriculation, arg.RoleIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPerson = `-- name: CreatePerson :one
INSERT INTO people (id, first_name, last_name, email, phone, matriculation_number, photo_reference)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, first_name, last_name, email, phone, matriculation_number, photo_reference, version, created_at, updated_at, profile_image_file_id, profile_image_source
`

type CreatePersonParams struct {
	ID                  uuid.UUID
	FirstName           string
	LastName            string
	Email               *string
	Phone               *string
	MatriculationNumber *string
	PhotoReference      *string
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, createPerson,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.MatriculationNumber,
		arg.PhotoReference,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.MatriculationNumber,
		&i.PhotoReference,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProfileImageFileID,
		&i.ProfileImageSource,
	)
	return i, err
}

const deletePerson = `-- name: DeletePerson :one
DELETE FROM people WHERE id = $1 AND version = $2
RETURNING id
`

type DeletePersonParams struct {
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) DeletePerson(ctx context.Context, arg DeletePersonParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deletePerson, arg.ID, arg.ExpectedVersion)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getPerson = `-- name: GetPerson :one
SELECT id, first_name, last_name, email, phone, matriculation_number, photo_reference, version, created_at, updated_at, profile_image_file_id, profile_image_source FROM people WHERE id = $1
`

func (q *Queries) GetPerson(ctx context.Context, id uuid.UUID) (Person, error) {
	row := q.db.QueryRow(ctx, getPerson, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.MatriculationNumber,
		&i.PhotoReference,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProfileImageFileID,
		&i.ProfileImageSource,
	)
	return i, err
}

const getPersonForDeletion = `-- name: GetPersonForDeletion :one
SELECT id, first_name, last_name, email, phone, matriculation_number, photo_reference, version, created_at, updated_at, profile_image_file_id, profile_image_source FROM people WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetPersonForDeletion(ctx context.Context, id uuid.UUID) (Person, error) {
	row := q.db.QueryRow(ctx, getPersonForDeletion, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.MatriculationNumber,
		&i.PhotoReference,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProfileImageFileID,
		&i.ProfileImageSource,
	)
	return i, err
}

const getProfileImage = `-- name: GetProfileImage :one
SELECT profile_image_file_id, profile_image_source
FROM people
WHERE id = $1
`

type GetProfileImageRow struct {
	ProfileImageFileID *uuid.UUID
	ProfileImageSource *string
}

func (q *Queries) GetProfileImage(ctx context.Context, id uuid.UUID) (GetProfileImageRow, error) {
	row := q.db.QueryRow(ctx, getProfileImage, id)
	var i GetProfileImageRow
	err := row.Scan(&i.ProfileImageFileID, &i.ProfileImageSource)
	return i, err
}

const listPeople = `-- name: ListPeople :many
SELECT p.id, p.first_name, p.last_name, p.email, p.phone, p.matriculation_number, p.photo_reference, p.version, p.created_at, p.updated_at, p.profile_image_file_id, p.profile_image_source FROM people p
WHERE (
       $1::text = ''
       OR p.first_name ILIKE '%' || $1::text || '%'
       OR p.last_name ILIKE '%' || $1::text || '%'
       OR COALESCE(p.email, '') ILIKE '%' || $1::text || '%'
       OR COALESCE(p.phone, '') ILIKE '%' || $1::text || '%'
       OR ($2::boolean AND COALESCE(p.matriculation_number, '') ILIKE '%' || $1::text || '%')
   )
  AND (
       cardinality($3::uuid[]) = 0
       OR EXISTS (
           SELECT 1
           FROM accounts a
           JOIN account_roles ar ON ar.account_id = a.id
           WHERE a.person_id = p.id AND ar.role_id = ANY($3::uuid[])
       )
   )
ORDER BY lower(last_name), lower(first_name), id
LIMIT $5 OFFSET $4
`

type ListPeopleParams struct {
	Search               string
	IncludeMatriculation bool
	RoleIds              []uuid.UUID
	PageOffset           int32
	PageLimit            int32
}

func (q *Queries) ListPeople(ctx context.Context, arg ListPeopleParams) ([]Person, error) {
	rows, err := q.db.Query(ctx, listPeople,
		arg.Search,
		arg.IncludeMatriculation,
		arg.RoleIds,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Person{}
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.MatriculationNumber,
			&i.PhotoReference,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProfileImageFileID,
			&i.ProfileImageSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfileImageRequirements = `-- name: ListProfileImageRequirements :many
SELECT p.id AS person_id, COALESCE(bool_or(r.profile_image_required), false)::boolean AS required
FROM people p
LEFT JOIN accounts a ON a.person_id = p.id
LEFT JOIN account_roles ar ON ar.account_id = a.id
LEFT JOIN roles r ON r.id = ar.role_id
WHERE p.id = ANY($1::uuid[])
GROUP BY p.id
`

type ListProfileImageRequirementsRow struct {
	PersonID uuid.UUID
	Required bool
}

func (q *Queries) ListProfileImageRequirements(ctx context.Context, personIds []uuid.UUID) ([]ListProfileImageRequirementsRow, error) {
	rows, err := q.db.Query(ctx, listProfileImageRequirements, personIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProfileImageRequirementsRow{}
	for rows.Next() {
		var i ListProfileImageRequirementsRow
		if err := rows.Scan(&i.PersonID, &i.Required); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const personRequiresProfileImage = `-- name: PersonRequiresProfileImage :one
SELECT COALESCE(bool_or(r.profile_image_required), false)::boolean
FROM accounts a
LEFT JOIN account_roles ar ON ar.account_id = a.id
LEFT JOIN roles r ON r.id = ar.role_id
WHERE a.person_id = $1
`

func (q *Queries) PersonRequiresProfileImage(ctx context.Context, personID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, personRequiresProfileImage, personID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const setProfileImage = `-- name: SetProfileImage :one
UPDATE people
SET profile_image_file_id = $1,
    profile_image_source = $2,
    version = version + 1,
    updated_at = now()
WHERE id = $3 AND version = $4
RETURNING id, first_name, last_name, email, phone, matriculation_number, photo_reference, version, created_at, updated_at, profile_image_file_id, profile_image_source
`

type SetProfileImageParams struct {
	ProfileImageFileID *uuid.UUID
	ProfileImageSource *string
	ID                 uuid.UUID
	ExpectedVersion    int64
}

func (q *Queries) SetProfileImage(ctx context.Context, arg SetProfileImageParams) (Person, error) {
	row := q.db.QueryRow(ctx, setProfileImage,
		arg.ProfileImageFileID,
		arg.ProfileImageSource,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.MatriculationNumber,
		&i.PhotoReference,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProfileImageFileID,
		&i.ProfileImageSource,
	)
	return i, err
}

const updatePerson = `-- name: UpdatePerson :one
UPDATE people
SET first_name = $1, last_name = $2,
    email = $3, phone = $4,
    matriculation_number = $5, photo_reference = $6,
    version = version + 1, updated_at = now()
WHERE id = $7 AND version = $8
RETURNING id, first_name, last_name, email, phone, matriculation_number, photo_reference, version, created_at, updated_at, profile_image_file_id, profile_image_source
`

type UpdatePersonParams struct {
	FirstName           string
	LastName            string
	Email               *string
	Phone               *string
	MatriculationNumber *string
	PhotoReference      *string
	ID                  uuid.UUID
	ExpectedVersion     int64
}

func (q *Queries) UpdatePerson(ctx context.Context, arg UpdatePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, updatePerson,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.MatriculationNumber,
		arg.PhotoReference,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.MatriculationNumber,
		&i.PhotoReference,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProfileImageFileID,
		&i.ProfileImageSource,
	)
	return i, err
}
