// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package manageddevicesdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateDeviceType(ctx context.Context, arg CreateDeviceTypeParams) (DeviceType, error)
	CreateManagedDevice(ctx context.Context, arg CreateManagedDeviceParams) (ManagedDevice, error)
	DeleteDeviceType(ctx context.Context, arg DeleteDeviceTypeParams) (uuid.UUID, error)
	DeleteManagedDevice(ctx context.Context, arg DeleteManagedDeviceParams) (uuid.UUID, error)
	GetDeviceType(ctx context.Context, id uuid.UUID) (DeviceType, error)
	GetDeviceTypeForMutation(ctx context.Context, id uuid.UUID) (DeviceType, error)
	GetManagedDevice(ctx context.Context, id uuid.UUID) (GetManagedDeviceRow, error)
	GetManagedDeviceForMutation(ctx context.Context, id uuid.UUID) (ManagedDevice, error)
	GetValidManagedDeviceByDigest(ctx context.Context, tokenDigest []byte) (GetValidManagedDeviceByDigestRow, error)
	ListDeviceTypes(ctx context.Context) ([]DeviceType, error)
	ListManagedDevices(ctx context.Context) ([]ListManagedDevicesRow, error)
	RevokeManagedDevice(ctx context.Context, arg RevokeManagedDeviceParams) (ManagedDevice, error)
	RotateManagedDeviceToken(ctx context.Context, arg RotateManagedDeviceTokenParams) (ManagedDevice, error)
	TouchManagedDevice(ctx context.Context, id uuid.UUID) error
	UpdateDeviceType(ctx context.Context, arg UpdateDeviceTypeParams) (DeviceType, error)
	UpdateManagedDevice(ctx context.Context, arg UpdateManagedDeviceParams) (ManagedDevice, error)
}

var _ Querier = (*Queries)(nil)
