// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package manageddevicesdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDeviceType = `-- name: CreateDeviceType :one
INSERT INTO device_types (id, name, description)
VALUES ($1, $2, $3) RETURNING id, name, description, version, created_at, updated_at
`

type CreateDeviceTypeParams struct {
	ID          uuid.UUID
	Name        string
	Description *string
}

func (q *Queries) CreateDeviceType(ctx context.Context, arg CreateDeviceTypeParams) (DeviceType, error) {
	row := q.db.QueryRow(ctx, createDeviceType, arg.ID, arg.Name, arg.Description)
	var i DeviceType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createManagedDevice = `-- name: CreateManagedDevice :one
INSERT INTO managed_devices (id, name, device_type_id, token_digest, expires_at)
VALUES ($1, $2, $3, $4, $5) RETURNING id, name, device_type_id, token_digest, expires_at, revoked_at, last_seen_at, version, created_at, updated_at
`

type CreateManagedDeviceParams struct {
	ID           uuid.UUID
	Name         string
	DeviceTypeID uuid.UUID
	TokenDigest  []byte
	ExpiresAt    pgtype.Timestamptz
}

func (q *Queries) CreateManagedDevice(ctx context.Context, arg CreateManagedDeviceParams) (ManagedDevice, error) {
	row := q.db.QueryRow(ctx, createManagedDevice,
		arg.ID,
		arg.Name,
		arg.DeviceTypeID,
		arg.TokenDigest,
		arg.ExpiresAt,
	)
	var i ManagedDevice
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeviceTypeID,
		&i.TokenDigest,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDeviceType = `-- name: DeleteDeviceType :one
DELETE FROM device_types WHERE id = $1 AND version = $2 RETURNING id
`

type DeleteDeviceTypeParams struct {
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) DeleteDeviceType(ctx context.Context, arg DeleteDeviceTypeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteDeviceType, arg.ID, arg.ExpectedVersion)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteManagedDevice = `-- name: DeleteManagedDevice :one
DELETE FROM managed_devices WHERE id = $1 AND version = $2
  AND revoked_at IS NOT NULL RETURNING id
`

type DeleteManagedDeviceParams struct {
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) DeleteManagedDevice(ctx context.Context, arg DeleteManagedDeviceParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteManagedDevice, arg.ID, arg.ExpectedVersion)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getDeviceType = `-- name: GetDeviceType :one
SELECT id, name, description, version, created_at, updated_at FROM device_types WHERE id = $1
`

func (q *Queries) GetDeviceType(ctx context.Context, id uuid.UUID) (DeviceType, error) {
	row := q.db.QueryRow(ctx, getDeviceType, id)
	var i DeviceType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceTypeForMutation = `-- name: GetDeviceTypeForMutation :one
SELECT id, name, description, version, created_at, updated_at FROM device_types WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetDeviceTypeForMutation(ctx context.Context, id uuid.UUID) (DeviceType, error) {
	row := q.db.QueryRow(ctx, getDeviceTypeForMutation, id)
	var i DeviceType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getManagedDevice = `-- name: GetManagedDevice :one
SELECT md.id, md.name, md.device_type_id, md.token_digest, md.expires_at, md.revoked_at, md.last_seen_at, md.version, md.created_at, md.updated_at, dt.name AS device_type_name
FROM managed_devices md JOIN device_types dt ON dt.id = md.device_type_id
WHERE md.id = $1
`

type GetManagedDeviceRow struct {
	ID             uuid.UUID
	Name           string
	DeviceTypeID   uuid.UUID
	TokenDigest    []byte
	ExpiresAt      pgtype.Timestamptz
	RevokedAt      pgtype.Timestamptz
	LastSeenAt     pgtype.Timestamptz
	Version        int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeviceTypeName string
}

func (q *Queries) GetManagedDevice(ctx context.Context, id uuid.UUID) (GetManagedDeviceRow, error) {
	row := q.db.QueryRow(ctx, getManagedDevice, id)
	var i GetManagedDeviceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeviceTypeID,
		&i.TokenDigest,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeviceTypeName,
	)
	return i, err
}

const getManagedDeviceForMutation = `-- name: GetManagedDeviceForMutation :one
SELECT id, name, device_type_id, token_digest, expires_at, revoked_at, last_seen_at, version, created_at, updated_at FROM managed_devices WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetManagedDeviceForMutation(ctx context.Context, id uuid.UUID) (ManagedDevice, error) {
	row := q.db.QueryRow(ctx, getManagedDeviceForMutation, id)
	var i ManagedDevice
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeviceTypeID,
		&i.TokenDigest,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getValidManagedDeviceByDigest = `-- name: GetValidManagedDeviceByDigest :one
SELECT md.id, md.name, md.device_type_id, dt.name AS device_type_name, md.expires_at
FROM managed_devices md JOIN device_types dt ON dt.id = md.device_type_id
WHERE md.token_digest = $1 AND md.revoked_at IS NULL
  AND (md.expires_at IS NULL OR md.expires_at > now())
`

type GetValidManagedDeviceByDigestRow struct {
	ID             uuid.UUID
	Name           string
	DeviceTypeID   uuid.UUID
	DeviceTypeName string
	ExpiresAt      pgtype.Timestamptz
}

func (q *Queries) GetValidManagedDeviceByDigest(ctx context.Context, tokenDigest []byte) (GetValidManagedDeviceByDigestRow, error) {
	row := q.db.QueryRow(ctx, getValidManagedDeviceByDigest, tokenDigest)
	var i GetValidManagedDeviceByDigestRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeviceTypeID,
		&i.DeviceTypeName,
		&i.ExpiresAt,
	)
	return i, err
}

const listDeviceTypes = `-- name: ListDeviceTypes :many
SELECT id, name, description, version, created_at, updated_at FROM device_types ORDER BY lower(name), id
`

func (q *Queries) ListDeviceTypes(ctx context.Context) ([]DeviceType, error) {
	rows, err := q.db.Query(ctx, listDeviceTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceType{}
	for rows.Next() {
		var i DeviceType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManagedDevices = `-- name: ListManagedDevices :many
SELECT md.id, md.name, md.device_type_id, md.token_digest, md.expires_at, md.revoked_at, md.last_seen_at, md.version, md.created_at, md.updated_at, dt.name AS device_type_name
FROM managed_devices md JOIN device_types dt ON dt.id = md.device_type_id
ORDER BY lower(md.name), md.id
`

type ListManagedDevicesRow struct {
	ID             uuid.UUID
	Name           string
	DeviceTypeID   uuid.UUID
	TokenDigest    []byte
	ExpiresAt      pgtype.Timestamptz
	RevokedAt      pgtype.Timestamptz
	LastSeenAt     pgtype.Timestamptz
	Version        int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeviceTypeName string
}

func (q *Queries) ListManagedDevices(ctx context.Context) ([]ListManagedDevicesRow, error) {
	rows, err := q.db.Query(ctx, listManagedDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListManagedDevicesRow{}
	for rows.Next() {
		var i ListManagedDevicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DeviceTypeID,
			&i.TokenDigest,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastSeenAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeviceTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeManagedDevice = `-- name: RevokeManagedDevice :one
UPDATE managed_devices SET revoked_at = now(), version = version + 1, updated_at = now()
WHERE id = $1 AND version = $2 AND revoked_at IS NULL RETURNING id, name, device_type_id, token_digest, expires_at, revoked_at, last_seen_at, version, created_at, updated_at
`

type RevokeManagedDeviceParams struct {
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) RevokeManagedDevice(ctx context.Context, arg RevokeManagedDeviceParams) (ManagedDevice, error) {
	row := q.db.QueryRow(ctx, revokeManagedDevice, arg.ID, arg.ExpectedVersion)
	var i ManagedDevice
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeviceTypeID,
		&i.TokenDigest,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rotateManagedDeviceToken = `-- name: RotateManagedDeviceToken :one
UPDATE managed_devices SET token_digest = $1, expires_at = $2,
  version = version + 1, updated_at = now()
WHERE id = $3 AND version = $4 AND revoked_at IS NULL RETURNING id, name, device_type_id, token_digest, expires_at, revoked_at, last_seen_at, version, created_at, updated_at
`

type RotateManagedDeviceTokenParams struct {
	TokenDigest     []byte
	ExpiresAt       pgtype.Timestamptz
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) RotateManagedDeviceToken(ctx context.Context, arg RotateManagedDeviceTokenParams) (ManagedDevice, error) {
	row := q.db.QueryRow(ctx, rotateManagedDeviceToken,
		arg.TokenDigest,
		arg.ExpiresAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i ManagedDevice
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeviceTypeID,
		&i.TokenDigest,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchManagedDevice = `-- name: TouchManagedDevice :exec
UPDATE managed_devices SET last_seen_at = now()
WHERE id = $1 AND revoked_at IS NULL
  AND (last_seen_at IS NULL OR last_seen_at < now() - interval '5 minutes')
`

func (q *Queries) TouchManagedDevice(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchManagedDevice, id)
	return err
}

const updateDeviceType = `-- name: UpdateDeviceType :one
UPDATE device_types SET name = $1, description = $2,
  version = version + 1, updated_at = now()
WHERE id = $3 AND version = $4 RETURNING id, name, description, version, created_at, updated_at
`

type UpdateDeviceTypeParams struct {
	Name            string
	Description     *string
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) UpdateDeviceType(ctx context.Context, arg UpdateDeviceTypeParams) (DeviceType, error) {
	row := q.db.QueryRow(ctx, updateDeviceType,
		arg.Name,
		arg.Description,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i DeviceType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateManagedDevice = `-- name: UpdateManagedDevice :one
UPDATE managed_devices SET name = $1, device_type_id = $2,
  expires_at = $3, version = version + 1, updated_at = now()
WHERE id = $4 AND version = $5 RETURNING id, name, device_type_id, token_digest, expires_at, revoked_at, last_seen_at, version, created_at, updated_at
`

type UpdateManagedDeviceParams struct {
	Name            string
	DeviceTypeID    uuid.UUID
	ExpiresAt       pgtype.Timestamptz
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) UpdateManagedDevice(ctx context.Context, arg UpdateManagedDeviceParams) (ManagedDevice, error) {
	row := q.db.QueryRow(ctx, updateManagedDevice,
		arg.Name,
		arg.DeviceTypeID,
		arg.ExpiresAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i ManagedDevice
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeviceTypeID,
		&i.TokenDigest,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
