// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package authdb

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                         uuid.UUID
	PersonID                   uuid.UUID
	Status                     string
	Version                    int64
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	ProvisioningSource         string
	FirstAuthenticatedAt       pgtype.Timestamptz
	AdministrativelyDisabledAt pgtype.Timestamptz
}

type AccountRole struct {
	AccountID           uuid.UUID
	RoleID              uuid.UUID
	AssignedByAccountID *uuid.UUID
	AssignedAt          time.Time
}

type AuditEvent struct {
	ID             uuid.UUID
	ActorAccountID *uuid.UUID
	Action         string
	ResourceType   string
	ResourceID     *uuid.UUID
	OccurredAt     time.Time
	RequestID      *uuid.UUID
	ChangedFields  []string
	Metadata       []byte
	Source         string
}

type AuthChallenge struct {
	ID                  uuid.UUID
	Kind                string
	AccountID           uuid.UUID
	AuthIdentityID      *uuid.UUID
	CodeDigest          []byte
	DeliveryAddress     string
	AttemptCount        int16
	CreatedByAccountID  *uuid.UUID
	ExpiresAt           time.Time
	UsedAt              pgtype.Timestamptz
	CancelledAt         pgtype.Timestamptz
	DeliveryStatus      string
	DeliveryAttemptedAt pgtype.Timestamptz
	DeliveryFailureCode *string
	CreatedAt           time.Time
}

type AuthIdentity struct {
	ID                   uuid.UUID
	AccountID            uuid.UUID
	Kind                 string
	IdentifierDisplay    *string
	IdentifierNormalized *string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	ProviderID           *uuid.UUID
	Issuer               *string
	Subject              *string
	VerifiedAt           pgtype.Timestamptz
	DisabledAt           pgtype.Timestamptz
	LastUsedAt           pgtype.Timestamptz
}

type AuthRateLimit struct {
	Action          string
	KeyDigest       []byte
	WindowStartedAt time.Time
	AttemptCount    int32
	BlockedUntil    pgtype.Timestamptz
	UpdatedAt       time.Time
}

type DeviceType struct {
	ID          uuid.UUID
	Name        string
	Description *string
	Version     int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type File struct {
	ID                 uuid.UUID
	StorageKey         string
	OriginalFilename   string
	ContentType        string
	SizeBytes          int64
	Sha256             []byte
	CreatedByAccountID *uuid.UUID
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type InventoryTransaction struct {
	ID                  uuid.UUID
	MaterialID          uuid.UUID
	Kind                string
	QuantityDelta       pgtype.Numeric
	UnitAcquisitionCost pgtype.Numeric
	InventoryValueDelta pgtype.Numeric
	TotalPurchasePrice  pgtype.Numeric
	OccurredAt          time.Time
	Supplier            *string
	Note                *string
	AdjustmentReason    *string
	MachineJobUsageID   *uuid.UUID
	ActorAccountID      *uuid.UUID
	CreatedAt           time.Time
}

type LaborordnungRequest struct {
	ID                        uuid.UUID
	PersonID                  uuid.UUID
	RequiredVersionID         uuid.UUID
	PreviousVersionID         *uuid.UUID
	Status                    string
	RequestedAt               time.Time
	CompletedAt               pgtype.Timestamptz
	SupersededAt              pgtype.Timestamptz
	ConfirmedByAccountID      *uuid.UUID
	PhysicalDocumentReference *string
	SignedDate                pgtype.Date
	ArchiveNote               *string
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
}

type LaborordnungVersion struct {
	ID                 uuid.UUID
	Status             string
	HumanRevision      string
	PdfFileID          uuid.UUID
	PdfSha256          []byte
	EffectiveAt        pgtype.Timestamptz
	PublishedAt        pgtype.Timestamptz
	CreatedByAccountID *uuid.UUID
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type Machine struct {
	ID                         uuid.UUID
	MachineTypeID              uuid.UUID
	Name                       string
	Status                     string
	ExternalIdentifier         *string
	AutomaticCollectionEnabled bool
	LastIngestedAt             pgtype.Timestamptz
	Version                    int64
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
}

type MachineJob struct {
	ID                         uuid.UUID
	DisplayID                  string
	MachineID                  uuid.UUID
	StartsAt                   time.Time
	EndsAt                     time.Time
	Source                     string
	ExternalID                 *string
	ExternalMetadata           []byte
	ReviewState                string
	CustomerPersonID           *uuid.UUID
	CustomerOrganizationID     *uuid.UUID
	OperatorPersonID           *uuid.UUID
	Outcome                    string
	Notes                      *string
	PricingStatus              string
	CalculatedPrice            pgtype.Numeric
	FinalPrice                 pgtype.Numeric
	PriceOverrideReason        *string
	PriceOverriddenByAccountID *uuid.UUID
	PriceOverriddenAt          pgtype.Timestamptz
	BillingStatus              string
	BillingReference           *string
	ActivePricingSnapshotID    *uuid.UUID
	Version                    int64
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
}

type MachineJobMaterialUsage struct {
	ID           uuid.UUID
	MachineJobID uuid.UUID
	MaterialID   uuid.UUID
	Quantity     pgtype.Numeric
	Active       bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type MachineJobPricingSnapshot struct {
	ID                  uuid.UUID
	MachineJobID        uuid.UUID
	Revision            int32
	PricingGroupID      *uuid.UUID
	PricingGroupName    string
	Currency            string
	Reason              string
	Complete            bool
	CalculatedAmount    pgtype.Numeric
	CapturedByAccountID *uuid.UUID
	CapturedAt          time.Time
}

type MachineJobPricingSnapshotRule struct {
	ID           uuid.UUID
	SnapshotID   uuid.UUID
	SourceRuleID *uuid.UUID
	Kind         string
	Label        string
	Selector     string
	Unit         string
	Rate         pgtype.Numeric
	Missing      bool
}

type MachineType struct {
	ID        uuid.UUID
	Name      string
	Active    bool
	Version   int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type MailConfiguration struct {
	Singleton             bool
	Enabled               bool
	Provider              string
	SmtpHost              string
	SmtpPort              int32
	SmtpTlsMode           string
	SmtpUsername          string
	EncryptedSmtpPassword []byte
	FromAddress           string
	FromName              string
	BaseUrl               string
	Version               int64
	UpdatedByAccountID    *uuid.UUID
	UpdatedAt             time.Time
}

type ManagedDevice struct {
	ID           uuid.UUID
	Name         string
	DeviceTypeID uuid.UUID
	TokenDigest  []byte
	ExpiresAt    pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
	LastSeenAt   pgtype.Timestamptz
	Version      int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Material struct {
	ID                uuid.UUID
	Name              string
	Category          string
	Color             *string
	Unit              string
	Active            bool
	LowStockThreshold pgtype.Numeric
	Version           int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type MaterialBalance struct {
	MaterialID      uuid.UUID
	Quantity        pgtype.Numeric
	InventoryValue  pgtype.Numeric
	AverageUnitCost pgtype.Numeric
	Version         int64
	UpdatedAt       time.Time
}

type OidcFlow struct {
	ID                    uuid.UUID
	ProviderID            uuid.UUID
	Kind                  string
	AccountID             *uuid.UUID
	StateDigest           []byte
	BrowserTokenDigest    []byte
	EncryptedNonce        []byte
	EncryptedPkceVerifier []byte
	ExpiresAt             time.Time
	UsedAt                pgtype.Timestamptz
	CreatedAt             time.Time
	SessionID             *uuid.UUID
}

type OidcProvider struct {
	ID                    uuid.UUID
	Slug                  string
	DisplayName           string
	Issuer                string
	ClientID              string
	EncryptedClientSecret []byte
	Enabled               bool
	JitEnabled            bool
	AcrAssuranceMappings  []byte
	Version               int64
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type OpenDay struct {
	ID           uuid.UUID
	PeriodID     uuid.UUID
	StartsAt     time.Time
	EndsAt       time.Time
	InternalNote *string
	Status       string
	Version      int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type OpenDayAcademicBreak struct {
	ID        uuid.UUID
	Name      string
	StartsOn  pgtype.Date
	EndsOn    pgtype.Date
	Version   int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type OpenDayAssignment struct {
	ID                 uuid.UUID
	OpenDayID          uuid.UUID
	RequirementID      uuid.UUID
	PersonID           uuid.UUID
	CreatedByAccountID *uuid.UUID
	CreatedAt          time.Time
}

type OpenDayPeriod struct {
	ID        uuid.UUID
	Name      string
	StartsOn  pgtype.Date
	EndsOn    pgtype.Date
	Status    string
	Version   int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type OpenDayStaffRequirement struct {
	ID            uuid.UUID
	OpenDayID     uuid.UUID
	Kind          string
	RequiredCount int32
}

type OpenDayStaffRequirementRole struct {
	RequirementID uuid.UUID
	RoleID        uuid.UUID
}

type Organization struct {
	ID        uuid.UUID
	Name      string
	Kind      string
	Active    bool
	Version   int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type OrganizationPricingGroupAssignment struct {
	OrganizationID      uuid.UUID
	PricingGroupID      uuid.UUID
	AssignedByAccountID *uuid.UUID
	Version             int64
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type PasswordCredential struct {
	AuthIdentityID uuid.UUID
	PasswordHash   string
	ResetRequired  bool
	ChangedAt      time.Time
}

type PasswordResetToken struct {
	ID                 uuid.UUID
	AccountID          uuid.UUID
	TokenDigest        []byte
	CreatedByAccountID *uuid.UUID
	CreatedAt          time.Time
	ExpiresAt          time.Time
}

type Person struct {
	ID                  uuid.UUID
	FirstName           string
	LastName            string
	Email               *string
	Phone               *string
	MatriculationNumber *string
	PhotoReference      *string
	Version             int64
	CreatedAt           time.Time
	UpdatedAt           time.Time
	ProfileImageFileID  *uuid.UUID
	ProfileImageSource  *string
}

type PersonPricingGroupAssignment struct {
	PersonID            uuid.UUID
	PricingGroupID      uuid.UUID
	AssignedByAccountID *uuid.UUID
	Version             int64
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type PinCredential struct {
	AuthIdentityID uuid.UUID
	PinHash        string
	ChangedAt      time.Time
}

type PinLoginThrottle struct {
	Dimension    string
	KeyDigest    []byte
	FailureCount int32
	BlockedUntil pgtype.Timestamptz
	UpdatedAt    time.Time
}

type PricingGroup struct {
	ID          uuid.UUID
	Name        string
	Description *string
	Active      bool
	IsDefault   bool
	Version     int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type PricingRule struct {
	ID               uuid.UUID
	PricingGroupID   uuid.UUID
	Kind             string
	MachineTypeID    *uuid.UUID
	MaterialCategory *string
	MaterialUnit     *string
	Rate             pgtype.Numeric
	Active           bool
	Version          int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Role struct {
	ID                   uuid.UUID
	Name                 string
	Description          *string
	SystemKey            *string
	Version              int64
	CreatedAt            time.Time
	UpdatedAt            time.Time
	ProfileImageRequired bool
	LaborordnungMode     string
	SupervisorDashboard  bool
}

type RolePermissionGrant struct {
	ID               uuid.UUID
	RoleID           uuid.UUID
	PermissionID     string
	Scope            string
	MinimumAssurance string
}

type RolePermissionGrantDeviceType struct {
	GrantID      uuid.UUID
	DeviceTypeID uuid.UUID
}

type ScimConnector struct {
	ID             uuid.UUID
	Name           string
	OidcProviderID *uuid.UUID
	Enabled        bool
	Version        int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type ScimConnectorToken struct {
	ID                 uuid.UUID
	ConnectorID        uuid.UUID
	TokenDigest        []byte
	ExpiresAt          time.Time
	RevokedAt          pgtype.Timestamptz
	LastUsedAt         pgtype.Timestamptz
	CreatedByAccountID *uuid.UUID
	CreatedAt          time.Time
}

type ScimUser struct {
	ID               uuid.UUID
	ConnectorID      uuid.UUID
	PersonID         uuid.UUID
	AccountID        uuid.UUID
	ExternalID       *string
	UserName         string
	ProvisioningData []byte
	Version          int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Session struct {
	ID                 uuid.UUID
	AccountID          uuid.UUID
	AuthIdentityID     uuid.UUID
	TokenDigest        []byte
	CsrfDigest         []byte
	AuthMethod         string
	CreatedAt          time.Time
	LastSeenAt         time.Time
	IdleExpiresAt      time.Time
	AbsoluteExpiresAt  time.Time
	RevokedAt          pgtype.Timestamptz
	RevocationReason   *string
	BaseAssurance      string
	CurrentAssurance   string
	AuthenticatedAt    time.Time
	AssuranceExpiresAt pgtype.Timestamptz
}

type VisitorEnrollmentConfiguration struct {
	Singleton          bool
	Enabled            bool
	InitialRoleID      *uuid.UUID
	AllowedMethods     []string
	Version            int64
	UpdatedByAccountID *uuid.UUID
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type VisitorEnrollmentContext struct {
	ID                uuid.UUID
	ManagedDeviceID   uuid.UUID
	TokenDigest       []byte
	CsrfDigest        []byte
	ExpiresAt         time.Time
	UsedAt            pgtype.Timestamptz
	CreatedAt         time.Time
	LabRulesVersionID *uuid.UUID
}

type VisitorEnrollmentDeviceType struct {
	DeviceTypeID uuid.UUID
}
