// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package authdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const bumpAccountVersionAfterCredentialChange = `-- name: BumpAccountVersionAfterCredentialChange :exec
UPDATE accounts
SET version = version + 1, updated_at = now()
WHERE id = $1
`

func (q *Queries) BumpAccountVersionAfterCredentialChange(ctx context.Context, accountID uuid.UUID) error {
	_, err := q.db.Exec(ctx, bumpAccountVersionAfterCredentialChange, accountID)
	return err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (id, account_id, token_digest, created_by_account_id, expires_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (account_id) DO UPDATE SET id = EXCLUDED.id, token_digest = EXCLUDED.token_digest,
    created_by_account_id = EXCLUDED.created_by_account_id, created_at = now(), expires_at = EXCLUDED.expires_at
RETURNING id, account_id, token_digest, created_by_account_id, created_at, expires_at
`

type CreatePasswordResetTokenParams struct {
	ID                 uuid.UUID
	AccountID          uuid.UUID
	TokenDigest        []byte
	CreatedByAccountID *uuid.UUID
	ExpiresAt          time.Time
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken,
		arg.ID,
		arg.AccountID,
		arg.TokenDigest,
		arg.CreatedByAccountID,
		arg.ExpiresAt,
	)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenDigest,
		&i.CreatedByAccountID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, account_id, auth_identity_id, token_digest, csrf_digest, auth_method, idle_expires_at, absolute_expires_at)
VALUES ($1, $2, $3, $4, $5, 'password', $6, $7)
RETURNING id, account_id, auth_identity_id, token_digest, csrf_digest, auth_method, created_at, last_seen_at, idle_expires_at, absolute_expires_at, revoked_at, revocation_reason
`

type CreateSessionParams struct {
	ID                uuid.UUID
	AccountID         uuid.UUID
	AuthIdentityID    uuid.UUID
	TokenDigest       []byte
	CsrfDigest        []byte
	IdleExpiresAt     time.Time
	AbsoluteExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.AccountID,
		arg.AuthIdentityID,
		arg.TokenDigest,
		arg.CsrfDigest,
		arg.IdleExpiresAt,
		arg.AbsoluteExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.AuthIdentityID,
		&i.TokenDigest,
		&i.CsrfDigest,
		&i.AuthMethod,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
		&i.RevocationReason,
	)
	return i, err
}

const deleteExpiredPasswordResetTokens = `-- name: DeleteExpiredPasswordResetTokens :execrows
DELETE FROM password_reset_tokens WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredPasswordResetTokens(ctx context.Context, beforeTime time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredPasswordResetTokens, beforeTime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE absolute_expires_at < $1
   OR idle_expires_at < $1
   OR (revoked_at IS NOT NULL AND revoked_at < $1)
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, beforeTime time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions, beforeTime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePasswordResetToken = `-- name: DeletePasswordResetToken :exec
DELETE FROM password_reset_tokens WHERE id = $1
`

func (q *Queries) DeletePasswordResetToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePasswordResetToken, id)
	return err
}

const findLoginAccountByEmail = `-- name: FindLoginAccountByEmail :one
SELECT account_id
FROM auth_identities
WHERE kind = 'email_password' AND identifier_normalized = $1
`

func (q *Queries) FindLoginAccountByEmail(ctx context.Context, identifierNormalized string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findLoginAccountByEmail, identifierNormalized)
	var account_id uuid.UUID
	err := row.Scan(&account_id)
	return account_id, err
}

const findPasswordResetAccountByDigest = `-- name: FindPasswordResetAccountByDigest :one
SELECT account_id
FROM password_reset_tokens
WHERE token_digest = $1 AND expires_at > now()
`

func (q *Queries) FindPasswordResetAccountByDigest(ctx context.Context, tokenDigest []byte) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findPasswordResetAccountByDigest, tokenDigest)
	var account_id uuid.UUID
	err := row.Scan(&account_id)
	return account_id, err
}

const getAccountForAuthentication = `-- name: GetAccountForAuthentication :one
SELECT id, status
FROM accounts
WHERE id = $1
FOR UPDATE
`

type GetAccountForAuthenticationRow struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) GetAccountForAuthentication(ctx context.Context, id uuid.UUID) (GetAccountForAuthenticationRow, error) {
	row := q.db.QueryRow(ctx, getAccountForAuthentication, id)
	var i GetAccountForAuthenticationRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const getLoginByEmail = `-- name: GetLoginByEmail :one
SELECT a.id AS account_id, a.person_id, a.status, a.version AS account_version,
       i.id AS auth_identity_id, i.identifier_display AS login_email,
       pc.password_hash, pc.reset_required, p.first_name, p.last_name
FROM auth_identities i JOIN accounts a ON a.id = i.account_id
JOIN people p ON p.id = a.person_id JOIN password_credentials pc ON pc.auth_identity_id = i.id
WHERE i.kind = 'email_password' AND i.identifier_normalized = $1
`

type GetLoginByEmailRow struct {
	AccountID      uuid.UUID
	PersonID       uuid.UUID
	Status         string
	AccountVersion int64
	AuthIdentityID uuid.UUID
	LoginEmail     string
	PasswordHash   string
	ResetRequired  bool
	FirstName      string
	LastName       string
}

func (q *Queries) GetLoginByEmail(ctx context.Context, identifierNormalized string) (GetLoginByEmailRow, error) {
	row := q.db.QueryRow(ctx, getLoginByEmail, identifierNormalized)
	var i GetLoginByEmailRow
	err := row.Scan(
		&i.AccountID,
		&i.PersonID,
		&i.Status,
		&i.AccountVersion,
		&i.AuthIdentityID,
		&i.LoginEmail,
		&i.PasswordHash,
		&i.ResetRequired,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const getPasswordCredentialForAccount = `-- name: GetPasswordCredentialForAccount :one
SELECT pc.auth_identity_id, pc.password_hash, pc.reset_required, pc.changed_at FROM password_credentials pc JOIN auth_identities i ON i.id = pc.auth_identity_id
WHERE i.account_id = $1 AND i.kind = 'email_password'
`

func (q *Queries) GetPasswordCredentialForAccount(ctx context.Context, accountID uuid.UUID) (PasswordCredential, error) {
	row := q.db.QueryRow(ctx, getPasswordCredentialForAccount, accountID)
	var i PasswordCredential
	err := row.Scan(
		&i.AuthIdentityID,
		&i.PasswordHash,
		&i.ResetRequired,
		&i.ChangedAt,
	)
	return i, err
}

const getPasswordResetByDigest = `-- name: GetPasswordResetByDigest :one
SELECT prt.id, prt.account_id, prt.token_digest, prt.created_by_account_id, prt.created_at, prt.expires_at, i.id AS auth_identity_id
FROM password_reset_tokens prt JOIN auth_identities i ON i.account_id = prt.account_id AND i.kind = 'email_password'
WHERE prt.token_digest = $1 AND prt.expires_at > now()
FOR UPDATE OF prt
`

type GetPasswordResetByDigestRow struct {
	ID                 uuid.UUID
	AccountID          uuid.UUID
	TokenDigest        []byte
	CreatedByAccountID *uuid.UUID
	CreatedAt          time.Time
	ExpiresAt          time.Time
	AuthIdentityID     uuid.UUID
}

func (q *Queries) GetPasswordResetByDigest(ctx context.Context, tokenDigest []byte) (GetPasswordResetByDigestRow, error) {
	row := q.db.QueryRow(ctx, getPasswordResetByDigest, tokenDigest)
	var i GetPasswordResetByDigestRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenDigest,
		&i.CreatedByAccountID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AuthIdentityID,
	)
	return i, err
}

const getSessionPrincipal = `-- name: GetSessionPrincipal :one
SELECT s.id AS session_id, s.account_id, s.auth_identity_id, s.csrf_digest,
       s.idle_expires_at, s.absolute_expires_at, s.last_seen_at,
       a.person_id, p.first_name, p.last_name, i.identifier_display AS login_email
FROM sessions s JOIN accounts a ON a.id = s.account_id JOIN people p ON p.id = a.person_id
JOIN auth_identities i ON i.id = s.auth_identity_id
WHERE s.token_digest = $1 AND s.revoked_at IS NULL
  AND s.idle_expires_at > now() AND s.absolute_expires_at > now() AND a.status = 'enabled'
`

type GetSessionPrincipalRow struct {
	SessionID         uuid.UUID
	AccountID         uuid.UUID
	AuthIdentityID    uuid.UUID
	CsrfDigest        []byte
	IdleExpiresAt     time.Time
	AbsoluteExpiresAt time.Time
	LastSeenAt        time.Time
	PersonID          uuid.UUID
	FirstName         string
	LastName          string
	LoginEmail        string
}

func (q *Queries) GetSessionPrincipal(ctx context.Context, tokenDigest []byte) (GetSessionPrincipalRow, error) {
	row := q.db.QueryRow(ctx, getSessionPrincipal, tokenDigest)
	var i GetSessionPrincipalRow
	err := row.Scan(
		&i.SessionID,
		&i.AccountID,
		&i.AuthIdentityID,
		&i.CsrfDigest,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.LastSeenAt,
		&i.PersonID,
		&i.FirstName,
		&i.LastName,
		&i.LoginEmail,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = COALESCE(revoked_at, now()), revocation_reason = COALESCE(revocation_reason, $1)
WHERE id = $2
`

type RevokeSessionParams struct {
	Reason *string
	ID     uuid.UUID
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.Reason, arg.ID)
	return err
}

const revokeSessionsForAccount = `-- name: RevokeSessionsForAccount :exec
UPDATE sessions SET revoked_at = COALESCE(revoked_at, now()), revocation_reason = COALESCE(revocation_reason, $1)
WHERE account_id = $2 AND revoked_at IS NULL
`

type RevokeSessionsForAccountParams struct {
	Reason    *string
	AccountID uuid.UUID
}

func (q *Queries) RevokeSessionsForAccount(ctx context.Context, arg RevokeSessionsForAccountParams) error {
	_, err := q.db.Exec(ctx, revokeSessionsForAccount, arg.Reason, arg.AccountID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = now(), idle_expires_at = LEAST($1, absolute_expires_at)
WHERE id = $2 AND last_seen_at < now() - interval '5 minutes' AND revoked_at IS NULL
`

type TouchSessionParams struct {
	IdleExpiresAt time.Time
	ID            uuid.UUID
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.IdleExpiresAt, arg.ID)
	return err
}

const upsertPasswordCredential = `-- name: UpsertPasswordCredential :exec
INSERT INTO password_credentials (auth_identity_id, password_hash, reset_required, changed_at)
VALUES ($1, $2, false, now())
ON CONFLICT (auth_identity_id) DO UPDATE SET password_hash = EXCLUDED.password_hash, reset_required = false, changed_at = now()
`

type UpsertPasswordCredentialParams struct {
	AuthIdentityID uuid.UUID
	PasswordHash   string
}

func (q *Queries) UpsertPasswordCredential(ctx context.Context, arg UpsertPasswordCredentialParams) error {
	_, err := q.db.Exec(ctx, upsertPasswordCredential, arg.AuthIdentityID, arg.PasswordHash)
	return err
}
