// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package authorizationdb

import (
	"context"

	"github.com/google/uuid"
)

const getPrincipalRolePermissions = `-- name: GetPrincipalRolePermissions :many
SELECT r.id AS role_id, r.system_key, g.id AS grant_id, g.permission_id, g.scope,
       g.minimum_assurance, gdt.device_type_id
FROM account_roles ar JOIN roles r ON r.id = ar.role_id
LEFT JOIN role_permission_grants g ON g.role_id = r.id
LEFT JOIN role_permission_grant_device_types gdt ON gdt.grant_id = g.id
WHERE ar.account_id = $1 ORDER BY r.id, g.permission_id, g.id, gdt.device_type_id
`

type GetPrincipalRolePermissionsRow struct {
	RoleID           uuid.UUID
	SystemKey        *string
	GrantID          *uuid.UUID
	PermissionID     *string
	Scope            *string
	MinimumAssurance *string
	DeviceTypeID     *uuid.UUID
}

func (q *Queries) GetPrincipalRolePermissions(ctx context.Context, accountID uuid.UUID) ([]GetPrincipalRolePermissionsRow, error) {
	rows, err := q.db.Query(ctx, getPrincipalRolePermissions, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPrincipalRolePermissionsRow{}
	for rows.Next() {
		var i GetPrincipalRolePermissionsRow
		if err := rows.Scan(
			&i.RoleID,
			&i.SystemKey,
			&i.GrantID,
			&i.PermissionID,
			&i.Scope,
			&i.MinimumAssurance,
			&i.DeviceTypeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
