// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package opendaysdb

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        uuid.UUID
	PersonID  uuid.UUID
	Status    string
	Version   int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type AccountRole struct {
	AccountID           uuid.UUID
	RoleID              uuid.UUID
	AssignedByAccountID *uuid.UUID
	AssignedAt          time.Time
}

type AuditEvent struct {
	ID             uuid.UUID
	ActorAccountID *uuid.UUID
	Action         string
	ResourceType   string
	ResourceID     *uuid.UUID
	OccurredAt     time.Time
	RequestID      *uuid.UUID
	ChangedFields  []string
	Metadata       []byte
	Source         string
}

type AuthIdentity struct {
	ID                   uuid.UUID
	AccountID            uuid.UUID
	Kind                 string
	IdentifierDisplay    string
	IdentifierNormalized string
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type OpenDay struct {
	ID           uuid.UUID
	PeriodID     uuid.UUID
	StartsAt     time.Time
	EndsAt       time.Time
	InternalNote *string
	Status       string
	Version      int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type OpenDayAcademicBreak struct {
	ID        uuid.UUID
	Name      string
	StartsOn  pgtype.Date
	EndsOn    pgtype.Date
	Version   int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type OpenDayAssignment struct {
	ID                 uuid.UUID
	OpenDayID          uuid.UUID
	RequirementID      uuid.UUID
	PersonID           uuid.UUID
	CreatedByAccountID *uuid.UUID
	CreatedAt          time.Time
}

type OpenDayPeriod struct {
	ID        uuid.UUID
	Name      string
	StartsOn  pgtype.Date
	EndsOn    pgtype.Date
	Status    string
	Version   int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type OpenDayStaffRequirement struct {
	ID            uuid.UUID
	OpenDayID     uuid.UUID
	Kind          string
	RequiredCount int32
}

type OpenDayStaffRequirementRole struct {
	RequirementID uuid.UUID
	RoleID        uuid.UUID
}

type PasswordCredential struct {
	AuthIdentityID uuid.UUID
	PasswordHash   string
	ResetRequired  bool
	ChangedAt      time.Time
}

type PasswordResetToken struct {
	ID                 uuid.UUID
	AccountID          uuid.UUID
	TokenDigest        []byte
	CreatedByAccountID *uuid.UUID
	CreatedAt          time.Time
	ExpiresAt          time.Time
}

type Person struct {
	ID                  uuid.UUID
	FirstName           string
	LastName            string
	Email               *string
	Phone               *string
	MatriculationNumber *string
	PhotoReference      *string
	Version             int64
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type Role struct {
	ID          uuid.UUID
	Name        string
	Description *string
	SystemKey   *string
	Version     int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type RolePermission struct {
	RoleID       uuid.UUID
	PermissionID string
}

type Session struct {
	ID                uuid.UUID
	AccountID         uuid.UUID
	AuthIdentityID    uuid.UUID
	TokenDigest       []byte
	CsrfDigest        []byte
	AuthMethod        string
	CreatedAt         time.Time
	LastSeenAt        time.Time
	IdleExpiresAt     time.Time
	AbsoluteExpiresAt time.Time
	RevokedAt         pgtype.Timestamptz
	RevocationReason  *string
}
