// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package opendaysdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddRequirementRole(ctx context.Context, arg AddRequirementRoleParams) error
	BumpPeriodVersion(ctx context.Context, arg BumpPeriodVersionParams) (OpenDayPeriod, error)
	CancelOpenDay(ctx context.Context, arg CancelOpenDayParams) (OpenDay, error)
	CountRequirementAssignments(ctx context.Context, requirementID uuid.UUID) (int64, error)
	CreateAcademicBreak(ctx context.Context, arg CreateAcademicBreakParams) (OpenDayAcademicBreak, error)
	CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (OpenDayAssignment, error)
	CreateOpenDay(ctx context.Context, arg CreateOpenDayParams) (OpenDay, error)
	CreatePeriod(ctx context.Context, arg CreatePeriodParams) (OpenDayPeriod, error)
	CreateRequirement(ctx context.Context, arg CreateRequirementParams) (OpenDayStaffRequirement, error)
	DeleteAcademicBreak(ctx context.Context, arg DeleteAcademicBreakParams) (uuid.UUID, error)
	DeleteAssignment(ctx context.Context, id uuid.UUID) (OpenDayAssignment, error)
	DeleteOpenDay(ctx context.Context, arg DeleteOpenDayParams) (uuid.UUID, error)
	DeleteRequirementRoles(ctx context.Context, requirementID uuid.UUID) error
	GetAcademicBreakForUpdate(ctx context.Context, id uuid.UUID) (OpenDayAcademicBreak, error)
	GetAssignment(ctx context.Context, id uuid.UUID) (OpenDayAssignment, error)
	GetAssignmentPersonName(ctx context.Context, id uuid.UUID) (GetAssignmentPersonNameRow, error)
	GetOpenDay(ctx context.Context, id uuid.UUID) (OpenDay, error)
	GetOpenDayForUpdate(ctx context.Context, id uuid.UUID) (OpenDay, error)
	GetPeriod(ctx context.Context, id uuid.UUID) (OpenDayPeriod, error)
	GetPeriodForUpdate(ctx context.Context, id uuid.UUID) (OpenDayPeriod, error)
	GetPersonOpenDayAssignment(ctx context.Context, arg GetPersonOpenDayAssignmentParams) (OpenDayAssignment, error)
	GetRequirement(ctx context.Context, id uuid.UUID) (OpenDayStaffRequirement, error)
	GetRequirementForUpdate(ctx context.Context, id uuid.UUID) (OpenDayStaffRequirement, error)
	ListAcademicBreaksInRange(ctx context.Context, arg ListAcademicBreaksInRangeParams) ([]OpenDayAcademicBreak, error)
	ListAssignments(ctx context.Context, openDayID uuid.UUID) ([]ListAssignmentsRow, error)
	ListEligibilityRoles(ctx context.Context) ([]ListEligibilityRolesRow, error)
	ListEligiblePeople(ctx context.Context, arg ListEligiblePeopleParams) ([]ListEligiblePeopleRow, error)
	ListOpenDaysByPeriod(ctx context.Context, periodID uuid.UUID) ([]OpenDay, error)
	ListPeriods(ctx context.Context) ([]OpenDayPeriod, error)
	ListPublishedOpenDays(ctx context.Context) ([]OpenDay, error)
	ListRequirementRoleIDs(ctx context.Context, requirementID uuid.UUID) ([]uuid.UUID, error)
	ListRequirements(ctx context.Context, openDayID uuid.UUID) ([]OpenDayStaffRequirement, error)
	PersonEligibleForRequirement(ctx context.Context, arg PersonEligibleForRequirementParams) (bool, error)
	TransitionPeriod(ctx context.Context, arg TransitionPeriodParams) (OpenDayPeriod, error)
	UpdateAcademicBreak(ctx context.Context, arg UpdateAcademicBreakParams) (OpenDayAcademicBreak, error)
	UpdateOpenDay(ctx context.Context, arg UpdateOpenDayParams) (OpenDay, error)
	UpdatePeriod(ctx context.Context, arg UpdatePeriodParams) (OpenDayPeriod, error)
	UpdateRequirement(ctx context.Context, arg UpdateRequirementParams) (OpenDayStaffRequirement, error)
}

var _ Querier = (*Queries)(nil)
