// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package opendaysdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addRequirementRole = `-- name: AddRequirementRole :exec
INSERT INTO open_day_staff_requirement_roles (requirement_id, role_id)
VALUES ($1, $2)
`

type AddRequirementRoleParams struct {
	RequirementID uuid.UUID
	RoleID        uuid.UUID
}

func (q *Queries) AddRequirementRole(ctx context.Context, arg AddRequirementRoleParams) error {
	_, err := q.db.Exec(ctx, addRequirementRole, arg.RequirementID, arg.RoleID)
	return err
}

const bumpPeriodVersion = `-- name: BumpPeriodVersion :one
UPDATE open_day_periods SET version = version + 1, updated_at = now()
WHERE id = $1 AND version = $2 RETURNING id, name, starts_on, ends_on, status, version, created_at, updated_at
`

type BumpPeriodVersionParams struct {
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) BumpPeriodVersion(ctx context.Context, arg BumpPeriodVersionParams) (OpenDayPeriod, error) {
	row := q.db.QueryRow(ctx, bumpPeriodVersion, arg.ID, arg.ExpectedVersion)
	var i OpenDayPeriod
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartsOn,
		&i.EndsOn,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelOpenDay = `-- name: CancelOpenDay :one
UPDATE open_days SET status = 'cancelled', version = version + 1, updated_at = now()
WHERE id = $1 AND version = $2 AND status = 'scheduled'
RETURNING id, period_id, starts_at, ends_at, internal_note, status, version, created_at, updated_at
`

type CancelOpenDayParams struct {
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) CancelOpenDay(ctx context.Context, arg CancelOpenDayParams) (OpenDay, error) {
	row := q.db.QueryRow(ctx, cancelOpenDay, arg.ID, arg.ExpectedVersion)
	var i OpenDay
	err := row.Scan(
		&i.ID,
		&i.PeriodID,
		&i.StartsAt,
		&i.EndsAt,
		&i.InternalNote,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countRequirementAssignments = `-- name: CountRequirementAssignments :one
SELECT count(*) FROM open_day_assignments WHERE requirement_id = $1
`

func (q *Queries) CountRequirementAssignments(ctx context.Context, requirementID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRequirementAssignments, requirementID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAcademicBreak = `-- name: CreateAcademicBreak :one
INSERT INTO open_day_academic_breaks (id, name, starts_on, ends_on)
VALUES ($1, $2, $3, $4) RETURNING id, name, starts_on, ends_on, version, created_at, updated_at
`

type CreateAcademicBreakParams struct {
	ID       uuid.UUID
	Name     string
	StartsOn pgtype.Date
	EndsOn   pgtype.Date
}

func (q *Queries) CreateAcademicBreak(ctx context.Context, arg CreateAcademicBreakParams) (OpenDayAcademicBreak, error) {
	row := q.db.QueryRow(ctx, createAcademicBreak,
		arg.ID,
		arg.Name,
		arg.StartsOn,
		arg.EndsOn,
	)
	var i OpenDayAcademicBreak
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartsOn,
		&i.EndsOn,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAssignment = `-- name: CreateAssignment :one
INSERT INTO open_day_assignments (id, open_day_id, requirement_id, person_id, created_by_account_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, open_day_id, requirement_id, person_id, created_by_account_id, created_at
`

type CreateAssignmentParams struct {
	ID                 uuid.UUID
	OpenDayID          uuid.UUID
	RequirementID      uuid.UUID
	PersonID           uuid.UUID
	CreatedByAccountID *uuid.UUID
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (OpenDayAssignment, error) {
	row := q.db.QueryRow(ctx, createAssignment,
		arg.ID,
		arg.OpenDayID,
		arg.RequirementID,
		arg.PersonID,
		arg.CreatedByAccountID,
	)
	var i OpenDayAssignment
	err := row.Scan(
		&i.ID,
		&i.OpenDayID,
		&i.RequirementID,
		&i.PersonID,
		&i.CreatedByAccountID,
		&i.CreatedAt,
	)
	return i, err
}

const createOpenDay = `-- name: CreateOpenDay :one
INSERT INTO open_days (id, period_id, starts_at, ends_at, internal_note)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, period_id, starts_at, ends_at, internal_note, status, version, created_at, updated_at
`

type CreateOpenDayParams struct {
	ID           uuid.UUID
	PeriodID     uuid.UUID
	StartsAt     time.Time
	EndsAt       time.Time
	InternalNote *string
}

func (q *Queries) CreateOpenDay(ctx context.Context, arg CreateOpenDayParams) (OpenDay, error) {
	row := q.db.QueryRow(ctx, createOpenDay,
		arg.ID,
		arg.PeriodID,
		arg.StartsAt,
		arg.EndsAt,
		arg.InternalNote,
	)
	var i OpenDay
	err := row.Scan(
		&i.ID,
		&i.PeriodID,
		&i.StartsAt,
		&i.EndsAt,
		&i.InternalNote,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPeriod = `-- name: CreatePeriod :one
INSERT INTO open_day_periods (id, name, starts_on, ends_on)
VALUES ($1, $2, $3, $4) RETURNING id, name, starts_on, ends_on, status, version, created_at, updated_at
`

type CreatePeriodParams struct {
	ID       uuid.UUID
	Name     string
	StartsOn pgtype.Date
	EndsOn   pgtype.Date
}

func (q *Queries) CreatePeriod(ctx context.Context, arg CreatePeriodParams) (OpenDayPeriod, error) {
	row := q.db.QueryRow(ctx, createPeriod,
		arg.ID,
		arg.Name,
		arg.StartsOn,
		arg.EndsOn,
	)
	var i OpenDayPeriod
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartsOn,
		&i.EndsOn,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRequirement = `-- name: CreateRequirement :one
INSERT INTO open_day_staff_requirements (id, open_day_id, kind, required_count)
VALUES ($1, $2, $3, $4) RETURNING id, open_day_id, kind, required_count
`

type CreateRequirementParams struct {
	ID            uuid.UUID
	OpenDayID     uuid.UUID
	Kind          string
	RequiredCount int32
}

func (q *Queries) CreateRequirement(ctx context.Context, arg CreateRequirementParams) (OpenDayStaffRequirement, error) {
	row := q.db.QueryRow(ctx, createRequirement,
		arg.ID,
		arg.OpenDayID,
		arg.Kind,
		arg.RequiredCount,
	)
	var i OpenDayStaffRequirement
	err := row.Scan(
		&i.ID,
		&i.OpenDayID,
		&i.Kind,
		&i.RequiredCount,
	)
	return i, err
}

const deleteAcademicBreak = `-- name: DeleteAcademicBreak :one
DELETE FROM open_day_academic_breaks WHERE id = $1 AND version = $2 RETURNING id
`

type DeleteAcademicBreakParams struct {
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) DeleteAcademicBreak(ctx context.Context, arg DeleteAcademicBreakParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteAcademicBreak, arg.ID, arg.ExpectedVersion)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteAssignment = `-- name: DeleteAssignment :one
DELETE FROM open_day_assignments WHERE id = $1 RETURNING id, open_day_id, requirement_id, person_id, created_by_account_id, created_at
`

func (q *Queries) DeleteAssignment(ctx context.Context, id uuid.UUID) (OpenDayAssignment, error) {
	row := q.db.QueryRow(ctx, deleteAssignment, id)
	var i OpenDayAssignment
	err := row.Scan(
		&i.ID,
		&i.OpenDayID,
		&i.RequirementID,
		&i.PersonID,
		&i.CreatedByAccountID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOpenDay = `-- name: DeleteOpenDay :one
DELETE FROM open_days WHERE id = $1 AND version = $2 RETURNING id
`

type DeleteOpenDayParams struct {
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) DeleteOpenDay(ctx context.Context, arg DeleteOpenDayParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteOpenDay, arg.ID, arg.ExpectedVersion)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteRequirementRoles = `-- name: DeleteRequirementRoles :exec
DELETE FROM open_day_staff_requirement_roles WHERE requirement_id = $1
`

func (q *Queries) DeleteRequirementRoles(ctx context.Context, requirementID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRequirementRoles, requirementID)
	return err
}

const getAcademicBreakForUpdate = `-- name: GetAcademicBreakForUpdate :one
SELECT id, name, starts_on, ends_on, version, created_at, updated_at FROM open_day_academic_breaks WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetAcademicBreakForUpdate(ctx context.Context, id uuid.UUID) (OpenDayAcademicBreak, error) {
	row := q.db.QueryRow(ctx, getAcademicBreakForUpdate, id)
	var i OpenDayAcademicBreak
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartsOn,
		&i.EndsOn,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssignment = `-- name: GetAssignment :one
SELECT id, open_day_id, requirement_id, person_id, created_by_account_id, created_at FROM open_day_assignments WHERE id = $1
`

func (q *Queries) GetAssignment(ctx context.Context, id uuid.UUID) (OpenDayAssignment, error) {
	row := q.db.QueryRow(ctx, getAssignment, id)
	var i OpenDayAssignment
	err := row.Scan(
		&i.ID,
		&i.OpenDayID,
		&i.RequirementID,
		&i.PersonID,
		&i.CreatedByAccountID,
		&i.CreatedAt,
	)
	return i, err
}

const getAssignmentPersonName = `-- name: GetAssignmentPersonName :one
SELECT first_name, last_name FROM people WHERE id = $1
`

type GetAssignmentPersonNameRow struct {
	FirstName string
	LastName  string
}

func (q *Queries) GetAssignmentPersonName(ctx context.Context, id uuid.UUID) (GetAssignmentPersonNameRow, error) {
	row := q.db.QueryRow(ctx, getAssignmentPersonName, id)
	var i GetAssignmentPersonNameRow
	err := row.Scan(&i.FirstName, &i.LastName)
	return i, err
}

const getOpenDay = `-- name: GetOpenDay :one
SELECT id, period_id, starts_at, ends_at, internal_note, status, version, created_at, updated_at FROM open_days WHERE id = $1
`

func (q *Queries) GetOpenDay(ctx context.Context, id uuid.UUID) (OpenDay, error) {
	row := q.db.QueryRow(ctx, getOpenDay, id)
	var i OpenDay
	err := row.Scan(
		&i.ID,
		&i.PeriodID,
		&i.StartsAt,
		&i.EndsAt,
		&i.InternalNote,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOpenDayForUpdate = `-- name: GetOpenDayForUpdate :one
SELECT id, period_id, starts_at, ends_at, internal_note, status, version, created_at, updated_at FROM open_days WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetOpenDayForUpdate(ctx context.Context, id uuid.UUID) (OpenDay, error) {
	row := q.db.QueryRow(ctx, getOpenDayForUpdate, id)
	var i OpenDay
	err := row.Scan(
		&i.ID,
		&i.PeriodID,
		&i.StartsAt,
		&i.EndsAt,
		&i.InternalNote,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPeriod = `-- name: GetPeriod :one
SELECT id, name, starts_on, ends_on, status, version, created_at, updated_at FROM open_day_periods WHERE id = $1
`

func (q *Queries) GetPeriod(ctx context.Context, id uuid.UUID) (OpenDayPeriod, error) {
	row := q.db.QueryRow(ctx, getPeriod, id)
	var i OpenDayPeriod
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartsOn,
		&i.EndsOn,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPeriodForUpdate = `-- name: GetPeriodForUpdate :one
SELECT id, name, starts_on, ends_on, status, version, created_at, updated_at FROM open_day_periods WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetPeriodForUpdate(ctx context.Context, id uuid.UUID) (OpenDayPeriod, error) {
	row := q.db.QueryRow(ctx, getPeriodForUpdate, id)
	var i OpenDayPeriod
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartsOn,
		&i.EndsOn,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPersonOpenDayAssignment = `-- name: GetPersonOpenDayAssignment :one
SELECT id, open_day_id, requirement_id, person_id, created_by_account_id, created_at FROM open_day_assignments
WHERE open_day_id = $1 AND person_id = $2
`

type GetPersonOpenDayAssignmentParams struct {
	OpenDayID uuid.UUID
	PersonID  uuid.UUID
}

func (q *Queries) GetPersonOpenDayAssignment(ctx context.Context, arg GetPersonOpenDayAssignmentParams) (OpenDayAssignment, error) {
	row := q.db.QueryRow(ctx, getPersonOpenDayAssignment, arg.OpenDayID, arg.PersonID)
	var i OpenDayAssignment
	err := row.Scan(
		&i.ID,
		&i.OpenDayID,
		&i.RequirementID,
		&i.PersonID,
		&i.CreatedByAccountID,
		&i.CreatedAt,
	)
	return i, err
}

const getRequirement = `-- name: GetRequirement :one
SELECT id, open_day_id, kind, required_count FROM open_day_staff_requirements WHERE id = $1
`

func (q *Queries) GetRequirement(ctx context.Context, id uuid.UUID) (OpenDayStaffRequirement, error) {
	row := q.db.QueryRow(ctx, getRequirement, id)
	var i OpenDayStaffRequirement
	err := row.Scan(
		&i.ID,
		&i.OpenDayID,
		&i.Kind,
		&i.RequiredCount,
	)
	return i, err
}

const getRequirementForUpdate = `-- name: GetRequirementForUpdate :one
SELECT id, open_day_id, kind, required_count FROM open_day_staff_requirements WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetRequirementForUpdate(ctx context.Context, id uuid.UUID) (OpenDayStaffRequirement, error) {
	row := q.db.QueryRow(ctx, getRequirementForUpdate, id)
	var i OpenDayStaffRequirement
	err := row.Scan(
		&i.ID,
		&i.OpenDayID,
		&i.Kind,
		&i.RequiredCount,
	)
	return i, err
}

const listAcademicBreaksInRange = `-- name: ListAcademicBreaksInRange :many
SELECT id, name, starts_on, ends_on, version, created_at, updated_at FROM open_day_academic_breaks
WHERE starts_on <= $1 AND ends_on >= $2
ORDER BY starts_on, ends_on, id
`

type ListAcademicBreaksInRangeParams struct {
	EndsOn   pgtype.Date
	StartsOn pgtype.Date
}

func (q *Queries) ListAcademicBreaksInRange(ctx context.Context, arg ListAcademicBreaksInRangeParams) ([]OpenDayAcademicBreak, error) {
	rows, err := q.db.Query(ctx, listAcademicBreaksInRange, arg.EndsOn, arg.StartsOn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OpenDayAcademicBreak{}
	for rows.Next() {
		var i OpenDayAcademicBreak
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartsOn,
			&i.EndsOn,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssignments = `-- name: ListAssignments :many
SELECT a.id, a.open_day_id, a.requirement_id, a.person_id, a.created_by_account_id, a.created_at,
       p.first_name, p.last_name
FROM open_day_assignments a JOIN people p ON p.id = a.person_id
WHERE a.open_day_id = $1
ORDER BY a.created_at, a.id
`

type ListAssignmentsRow struct {
	ID                 uuid.UUID
	OpenDayID          uuid.UUID
	RequirementID      uuid.UUID
	PersonID           uuid.UUID
	CreatedByAccountID *uuid.UUID
	CreatedAt          time.Time
	FirstName          string
	LastName           string
}

func (q *Queries) ListAssignments(ctx context.Context, openDayID uuid.UUID) ([]ListAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listAssignments, openDayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssignmentsRow{}
	for rows.Next() {
		var i ListAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.OpenDayID,
			&i.RequirementID,
			&i.PersonID,
			&i.CreatedByAccountID,
			&i.CreatedAt,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEligibilityRoles = `-- name: ListEligibilityRoles :many
SELECT id, name FROM roles ORDER BY system_key DESC NULLS LAST, lower(name), id
`

type ListEligibilityRolesRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) ListEligibilityRoles(ctx context.Context) ([]ListEligibilityRolesRow, error) {
	rows, err := q.db.Query(ctx, listEligibilityRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEligibilityRolesRow{}
	for rows.Next() {
		var i ListEligibilityRolesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEligiblePeople = `-- name: ListEligiblePeople :many
SELECT DISTINCT p.id, p.first_name, p.last_name
FROM people p
JOIN accounts a ON a.person_id = p.id AND a.status = 'enabled'
JOIN account_roles ar ON ar.account_id = a.id
JOIN open_day_staff_requirement_roles rr ON rr.role_id = ar.role_id
WHERE rr.requirement_id = $1
  AND ($2::text = '' OR lower(p.first_name || ' ' || p.last_name) LIKE '%' || lower($2::text) || '%')
ORDER BY p.last_name, p.first_name, p.id
LIMIT $3
`

type ListEligiblePeopleParams struct {
	RequirementID uuid.UUID
	Search        string
	PageLimit     int32
}

type ListEligiblePeopleRow struct {
	ID        uuid.UUID
	FirstName string
	LastName  string
}

func (q *Queries) ListEligiblePeople(ctx context.Context, arg ListEligiblePeopleParams) ([]ListEligiblePeopleRow, error) {
	rows, err := q.db.Query(ctx, listEligiblePeople, arg.RequirementID, arg.Search, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEligiblePeopleRow{}
	for rows.Next() {
		var i ListEligiblePeopleRow
		if err := rows.Scan(&i.ID, &i.FirstName, &i.LastName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenDaysByPeriod = `-- name: ListOpenDaysByPeriod :many
SELECT id, period_id, starts_at, ends_at, internal_note, status, version, created_at, updated_at FROM open_days WHERE period_id = $1 ORDER BY starts_at, id
`

func (q *Queries) ListOpenDaysByPeriod(ctx context.Context, periodID uuid.UUID) ([]OpenDay, error) {
	rows, err := q.db.Query(ctx, listOpenDaysByPeriod, periodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OpenDay{}
	for rows.Next() {
		var i OpenDay
		if err := rows.Scan(
			&i.ID,
			&i.PeriodID,
			&i.StartsAt,
			&i.EndsAt,
			&i.InternalNote,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeriods = `-- name: ListPeriods :many
SELECT id, name, starts_on, ends_on, status, version, created_at, updated_at FROM open_day_periods ORDER BY starts_on DESC, id DESC
`

func (q *Queries) ListPeriods(ctx context.Context) ([]OpenDayPeriod, error) {
	rows, err := q.db.Query(ctx, listPeriods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OpenDayPeriod{}
	for rows.Next() {
		var i OpenDayPeriod
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartsOn,
			&i.EndsOn,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedOpenDays = `-- name: ListPublishedOpenDays :many
SELECT od.id, od.period_id, od.starts_at, od.ends_at, od.internal_note, od.status, od.version, od.created_at, od.updated_at FROM open_days od
JOIN open_day_periods odp ON odp.id = od.period_id
WHERE odp.status = 'published'
ORDER BY od.starts_at, od.id
`

func (q *Queries) ListPublishedOpenDays(ctx context.Context) ([]OpenDay, error) {
	rows, err := q.db.Query(ctx, listPublishedOpenDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OpenDay{}
	for rows.Next() {
		var i OpenDay
		if err := rows.Scan(
			&i.ID,
			&i.PeriodID,
			&i.StartsAt,
			&i.EndsAt,
			&i.InternalNote,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequirementRoleIDs = `-- name: ListRequirementRoleIDs :many
SELECT role_id FROM open_day_staff_requirement_roles
WHERE requirement_id = $1 ORDER BY role_id
`

func (q *Queries) ListRequirementRoleIDs(ctx context.Context, requirementID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listRequirementRoleIDs, requirementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var role_id uuid.UUID
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequirements = `-- name: ListRequirements :many
SELECT id, open_day_id, kind, required_count FROM open_day_staff_requirements WHERE open_day_id = $1 ORDER BY kind
`

func (q *Queries) ListRequirements(ctx context.Context, openDayID uuid.UUID) ([]OpenDayStaffRequirement, error) {
	rows, err := q.db.Query(ctx, listRequirements, openDayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OpenDayStaffRequirement{}
	for rows.Next() {
		var i OpenDayStaffRequirement
		if err := rows.Scan(
			&i.ID,
			&i.OpenDayID,
			&i.Kind,
			&i.RequiredCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const personEligibleForRequirement = `-- name: PersonEligibleForRequirement :one
SELECT EXISTS (
    SELECT 1 FROM people p
    JOIN accounts a ON a.person_id = p.id AND a.status = 'enabled'
    JOIN account_roles ar ON ar.account_id = a.id
    JOIN open_day_staff_requirement_roles rr ON rr.role_id = ar.role_id
    WHERE p.id = $1 AND rr.requirement_id = $2
)
`

type PersonEligibleForRequirementParams struct {
	PersonID      uuid.UUID
	RequirementID uuid.UUID
}

func (q *Queries) PersonEligibleForRequirement(ctx context.Context, arg PersonEligibleForRequirementParams) (bool, error) {
	row := q.db.QueryRow(ctx, personEligibleForRequirement, arg.PersonID, arg.RequirementID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const transitionPeriod = `-- name: TransitionPeriod :one
UPDATE open_day_periods
SET status = $1, version = version + 1, updated_at = now()
WHERE id = $2 AND version = $3
RETURNING id, name, starts_on, ends_on, status, version, created_at, updated_at
`

type TransitionPeriodParams struct {
	Status          string
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) TransitionPeriod(ctx context.Context, arg TransitionPeriodParams) (OpenDayPeriod, error) {
	row := q.db.QueryRow(ctx, transitionPeriod, arg.Status, arg.ID, arg.ExpectedVersion)
	var i OpenDayPeriod
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartsOn,
		&i.EndsOn,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAcademicBreak = `-- name: UpdateAcademicBreak :one
UPDATE open_day_academic_breaks
SET name = $1, starts_on = $2, ends_on = $3,
    version = version + 1, updated_at = now()
WHERE id = $4 AND version = $5 RETURNING id, name, starts_on, ends_on, version, created_at, updated_at
`

type UpdateAcademicBreakParams struct {
	Name            string
	StartsOn        pgtype.Date
	EndsOn          pgtype.Date
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) UpdateAcademicBreak(ctx context.Context, arg UpdateAcademicBreakParams) (OpenDayAcademicBreak, error) {
	row := q.db.QueryRow(ctx, updateAcademicBreak,
		arg.Name,
		arg.StartsOn,
		arg.EndsOn,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i OpenDayAcademicBreak
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartsOn,
		&i.EndsOn,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOpenDay = `-- name: UpdateOpenDay :one
UPDATE open_days
SET starts_at = $1, ends_at = $2, internal_note = $3,
    version = version + 1, updated_at = now()
WHERE id = $4 AND version = $5 AND status = 'scheduled'
RETURNING id, period_id, starts_at, ends_at, internal_note, status, version, created_at, updated_at
`

type UpdateOpenDayParams struct {
	StartsAt        time.Time
	EndsAt          time.Time
	InternalNote    *string
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) UpdateOpenDay(ctx context.Context, arg UpdateOpenDayParams) (OpenDay, error) {
	row := q.db.QueryRow(ctx, updateOpenDay,
		arg.StartsAt,
		arg.EndsAt,
		arg.InternalNote,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i OpenDay
	err := row.Scan(
		&i.ID,
		&i.PeriodID,
		&i.StartsAt,
		&i.EndsAt,
		&i.InternalNote,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePeriod = `-- name: UpdatePeriod :one
UPDATE open_day_periods
SET name = $1, starts_on = $2, ends_on = $3,
    version = version + 1, updated_at = now()
WHERE id = $4 AND version = $5 AND status = 'draft'
RETURNING id, name, starts_on, ends_on, status, version, created_at, updated_at
`

type UpdatePeriodParams struct {
	Name            string
	StartsOn        pgtype.Date
	EndsOn          pgtype.Date
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) UpdatePeriod(ctx context.Context, arg UpdatePeriodParams) (OpenDayPeriod, error) {
	row := q.db.QueryRow(ctx, updatePeriod,
		arg.Name,
		arg.StartsOn,
		arg.EndsOn,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i OpenDayPeriod
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartsOn,
		&i.EndsOn,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRequirement = `-- name: UpdateRequirement :one
UPDATE open_day_staff_requirements SET required_count = $1
WHERE id = $2 RETURNING id, open_day_id, kind, required_count
`

type UpdateRequirementParams struct {
	RequiredCount int32
	ID            uuid.UUID
}

func (q *Queries) UpdateRequirement(ctx context.Context, arg UpdateRequirementParams) (OpenDayStaffRequirement, error) {
	row := q.db.QueryRow(ctx, updateRequirement, arg.RequiredCount, arg.ID)
	var i OpenDayStaffRequirement
	err := row.Scan(
		&i.ID,
		&i.OpenDayID,
		&i.Kind,
		&i.RequiredCount,
	)
	return i, err
}
