// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package attendancedb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveExpiredVisitDetail = `-- name: ArchiveExpiredVisitDetail :execrows
WITH expired AS (
  DELETE FROM visits
  WHERE (status = 'checked_out' AND checked_out_at < $1)
     OR (status = 'voided' AND updated_at < $1)
  RETURNING id, person_id, checked_in_at, checked_out_at, check_in_device_id, check_out_device_id, status, check_in_method, check_out_method, check_in_assurance, check_out_assurance, admission_decision, laborordnung_version_id, checked_in_by_account_id, checked_out_by_account_id, correction_reason, version, created_at, updated_at
), segments AS (
  SELECT e.id, e.person_id, e.checked_in_at, e.checked_out_at, e.check_in_device_id, e.check_out_device_id, e.status, e.check_in_method, e.check_out_method, e.check_in_assurance, e.check_out_assurance, e.admission_decision, e.laborordnung_version_id, e.checked_in_by_account_id, e.checked_out_by_account_id, e.correction_reason, e.version, e.created_at, e.updated_at,
    day_start::date AS day,
    GREATEST(e.checked_in_at, day_start) AS segment_start,
    LEAST(e.checked_out_at, day_start + interval '1 day') AS segment_end
  FROM expired e
  CROSS JOIN LATERAL generate_series(
    date_trunc('day', e.checked_in_at),
    date_trunc('day', e.checked_out_at),
    interval '1 day'
  ) day_start
  WHERE e.status = 'checked_out'
), base AS (
  SELECT day,
    count(*) FILTER (WHERE checked_in_at >= day::timestamptz AND checked_in_at < day::timestamptz + interval '1 day')::bigint AS visitor_count,
    count(DISTINCT person_id) FILTER (WHERE checked_in_at >= day::timestamptz AND checked_in_at < day::timestamptz + interval '1 day')::bigint AS daily_unique_visitors,
    COALESCE(sum(extract(epoch FROM segment_end - segment_start)), 0)::bigint AS visitor_seconds,
    count(*) FILTER (WHERE checked_out_at >= day::timestamptz AND checked_out_at < day::timestamptz + interval '1 day')::bigint AS completed_visit_count,
    COALESCE(sum(extract(epoch FROM checked_out_at - checked_in_at)) FILTER (WHERE checked_out_at >= day::timestamptz AND checked_out_at < day::timestamptz + interval '1 day'), 0)::bigint AS completed_visit_seconds
  FROM segments GROUP BY day
), points AS (
  SELECT day, segment_start AS at, 1::bigint AS delta FROM segments WHERE segment_end > segment_start
  UNION ALL
  SELECT day, segment_end AS at, -1::bigint AS delta FROM segments WHERE segment_end > segment_start
), point_totals AS (
  SELECT day, at, sum(delta)::bigint AS delta FROM points GROUP BY day, at
), occupancy AS (
  SELECT day, sum(delta) OVER (PARTITION BY day ORDER BY at) AS value FROM point_totals
), aggregated AS (
  SELECT b.day, b.visitor_count, b.daily_unique_visitors, b.visitor_seconds, b.completed_visit_count, b.completed_visit_seconds, COALESCE(max(o.value), 0)::bigint AS peak_occupancy
  FROM base b LEFT JOIN occupancy o ON o.day = b.day
  GROUP BY b.day, b.visitor_count, b.daily_unique_visitors, b.visitor_seconds,
    b.completed_visit_count, b.completed_visit_seconds
)
INSERT INTO attendance_daily_statistics(day, visitor_count, daily_unique_visitors, visitor_seconds,
  completed_visit_count, completed_visit_seconds, peak_occupancy)
SELECT day, visitor_count, daily_unique_visitors, visitor_seconds,
  completed_visit_count, completed_visit_seconds, peak_occupancy
FROM aggregated
ON CONFLICT (day) DO UPDATE SET
  visitor_count = attendance_daily_statistics.visitor_count + EXCLUDED.visitor_count,
  daily_unique_visitors = attendance_daily_statistics.daily_unique_visitors + EXCLUDED.daily_unique_visitors,
  visitor_seconds = attendance_daily_statistics.visitor_seconds + EXCLUDED.visitor_seconds,
  completed_visit_count = attendance_daily_statistics.completed_visit_count + EXCLUDED.completed_visit_count,
  completed_visit_seconds = attendance_daily_statistics.completed_visit_seconds + EXCLUDED.completed_visit_seconds,
  peak_occupancy = GREATEST(attendance_daily_statistics.peak_occupancy, EXCLUDED.peak_occupancy),
  updated_at = now()
`

func (q *Queries) ArchiveExpiredVisitDetail(ctx context.Context, beforeTime pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, archiveExpiredVisitDetail, beforeTime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const attendanceStatistics = `-- name: AttendanceStatistics :one
WITH relevant AS (
  SELECT id, person_id, checked_in_at, checked_out_at, check_in_device_id, check_out_device_id, status, check_in_method, check_out_method, check_in_assurance, check_out_assurance, admission_decision, laborordnung_version_id, checked_in_by_account_id, checked_out_by_account_id, correction_reason, version, created_at, updated_at FROM visits
  WHERE status <> 'voided' AND checked_in_at < $2
    AND COALESCE(checked_out_at, now()) > $1
), points AS (
  SELECT GREATEST(checked_in_at, $1) AS at, 1::bigint AS delta FROM relevant
  UNION ALL
  SELECT LEAST(COALESCE(checked_out_at, $2), $2) AS at, -1::bigint AS delta
  FROM relevant WHERE COALESCE(checked_out_at, $2) < $2
), occupancy AS (
  SELECT sum(sum(delta)) OVER (ORDER BY at) AS value FROM points GROUP BY at
)
SELECT
  (SELECT count(*) FROM visits counts WHERE counts.status <> 'voided' AND counts.checked_in_at >= $1 AND counts.checked_in_at < $2)::bigint AS visitor_count,
  (SELECT count(DISTINCT uniques.person_id) FROM visits uniques WHERE uniques.status <> 'voided' AND uniques.checked_in_at >= $1 AND uniques.checked_in_at < $2)::bigint AS unique_visitors,
  COALESCE((SELECT sum(extract(epoch FROM (LEAST(COALESCE(checked_out_at, $2), $2) - GREATEST(checked_in_at, $1)))) / 3600 FROM relevant), 0)::numeric AS visitor_hours,
  COALESCE((SELECT max(value) FROM occupancy), 0)::bigint AS peak_occupancy,
  (SELECT count(*) FROM visits current_visits WHERE current_visits.status = 'checked_in')::bigint AS current_occupancy,
  COALESCE((SELECT avg(extract(epoch FROM (completed.checked_out_at - completed.checked_in_at))) / 60 FROM visits completed
    WHERE completed.status = 'checked_out' AND completed.checked_out_at >= $1 AND completed.checked_out_at < $2), 0)::numeric AS average_completed_visit_minutes
`

type AttendanceStatisticsParams struct {
	FromTime time.Time
	ToTime   time.Time
}

type AttendanceStatisticsRow struct {
	VisitorCount                 int64
	UniqueVisitors               int64
	VisitorHours                 pgtype.Numeric
	PeakOccupancy                int64
	CurrentOccupancy             int64
	AverageCompletedVisitMinutes pgtype.Numeric
}

func (q *Queries) AttendanceStatistics(ctx context.Context, arg AttendanceStatisticsParams) (AttendanceStatisticsRow, error) {
	row := q.db.QueryRow(ctx, attendanceStatistics, arg.FromTime, arg.ToTime)
	var i AttendanceStatisticsRow
	err := row.Scan(
		&i.VisitorCount,
		&i.UniqueVisitors,
		&i.VisitorHours,
		&i.PeakOccupancy,
		&i.CurrentOccupancy,
		&i.AverageCompletedVisitMinutes,
	)
	return i, err
}

const checkOutVisit = `-- name: CheckOutVisit :one
WITH updated AS (
  UPDATE visits SET checked_out_at = now(), check_out_device_id = $1,
    status = 'checked_out', check_out_method = $2,
    check_out_assurance = $3,
    checked_out_by_account_id = $4,
    version = version + 1, updated_at = now()
  WHERE visits.id = $5 AND visits.status = 'checked_in'
  RETURNING id, person_id, checked_in_at, checked_out_at, check_in_device_id, check_out_device_id, status, check_in_method, check_out_method, check_in_assurance, check_out_assurance, admission_decision, laborordnung_version_id, checked_in_by_account_id, checked_out_by_account_id, correction_reason, version, created_at, updated_at
)
SELECT updated.id, updated.person_id, updated.checked_in_at, updated.checked_out_at, updated.check_in_device_id, updated.check_out_device_id, updated.status, updated.check_in_method, updated.check_out_method, updated.check_in_assurance, updated.check_out_assurance, updated.admission_decision, updated.laborordnung_version_id, updated.checked_in_by_account_id, updated.checked_out_by_account_id, updated.correction_reason, updated.version, updated.created_at, updated.updated_at, p.first_name, p.last_name FROM updated JOIN people p ON p.id = updated.person_id
`

type CheckOutVisitParams struct {
	CheckOutDeviceID      *uuid.UUID
	CheckOutMethod        *string
	CheckOutAssurance     *string
	CheckedOutByAccountID *uuid.UUID
	VisitID               uuid.UUID
}

type CheckOutVisitRow struct {
	ID                    uuid.UUID
	PersonID              uuid.UUID
	CheckedInAt           time.Time
	CheckedOutAt          pgtype.Timestamptz
	CheckInDeviceID       *uuid.UUID
	CheckOutDeviceID      *uuid.UUID
	Status                string
	CheckInMethod         string
	CheckOutMethod        *string
	CheckInAssurance      string
	CheckOutAssurance     *string
	AdmissionDecision     string
	LaborordnungVersionID *uuid.UUID
	CheckedInByAccountID  *uuid.UUID
	CheckedOutByAccountID *uuid.UUID
	CorrectionReason      *string
	Version               int64
	CreatedAt             time.Time
	UpdatedAt             time.Time
	FirstName             string
	LastName              string
}

func (q *Queries) CheckOutVisit(ctx context.Context, arg CheckOutVisitParams) (CheckOutVisitRow, error) {
	row := q.db.QueryRow(ctx, checkOutVisit,
		arg.CheckOutDeviceID,
		arg.CheckOutMethod,
		arg.CheckOutAssurance,
		arg.CheckedOutByAccountID,
		arg.VisitID,
	)
	var i CheckOutVisitRow
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.CheckedInAt,
		&i.CheckedOutAt,
		&i.CheckInDeviceID,
		&i.CheckOutDeviceID,
		&i.Status,
		&i.CheckInMethod,
		&i.CheckOutMethod,
		&i.CheckInAssurance,
		&i.CheckOutAssurance,
		&i.AdmissionDecision,
		&i.LaborordnungVersionID,
		&i.CheckedInByAccountID,
		&i.CheckedOutByAccountID,
		&i.CorrectionReason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const createVisit = `-- name: CreateVisit :one
WITH inserted AS (
  INSERT INTO visits (id, person_id, checked_in_at, check_in_device_id, check_in_method,
    check_in_assurance, admission_decision, laborordnung_version_id, checked_in_by_account_id)
  VALUES ($1, $2, now(), $3, $4,
    $5, $6, $7,
    $8)
  RETURNING id, person_id, checked_in_at, checked_out_at, check_in_device_id, check_out_device_id, status, check_in_method, check_out_method, check_in_assurance, check_out_assurance, admission_decision, laborordnung_version_id, checked_in_by_account_id, checked_out_by_account_id, correction_reason, version, created_at, updated_at
)
SELECT inserted.id, inserted.person_id, inserted.checked_in_at, inserted.checked_out_at, inserted.check_in_device_id, inserted.check_out_device_id, inserted.status, inserted.check_in_method, inserted.check_out_method, inserted.check_in_assurance, inserted.check_out_assurance, inserted.admission_decision, inserted.laborordnung_version_id, inserted.checked_in_by_account_id, inserted.checked_out_by_account_id, inserted.correction_reason, inserted.version, inserted.created_at, inserted.updated_at, p.first_name, p.last_name FROM inserted JOIN people p ON p.id = inserted.person_id
`

type CreateVisitParams struct {
	ID                    uuid.UUID
	PersonID              uuid.UUID
	CheckInDeviceID       *uuid.UUID
	CheckInMethod         string
	CheckInAssurance      string
	AdmissionDecision     string
	LaborordnungVersionID *uuid.UUID
	CheckedInByAccountID  *uuid.UUID
}

type CreateVisitRow struct {
	ID                    uuid.UUID
	PersonID              uuid.UUID
	CheckedInAt           time.Time
	CheckedOutAt          pgtype.Timestamptz
	CheckInDeviceID       *uuid.UUID
	CheckOutDeviceID      *uuid.UUID
	Status                string
	CheckInMethod         string
	CheckOutMethod        *string
	CheckInAssurance      string
	CheckOutAssurance     *string
	AdmissionDecision     string
	LaborordnungVersionID *uuid.UUID
	CheckedInByAccountID  *uuid.UUID
	CheckedOutByAccountID *uuid.UUID
	CorrectionReason      *string
	Version               int64
	CreatedAt             time.Time
	UpdatedAt             time.Time
	FirstName             string
	LastName              string
}

func (q *Queries) CreateVisit(ctx context.Context, arg CreateVisitParams) (CreateVisitRow, error) {
	row := q.db.QueryRow(ctx, createVisit,
		arg.ID,
		arg.PersonID,
		arg.CheckInDeviceID,
		arg.CheckInMethod,
		arg.CheckInAssurance,
		arg.AdmissionDecision,
		arg.LaborordnungVersionID,
		arg.CheckedInByAccountID,
	)
	var i CreateVisitRow
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.CheckedInAt,
		&i.CheckedOutAt,
		&i.CheckInDeviceID,
		&i.CheckOutDeviceID,
		&i.Status,
		&i.CheckInMethod,
		&i.CheckOutMethod,
		&i.CheckInAssurance,
		&i.CheckOutAssurance,
		&i.AdmissionDecision,
		&i.LaborordnungVersionID,
		&i.CheckedInByAccountID,
		&i.CheckedOutByAccountID,
		&i.CorrectionReason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const getOpenVisitByID = `-- name: GetOpenVisitByID :one
SELECT v.id, v.person_id, v.checked_in_at, v.checked_out_at, v.check_in_device_id, v.check_out_device_id, v.status, v.check_in_method, v.check_out_method, v.check_in_assurance, v.check_out_assurance, v.admission_decision, v.laborordnung_version_id, v.checked_in_by_account_id, v.checked_out_by_account_id, v.correction_reason, v.version, v.created_at, v.updated_at, p.first_name, p.last_name
FROM visits v JOIN people p ON p.id = v.person_id
WHERE v.id = $1 AND v.status = 'checked_in'
FOR UPDATE OF v
`

type GetOpenVisitByIDRow struct {
	ID                    uuid.UUID
	PersonID              uuid.UUID
	CheckedInAt           time.Time
	CheckedOutAt          pgtype.Timestamptz
	CheckInDeviceID       *uuid.UUID
	CheckOutDeviceID      *uuid.UUID
	Status                string
	CheckInMethod         string
	CheckOutMethod        *string
	CheckInAssurance      string
	CheckOutAssurance     *string
	AdmissionDecision     string
	LaborordnungVersionID *uuid.UUID
	CheckedInByAccountID  *uuid.UUID
	CheckedOutByAccountID *uuid.UUID
	CorrectionReason      *string
	Version               int64
	CreatedAt             time.Time
	UpdatedAt             time.Time
	FirstName             string
	LastName              string
}

func (q *Queries) GetOpenVisitByID(ctx context.Context, id uuid.UUID) (GetOpenVisitByIDRow, error) {
	row := q.db.QueryRow(ctx, getOpenVisitByID, id)
	var i GetOpenVisitByIDRow
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.CheckedInAt,
		&i.CheckedOutAt,
		&i.CheckInDeviceID,
		&i.CheckOutDeviceID,
		&i.Status,
		&i.CheckInMethod,
		&i.CheckOutMethod,
		&i.CheckInAssurance,
		&i.CheckOutAssurance,
		&i.AdmissionDecision,
		&i.LaborordnungVersionID,
		&i.CheckedInByAccountID,
		&i.CheckedOutByAccountID,
		&i.CorrectionReason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const getOpenVisitForPerson = `-- name: GetOpenVisitForPerson :one
SELECT v.id, v.person_id, v.checked_in_at, v.checked_out_at, v.check_in_device_id, v.check_out_device_id, v.status, v.check_in_method, v.check_out_method, v.check_in_assurance, v.check_out_assurance, v.admission_decision, v.laborordnung_version_id, v.checked_in_by_account_id, v.checked_out_by_account_id, v.correction_reason, v.version, v.created_at, v.updated_at, p.first_name, p.last_name
FROM visits v JOIN people p ON p.id = v.person_id
WHERE v.person_id = $1 AND v.status = 'checked_in'
FOR UPDATE OF v
`

type GetOpenVisitForPersonRow struct {
	ID                    uuid.UUID
	PersonID              uuid.UUID
	CheckedInAt           time.Time
	CheckedOutAt          pgtype.Timestamptz
	CheckInDeviceID       *uuid.UUID
	CheckOutDeviceID      *uuid.UUID
	Status                string
	CheckInMethod         string
	CheckOutMethod        *string
	CheckInAssurance      string
	CheckOutAssurance     *string
	AdmissionDecision     string
	LaborordnungVersionID *uuid.UUID
	CheckedInByAccountID  *uuid.UUID
	CheckedOutByAccountID *uuid.UUID
	CorrectionReason      *string
	Version               int64
	CreatedAt             time.Time
	UpdatedAt             time.Time
	FirstName             string
	LastName              string
}

func (q *Queries) GetOpenVisitForPerson(ctx context.Context, personID uuid.UUID) (GetOpenVisitForPersonRow, error) {
	row := q.db.QueryRow(ctx, getOpenVisitForPerson, personID)
	var i GetOpenVisitForPersonRow
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.CheckedInAt,
		&i.CheckedOutAt,
		&i.CheckInDeviceID,
		&i.CheckOutDeviceID,
		&i.Status,
		&i.CheckInMethod,
		&i.CheckOutMethod,
		&i.CheckInAssurance,
		&i.CheckOutAssurance,
		&i.AdmissionDecision,
		&i.LaborordnungVersionID,
		&i.CheckedInByAccountID,
		&i.CheckedOutByAccountID,
		&i.CorrectionReason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const getPersonDisplay = `-- name: GetPersonDisplay :one
SELECT id, first_name, last_name, email FROM people WHERE id = $1
`

type GetPersonDisplayRow struct {
	ID        uuid.UUID
	FirstName string
	LastName  string
	Email     *string
}

func (q *Queries) GetPersonDisplay(ctx context.Context, id uuid.UUID) (GetPersonDisplayRow, error) {
	row := q.db.QueryRow(ctx, getPersonDisplay, id)
	var i GetPersonDisplayRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
	)
	return i, err
}

const getTerminalDevice = `-- name: GetTerminalDevice :one
SELECT md.id, md.name, md.terminal_enabled, md.check_in_assurance, md.check_out_assurance,
       md.checkout_mode, md.revoked_at, md.expires_at
FROM managed_devices md
WHERE md.id = $1 AND md.terminal_enabled AND md.revoked_at IS NULL
  AND (md.expires_at IS NULL OR md.expires_at > now())
`

type GetTerminalDeviceRow struct {
	ID                uuid.UUID
	Name              string
	TerminalEnabled   bool
	CheckInAssurance  string
	CheckOutAssurance string
	CheckoutMode      string
	RevokedAt         pgtype.Timestamptz
	ExpiresAt         pgtype.Timestamptz
}

func (q *Queries) GetTerminalDevice(ctx context.Context, id uuid.UUID) (GetTerminalDeviceRow, error) {
	row := q.db.QueryRow(ctx, getTerminalDevice, id)
	var i GetTerminalDeviceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TerminalEnabled,
		&i.CheckInAssurance,
		&i.CheckOutAssurance,
		&i.CheckoutMode,
		&i.RevokedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getVisitByIDForUpdate = `-- name: GetVisitByIDForUpdate :one
SELECT v.id, v.person_id, v.checked_in_at, v.checked_out_at, v.check_in_device_id, v.check_out_device_id, v.status, v.check_in_method, v.check_out_method, v.check_in_assurance, v.check_out_assurance, v.admission_decision, v.laborordnung_version_id, v.checked_in_by_account_id, v.checked_out_by_account_id, v.correction_reason, v.version, v.created_at, v.updated_at, p.first_name, p.last_name
FROM visits v JOIN people p ON p.id = v.person_id
WHERE v.id = $1
FOR UPDATE OF v
`

type GetVisitByIDForUpdateRow struct {
	ID                    uuid.UUID
	PersonID              uuid.UUID
	CheckedInAt           time.Time
	CheckedOutAt          pgtype.Timestamptz
	CheckInDeviceID       *uuid.UUID
	CheckOutDeviceID      *uuid.UUID
	Status                string
	CheckInMethod         string
	CheckOutMethod        *string
	CheckInAssurance      string
	CheckOutAssurance     *string
	AdmissionDecision     string
	LaborordnungVersionID *uuid.UUID
	CheckedInByAccountID  *uuid.UUID
	CheckedOutByAccountID *uuid.UUID
	CorrectionReason      *string
	Version               int64
	CreatedAt             time.Time
	UpdatedAt             time.Time
	FirstName             string
	LastName              string
}

func (q *Queries) GetVisitByIDForUpdate(ctx context.Context, id uuid.UUID) (GetVisitByIDForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getVisitByIDForUpdate, id)
	var i GetVisitByIDForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.CheckedInAt,
		&i.CheckedOutAt,
		&i.CheckInDeviceID,
		&i.CheckOutDeviceID,
		&i.Status,
		&i.CheckInMethod,
		&i.CheckOutMethod,
		&i.CheckInAssurance,
		&i.CheckOutAssurance,
		&i.AdmissionDecision,
		&i.LaborordnungVersionID,
		&i.CheckedInByAccountID,
		&i.CheckedOutByAccountID,
		&i.CorrectionReason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const listPublicPresence = `-- name: ListPublicPresence :many
SELECT v.id, v.checked_in_at, p.first_name, left(p.last_name, 1)::text AS last_initial
FROM visits v JOIN people p ON p.id = v.person_id
WHERE v.status = 'checked_in'
ORDER BY lower(p.first_name), lower(p.last_name), v.checked_in_at, v.id
`

type ListPublicPresenceRow struct {
	ID          uuid.UUID
	CheckedInAt time.Time
	FirstName   string
	LastInitial string
}

func (q *Queries) ListPublicPresence(ctx context.Context) ([]ListPublicPresenceRow, error) {
	rows, err := q.db.Query(ctx, listPublicPresence)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicPresenceRow{}
	for rows.Next() {
		var i ListPublicPresenceRow
		if err := rows.Scan(
			&i.ID,
			&i.CheckedInAt,
			&i.FirstName,
			&i.LastInitial,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTerminalCapabilities = `-- name: ListTerminalCapabilities :many
SELECT capability FROM managed_device_capabilities
WHERE managed_device_id = $1 AND enabled ORDER BY capability
`

func (q *Queries) ListTerminalCapabilities(ctx context.Context, managedDeviceID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listTerminalCapabilities, managedDeviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var capability string
		if err := rows.Scan(&capability); err != nil {
			return nil, err
		}
		items = append(items, capability)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisits = `-- name: ListVisits :many
SELECT v.id, v.person_id, v.checked_in_at, v.checked_out_at, v.check_in_device_id, v.check_out_device_id, v.status, v.check_in_method, v.check_out_method, v.check_in_assurance, v.check_out_assurance, v.admission_decision, v.laborordnung_version_id, v.checked_in_by_account_id, v.checked_out_by_account_id, v.correction_reason, v.version, v.created_at, v.updated_at, p.first_name, p.last_name
FROM visits v JOIN people p ON p.id = v.person_id
WHERE (NOT $1::boolean OR v.status = 'checked_in')
  AND ($2::timestamptz IS NULL OR v.checked_in_at >= $2)
  AND ($3::timestamptz IS NULL OR v.checked_in_at < $3)
ORDER BY v.checked_in_at DESC, v.id DESC
LIMIT 500
`

type ListVisitsParams struct {
	CurrentlyHere bool
	FromTime      pgtype.Timestamptz
	ToTime        pgtype.Timestamptz
}

type ListVisitsRow struct {
	ID                    uuid.UUID
	PersonID              uuid.UUID
	CheckedInAt           time.Time
	CheckedOutAt          pgtype.Timestamptz
	CheckInDeviceID       *uuid.UUID
	CheckOutDeviceID      *uuid.UUID
	Status                string
	CheckInMethod         string
	CheckOutMethod        *string
	CheckInAssurance      string
	CheckOutAssurance     *string
	AdmissionDecision     string
	LaborordnungVersionID *uuid.UUID
	CheckedInByAccountID  *uuid.UUID
	CheckedOutByAccountID *uuid.UUID
	CorrectionReason      *string
	Version               int64
	CreatedAt             time.Time
	UpdatedAt             time.Time
	FirstName             string
	LastName              string
}

func (q *Queries) ListVisits(ctx context.Context, arg ListVisitsParams) ([]ListVisitsRow, error) {
	rows, err := q.db.Query(ctx, listVisits, arg.CurrentlyHere, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVisitsRow{}
	for rows.Next() {
		var i ListVisitsRow
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.CheckedInAt,
			&i.CheckedOutAt,
			&i.CheckInDeviceID,
			&i.CheckOutDeviceID,
			&i.Status,
			&i.CheckInMethod,
			&i.CheckOutMethod,
			&i.CheckInAssurance,
			&i.CheckOutAssurance,
			&i.AdmissionDecision,
			&i.LaborordnungVersionID,
			&i.CheckedInByAccountID,
			&i.CheckedOutByAccountID,
			&i.CorrectionReason,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEnabledAttendanceAccount = `-- name: LockEnabledAttendanceAccount :one
SELECT id FROM accounts
WHERE id = $1 AND person_id = $2 AND status = 'enabled'
FOR SHARE
`

type LockEnabledAttendanceAccountParams struct {
	AccountID uuid.UUID
	PersonID  uuid.UUID
}

func (q *Queries) LockEnabledAttendanceAccount(ctx context.Context, arg LockEnabledAttendanceAccountParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockEnabledAttendanceAccount, arg.AccountID, arg.PersonID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const lockPerson = `-- name: LockPerson :one
SELECT id FROM people WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockPerson(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockPerson, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const voidVisit = `-- name: VoidVisit :one
WITH updated AS (
  UPDATE visits SET status = 'voided', correction_reason = $1,
    version = version + 1, updated_at = now()
  WHERE visits.id = $2 AND visits.version = $3
    AND visits.status <> 'voided'
  RETURNING id, person_id, checked_in_at, checked_out_at, check_in_device_id, check_out_device_id, status, check_in_method, check_out_method, check_in_assurance, check_out_assurance, admission_decision, laborordnung_version_id, checked_in_by_account_id, checked_out_by_account_id, correction_reason, version, created_at, updated_at
)
SELECT updated.id, updated.person_id, updated.checked_in_at, updated.checked_out_at, updated.check_in_device_id, updated.check_out_device_id, updated.status, updated.check_in_method, updated.check_out_method, updated.check_in_assurance, updated.check_out_assurance, updated.admission_decision, updated.laborordnung_version_id, updated.checked_in_by_account_id, updated.checked_out_by_account_id, updated.correction_reason, updated.version, updated.created_at, updated.updated_at, p.first_name, p.last_name FROM updated JOIN people p ON p.id = updated.person_id
`

type VoidVisitParams struct {
	CorrectionReason *string
	VisitID          uuid.UUID
	ExpectedVersion  int64
}

type VoidVisitRow struct {
	ID                    uuid.UUID
	PersonID              uuid.UUID
	CheckedInAt           time.Time
	CheckedOutAt          pgtype.Timestamptz
	CheckInDeviceID       *uuid.UUID
	CheckOutDeviceID      *uuid.UUID
	Status                string
	CheckInMethod         string
	CheckOutMethod        *string
	CheckInAssurance      string
	CheckOutAssurance     *string
	AdmissionDecision     string
	LaborordnungVersionID *uuid.UUID
	CheckedInByAccountID  *uuid.UUID
	CheckedOutByAccountID *uuid.UUID
	CorrectionReason      *string
	Version               int64
	CreatedAt             time.Time
	UpdatedAt             time.Time
	FirstName             string
	LastName              string
}

func (q *Queries) VoidVisit(ctx context.Context, arg VoidVisitParams) (VoidVisitRow, error) {
	row := q.db.QueryRow(ctx, voidVisit, arg.CorrectionReason, arg.VisitID, arg.ExpectedVersion)
	var i VoidVisitRow
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.CheckedInAt,
		&i.CheckedOutAt,
		&i.CheckInDeviceID,
		&i.CheckOutDeviceID,
		&i.Status,
		&i.CheckInMethod,
		&i.CheckOutMethod,
		&i.CheckInAssurance,
		&i.CheckOutAssurance,
		&i.AdmissionDecision,
		&i.LaborordnungVersionID,
		&i.CheckedInByAccountID,
		&i.CheckedOutByAccountID,
		&i.CorrectionReason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}
