// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package accountsdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acquireMasterInvariantLock = `-- name: AcquireMasterInvariantLock :exec
SELECT pg_advisory_xact_lock(5577006791947779410)
`

func (q *Queries) AcquireMasterInvariantLock(ctx context.Context) error {
	_, err := q.db.Exec(ctx, acquireMasterInvariantLock)
	return err
}

const bumpAccountVersion = `-- name: BumpAccountVersion :one
UPDATE accounts SET version = version + 1, updated_at = now()
WHERE id = $1 AND version = $2 RETURNING id, person_id, status, version, created_at, updated_at, provisioning_source, first_authenticated_at, administratively_disabled_at
`

type BumpAccountVersionParams struct {
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) BumpAccountVersion(ctx context.Context, arg BumpAccountVersionParams) (Account, error) {
	row := q.db.QueryRow(ctx, bumpAccountVersion, arg.ID, arg.ExpectedVersion)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProvisioningSource,
		&i.FirstAuthenticatedAt,
		&i.AdministrativelyDisabledAt,
	)
	return i, err
}

const bumpAccountVersionForAdministrativeReset = `-- name: BumpAccountVersionForAdministrativeReset :exec
UPDATE accounts SET version = version + 1, updated_at = now()
WHERE id = $1
`

func (q *Queries) BumpAccountVersionForAdministrativeReset(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, bumpAccountVersionForAdministrativeReset, id)
	return err
}

const countEnabledMasters = `-- name: CountEnabledMasters :one
SELECT count(*) FROM accounts a
JOIN person_roles pr ON pr.person_id = a.person_id
JOIN roles r ON r.id = pr.role_id
WHERE a.status = 'enabled' AND r.system_key = 'master'
`

func (q *Queries) CountEnabledMasters(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEnabledMasters)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (id, person_id, status)
VALUES ($1, $2, $3) RETURNING id, person_id, status, version, created_at, updated_at, provisioning_source, first_authenticated_at, administratively_disabled_at
`

type CreateAccountParams struct {
	ID       uuid.UUID
	PersonID uuid.UUID
	Status   string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.ID, arg.PersonID, arg.Status)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProvisioningSource,
		&i.FirstAuthenticatedAt,
		&i.AdministrativelyDisabledAt,
	)
	return i, err
}

const createAuthIdentity = `-- name: CreateAuthIdentity :one
INSERT INTO auth_identities (id, account_id, kind, identifier_display, identifier_normalized)
VALUES ($1, $2, 'password', $3::text, $4::text)
RETURNING id, account_id, kind, identifier_display, identifier_normalized, created_at, updated_at, provider_id, issuer, subject, verified_at, disabled_at, last_used_at
`

type CreateAuthIdentityParams struct {
	ID                   uuid.UUID
	AccountID            uuid.UUID
	IdentifierDisplay    string
	IdentifierNormalized string
}

func (q *Queries) CreateAuthIdentity(ctx context.Context, arg CreateAuthIdentityParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, createAuthIdentity,
		arg.ID,
		arg.AccountID,
		arg.IdentifierDisplay,
		arg.IdentifierNormalized,
	)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Kind,
		&i.IdentifierDisplay,
		&i.IdentifierNormalized,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderID,
		&i.Issuer,
		&i.Subject,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.LastUsedAt,
	)
	return i, err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (id, account_id, token_digest, created_by_account_id, expires_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (account_id) DO UPDATE SET id = EXCLUDED.id, token_digest = EXCLUDED.token_digest,
    created_by_account_id = EXCLUDED.created_by_account_id, created_at = now(), expires_at = EXCLUDED.expires_at
RETURNING id, account_id, token_digest, created_by_account_id, created_at, expires_at
`

type CreatePasswordResetTokenParams struct {
	ID                 uuid.UUID
	AccountID          uuid.UUID
	TokenDigest        []byte
	CreatedByAccountID *uuid.UUID
	ExpiresAt          time.Time
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken,
		arg.ID,
		arg.AccountID,
		arg.TokenDigest,
		arg.CreatedByAccountID,
		arg.ExpiresAt,
	)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenDigest,
		&i.CreatedByAccountID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :one
DELETE FROM accounts WHERE id = $1 AND version = $2 RETURNING id
`

type DeleteAccountParams struct {
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) DeleteAccount(ctx context.Context, arg DeleteAccountParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteAccount, arg.ID, arg.ExpectedVersion)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteAuthIdentityForAccount = `-- name: DeleteAuthIdentityForAccount :execrows
DELETE FROM auth_identities
WHERE id = $1 AND account_id = $2
`

type DeleteAuthIdentityForAccountParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) DeleteAuthIdentityForAccount(ctx context.Context, arg DeleteAuthIdentityForAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAuthIdentityForAccount, arg.ID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePINEnrollmentChallengesForAccount = `-- name: DeletePINEnrollmentChallengesForAccount :exec
DELETE FROM auth_challenges
WHERE account_id = $1 AND kind = 'pin_enrollment'
`

func (q *Queries) DeletePINEnrollmentChallengesForAccount(ctx context.Context, accountID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePINEnrollmentChallengesForAccount, accountID)
	return err
}

const deletePasswordChallengesForAccount = `-- name: DeletePasswordChallengesForAccount :exec
DELETE FROM auth_challenges
WHERE account_id = $1
  AND kind IN ('invitation', 'email_verification', 'password_reset')
`

func (q *Queries) DeletePasswordChallengesForAccount(ctx context.Context, accountID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePasswordChallengesForAccount, accountID)
	return err
}

const deletePasswordResetForAccount = `-- name: DeletePasswordResetForAccount :exec
DELETE FROM password_reset_tokens WHERE account_id = $1
`

func (q *Queries) DeletePasswordResetForAccount(ctx context.Context, accountID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePasswordResetForAccount, accountID)
	return err
}

const getAccountByPerson = `-- name: GetAccountByPerson :one
SELECT id, person_id, status, version, created_at, updated_at, provisioning_source, first_authenticated_at, administratively_disabled_at FROM accounts WHERE person_id = $1
`

func (q *Queries) GetAccountByPerson(ctx context.Context, personID uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByPerson, personID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProvisioningSource,
		&i.FirstAuthenticatedAt,
		&i.AdministrativelyDisabledAt,
	)
	return i, err
}

const getAccountByPersonForMutation = `-- name: GetAccountByPersonForMutation :one
SELECT id, person_id, status, version, created_at, updated_at, provisioning_source, first_authenticated_at, administratively_disabled_at FROM accounts WHERE person_id = $1 FOR UPDATE
`

func (q *Queries) GetAccountByPersonForMutation(ctx context.Context, personID uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByPersonForMutation, personID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProvisioningSource,
		&i.FirstAuthenticatedAt,
		&i.AdministrativelyDisabledAt,
	)
	return i, err
}

const getAccountForMutation = `-- name: GetAccountForMutation :one
SELECT id, person_id, status, version, created_at, updated_at, provisioning_source, first_authenticated_at, administratively_disabled_at FROM accounts WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetAccountForMutation(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountForMutation, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProvisioningSource,
		&i.FirstAuthenticatedAt,
		&i.AdministrativelyDisabledAt,
	)
	return i, err
}

const getAccountIdentityByLoginEmail = `-- name: GetAccountIdentityByLoginEmail :one
SELECT a.id, a.person_id, a.status, a.version, a.created_at, a.updated_at, a.provisioning_source, a.first_authenticated_at, a.administratively_disabled_at, i.id AS auth_identity_id FROM accounts a
JOIN auth_identities i ON i.account_id = a.id AND i.kind = 'password'
WHERE i.identifier_normalized = $1::text
`

type GetAccountIdentityByLoginEmailRow struct {
	ID                         uuid.UUID
	PersonID                   uuid.UUID
	Status                     string
	Version                    int64
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	ProvisioningSource         string
	FirstAuthenticatedAt       pgtype.Timestamptz
	AdministrativelyDisabledAt pgtype.Timestamptz
	AuthIdentityID             uuid.UUID
}

func (q *Queries) GetAccountIdentityByLoginEmail(ctx context.Context, identifierNormalized string) (GetAccountIdentityByLoginEmailRow, error) {
	row := q.db.QueryRow(ctx, getAccountIdentityByLoginEmail, identifierNormalized)
	var i GetAccountIdentityByLoginEmailRow
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProvisioningSource,
		&i.FirstAuthenticatedAt,
		&i.AdministrativelyDisabledAt,
		&i.AuthIdentityID,
	)
	return i, err
}

const getAccountView = `-- name: GetAccountView :one
SELECT a.id, a.person_id, a.status, a.provisioning_source, a.first_authenticated_at,
       a.version, a.created_at, a.updated_at,
       i.id AS auth_identity_id, i.identifier_display AS login_email,
       CASE WHEN prt.id IS NOT NULL OR pc.reset_required THEN 'reset_required'
            WHEN pc.auth_identity_id IS NULL THEN 'not_set' ELSE 'active' END AS password_status
FROM accounts a
LEFT JOIN auth_identities i ON i.account_id = a.id AND i.kind = 'password'
LEFT JOIN password_credentials pc ON pc.auth_identity_id = i.id
LEFT JOIN password_reset_tokens prt ON prt.account_id = a.id AND prt.expires_at > now()
WHERE a.id = $1
`

type GetAccountViewRow struct {
	ID                   uuid.UUID
	PersonID             uuid.UUID
	Status               string
	ProvisioningSource   string
	FirstAuthenticatedAt pgtype.Timestamptz
	Version              int64
	CreatedAt            time.Time
	UpdatedAt            time.Time
	AuthIdentityID       *uuid.UUID
	LoginEmail           *string
	PasswordStatus       string
}

func (q *Queries) GetAccountView(ctx context.Context, id uuid.UUID) (GetAccountViewRow, error) {
	row := q.db.QueryRow(ctx, getAccountView, id)
	var i GetAccountViewRow
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Status,
		&i.ProvisioningSource,
		&i.FirstAuthenticatedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthIdentityID,
		&i.LoginEmail,
		&i.PasswordStatus,
	)
	return i, err
}

const getIdentityByAccount = `-- name: GetIdentityByAccount :one
SELECT id, account_id, kind, identifier_display, identifier_normalized, created_at, updated_at, provider_id, issuer, subject, verified_at, disabled_at, last_used_at FROM auth_identities WHERE account_id = $1 AND kind = 'password'
`

func (q *Queries) GetIdentityByAccount(ctx context.Context, accountID uuid.UUID) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, getIdentityByAccount, accountID)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Kind,
		&i.IdentifierDisplay,
		&i.IdentifierNormalized,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderID,
		&i.Issuer,
		&i.Subject,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getPasswordIdentityForAccountForUpdate = `-- name: GetPasswordIdentityForAccountForUpdate :one
SELECT id, account_id, kind, identifier_display, identifier_normalized, created_at, updated_at, provider_id, issuer, subject, verified_at, disabled_at, last_used_at FROM auth_identities
WHERE account_id = $1 AND kind = 'password'
FOR UPDATE
`

func (q *Queries) GetPasswordIdentityForAccountForUpdate(ctx context.Context, accountID uuid.UUID) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, getPasswordIdentityForAccountForUpdate, accountID)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Kind,
		&i.IdentifierDisplay,
		&i.IdentifierNormalized,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderID,
		&i.Issuer,
		&i.Subject,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getPersonEmailForAccount = `-- name: GetPersonEmailForAccount :one
SELECT p.email FROM people p JOIN accounts a ON a.person_id = p.id
WHERE a.id = $1
`

func (q *Queries) GetPersonEmailForAccount(ctx context.Context, accountID uuid.UUID) (*string, error) {
	row := q.db.QueryRow(ctx, getPersonEmailForAccount, accountID)
	var email *string
	err := row.Scan(&email)
	return email, err
}

const getPersonVersionForAccountCreation = `-- name: GetPersonVersionForAccountCreation :one
SELECT version FROM people WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetPersonVersionForAccountCreation(ctx context.Context, personID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getPersonVersionForAccountCreation, personID)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const isAccountMaster = `-- name: IsAccountMaster :one
SELECT EXISTS (
    SELECT 1 FROM accounts a
    JOIN person_roles pr ON pr.person_id = a.person_id
    JOIN roles r ON r.id = pr.role_id
    WHERE a.id = $1 AND r.system_key = 'master'
)
`

func (q *Queries) IsAccountMaster(ctx context.Context, accountID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isAccountMaster, accountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAccountViewsByPeople = `-- name: ListAccountViewsByPeople :many
SELECT a.id, a.person_id, a.status, a.provisioning_source, a.first_authenticated_at,
       a.version, a.created_at, a.updated_at,
       i.id AS auth_identity_id, i.identifier_display AS login_email,
       CASE WHEN EXISTS (
                SELECT 1 FROM password_reset_tokens prt
                WHERE prt.account_id = a.id AND prt.expires_at > now()
            ) OR pc.reset_required THEN 'reset_required'
            WHEN pc.auth_identity_id IS NULL THEN 'not_set' ELSE 'active' END AS password_status
FROM accounts a
LEFT JOIN auth_identities i ON i.account_id = a.id AND i.kind = 'password'
LEFT JOIN password_credentials pc ON pc.auth_identity_id = i.id
WHERE a.person_id = ANY($1::uuid[])
ORDER BY a.person_id
`

type ListAccountViewsByPeopleRow struct {
	ID                   uuid.UUID
	PersonID             uuid.UUID
	Status               string
	ProvisioningSource   string
	FirstAuthenticatedAt pgtype.Timestamptz
	Version              int64
	CreatedAt            time.Time
	UpdatedAt            time.Time
	AuthIdentityID       *uuid.UUID
	LoginEmail           *string
	PasswordStatus       string
}

func (q *Queries) ListAccountViewsByPeople(ctx context.Context, personIds []uuid.UUID) ([]ListAccountViewsByPeopleRow, error) {
	rows, err := q.db.Query(ctx, listAccountViewsByPeople, personIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountViewsByPeopleRow{}
	for rows.Next() {
		var i ListAccountViewsByPeopleRow
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.Status,
			&i.ProvisioningSource,
			&i.FirstAuthenticatedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthIdentityID,
			&i.LoginEmail,
			&i.PasswordStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthIdentitiesByAccount = `-- name: ListAuthIdentitiesByAccount :many
SELECT i.id, i.account_id, i.kind, i.identifier_display, i.identifier_normalized, i.created_at, i.updated_at, i.provider_id, i.issuer, i.subject, i.verified_at, i.disabled_at, i.last_used_at, COALESCE(i.identifier_display, p.display_name) AS display_identifier, p.slug AS provider_slug,
       CASE
         WHEN i.disabled_at IS NOT NULL THEN false
         WHEN i.kind = 'password' THEN EXISTS (
           SELECT 1 FROM password_credentials pc WHERE pc.auth_identity_id = i.id AND NOT pc.reset_required
         )
         WHEN i.kind = 'pin' THEN EXISTS (
           SELECT 1 FROM pin_credentials pc WHERE pc.auth_identity_id = i.id
         )
         WHEN i.kind = 'oidc' THEN COALESCE(p.enabled, false)
         ELSE false
       END AS usable
FROM auth_identities i
LEFT JOIN oidc_providers p ON p.id = i.provider_id
WHERE i.account_id = $1
ORDER BY i.kind, i.created_at, i.id
`

type ListAuthIdentitiesByAccountRow struct {
	ID                   uuid.UUID
	AccountID            uuid.UUID
	Kind                 string
	IdentifierDisplay    *string
	IdentifierNormalized *string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	ProviderID           *uuid.UUID
	Issuer               *string
	Subject              *string
	VerifiedAt           pgtype.Timestamptz
	DisabledAt           pgtype.Timestamptz
	LastUsedAt           pgtype.Timestamptz
	DisplayIdentifier    string
	ProviderSlug         *string
	Usable               bool
}

func (q *Queries) ListAuthIdentitiesByAccount(ctx context.Context, accountID uuid.UUID) ([]ListAuthIdentitiesByAccountRow, error) {
	rows, err := q.db.Query(ctx, listAuthIdentitiesByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuthIdentitiesByAccountRow{}
	for rows.Next() {
		var i ListAuthIdentitiesByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Kind,
			&i.IdentifierDisplay,
			&i.IdentifierNormalized,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProviderID,
			&i.Issuer,
			&i.Subject,
			&i.VerifiedAt,
			&i.DisabledAt,
			&i.LastUsedAt,
			&i.DisplayIdentifier,
			&i.ProviderSlug,
			&i.Usable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthIdentitiesByAccounts = `-- name: ListAuthIdentitiesByAccounts :many
SELECT i.id, i.account_id, i.kind, i.identifier_display, i.identifier_normalized, i.created_at, i.updated_at, i.provider_id, i.issuer, i.subject, i.verified_at, i.disabled_at, i.last_used_at, COALESCE(i.identifier_display, p.display_name) AS display_identifier, p.slug AS provider_slug,
       CASE
         WHEN i.disabled_at IS NOT NULL THEN false
         WHEN i.kind = 'password' THEN EXISTS (
           SELECT 1 FROM password_credentials pc WHERE pc.auth_identity_id = i.id AND NOT pc.reset_required
         )
         WHEN i.kind = 'pin' THEN EXISTS (
           SELECT 1 FROM pin_credentials pc WHERE pc.auth_identity_id = i.id
         )
         WHEN i.kind = 'oidc' THEN COALESCE(p.enabled, false)
         ELSE false
       END AS usable
FROM auth_identities i
LEFT JOIN oidc_providers p ON p.id = i.provider_id
WHERE i.account_id = ANY($1::uuid[])
ORDER BY i.account_id, i.kind, i.created_at, i.id
`

type ListAuthIdentitiesByAccountsRow struct {
	ID                   uuid.UUID
	AccountID            uuid.UUID
	Kind                 string
	IdentifierDisplay    *string
	IdentifierNormalized *string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	ProviderID           *uuid.UUID
	Issuer               *string
	Subject              *string
	VerifiedAt           pgtype.Timestamptz
	DisabledAt           pgtype.Timestamptz
	LastUsedAt           pgtype.Timestamptz
	DisplayIdentifier    string
	ProviderSlug         *string
	Usable               bool
}

func (q *Queries) ListAuthIdentitiesByAccounts(ctx context.Context, accountIds []uuid.UUID) ([]ListAuthIdentitiesByAccountsRow, error) {
	rows, err := q.db.Query(ctx, listAuthIdentitiesByAccounts, accountIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuthIdentitiesByAccountsRow{}
	for rows.Next() {
		var i ListAuthIdentitiesByAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Kind,
			&i.IdentifierDisplay,
			&i.IdentifierNormalized,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProviderID,
			&i.Issuer,
			&i.Subject,
			&i.VerifiedAt,
			&i.DisabledAt,
			&i.LastUsedAt,
			&i.DisplayIdentifier,
			&i.ProviderSlug,
			&i.Usable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPersonForAccountMutation = `-- name: LockPersonForAccountMutation :one
SELECT p.id
FROM people p
JOIN accounts a ON a.person_id = p.id
WHERE a.id = $1
FOR UPDATE OF p
`

func (q *Queries) LockPersonForAccountMutation(ctx context.Context, accountID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockPersonForAccountMutation, accountID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const markInvitationProvisioning = `-- name: MarkInvitationProvisioning :exec
UPDATE accounts SET provisioning_source = 'invitation'
WHERE id = $1 AND first_authenticated_at IS NULL AND provisioning_source = 'local'
`

func (q *Queries) MarkInvitationProvisioning(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markInvitationProvisioning, id)
	return err
}

const markPasswordResetRequired = `-- name: MarkPasswordResetRequired :exec
UPDATE password_credentials SET reset_required = true, changed_at = now()
WHERE auth_identity_id = $1
`

func (q *Queries) MarkPasswordResetRequired(ctx context.Context, authIdentityID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPasswordResetRequired, authIdentityID)
	return err
}

const recoverAccount = `-- name: RecoverAccount :one
UPDATE accounts SET status = 'enabled', version = version + 1, updated_at = now()
WHERE id = $1 RETURNING id, person_id, status, version, created_at, updated_at, provisioning_source, first_authenticated_at, administratively_disabled_at
`

func (q *Queries) RecoverAccount(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, recoverAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProvisioningSource,
		&i.FirstAuthenticatedAt,
		&i.AdministrativelyDisabledAt,
	)
	return i, err
}

const restorePasswordIdentity = `-- name: RestorePasswordIdentity :exec
UPDATE auth_identities
SET disabled_at = NULL, verified_at = COALESCE(verified_at, now()), updated_at = now()
WHERE id = $1 AND kind = 'password'
`

func (q *Queries) RestorePasswordIdentity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restorePasswordIdentity, id)
	return err
}

const revokeSessionsForAccount = `-- name: RevokeSessionsForAccount :exec
UPDATE sessions
SET revoked_at = COALESCE(revoked_at, now()), revocation_reason = COALESCE(revocation_reason, $1)
WHERE account_id = $2 AND revoked_at IS NULL
`

type RevokeSessionsForAccountParams struct {
	Reason    *string
	AccountID uuid.UUID
}

func (q *Queries) RevokeSessionsForAccount(ctx context.Context, arg RevokeSessionsForAccountParams) error {
	_, err := q.db.Exec(ctx, revokeSessionsForAccount, arg.Reason, arg.AccountID)
	return err
}

const setAuthChallengeDelivery = `-- name: SetAuthChallengeDelivery :exec
UPDATE auth_challenges
SET delivery_status = $1, delivery_attempted_at = now(), delivery_failure_code = $2
WHERE id = $3 AND delivery_status = 'pending'
`

type SetAuthChallengeDeliveryParams struct {
	DeliveryStatus      string
	DeliveryFailureCode *string
	ID                  uuid.UUID
}

func (q *Queries) SetAuthChallengeDelivery(ctx context.Context, arg SetAuthChallengeDeliveryParams) error {
	_, err := q.db.Exec(ctx, setAuthChallengeDelivery, arg.DeliveryStatus, arg.DeliveryFailureCode, arg.ID)
	return err
}

const updateAccountStatus = `-- name: UpdateAccountStatus :one
UPDATE accounts SET status = $1,
    administratively_disabled_at = CASE WHEN $1::text = 'disabled' THEN now() ELSE NULL END,
    version = version + 1, updated_at = now()
WHERE id = $2 AND version = $3 RETURNING id, person_id, status, version, created_at, updated_at, provisioning_source, first_authenticated_at, administratively_disabled_at
`

type UpdateAccountStatusParams struct {
	Status          string
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountStatus, arg.Status, arg.ID, arg.ExpectedVersion)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProvisioningSource,
		&i.FirstAuthenticatedAt,
		&i.AdministrativelyDisabledAt,
	)
	return i, err
}

const updateLoginEmail = `-- name: UpdateLoginEmail :one
UPDATE auth_identities SET identifier_display = $1::text,
    identifier_normalized = $2::text,
    verified_at = CASE WHEN identifier_normalized = $2::text THEN verified_at ELSE NULL END,
    updated_at = now()
WHERE account_id = $3 AND kind = 'password' RETURNING id, account_id, kind, identifier_display, identifier_normalized, created_at, updated_at, provider_id, issuer, subject, verified_at, disabled_at, last_used_at
`

type UpdateLoginEmailParams struct {
	IdentifierDisplay    string
	IdentifierNormalized string
	AccountID            uuid.UUID
}

func (q *Queries) UpdateLoginEmail(ctx context.Context, arg UpdateLoginEmailParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, updateLoginEmail, arg.IdentifierDisplay, arg.IdentifierNormalized, arg.AccountID)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Kind,
		&i.IdentifierDisplay,
		&i.IdentifierNormalized,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderID,
		&i.Issuer,
		&i.Subject,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.LastUsedAt,
	)
	return i, err
}

const upsertAuthChallenge = `-- name: UpsertAuthChallenge :one
INSERT INTO auth_challenges (
    id, kind, account_id, auth_identity_id, code_digest, delivery_address,
    created_by_account_id, expires_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
ON CONFLICT (account_id, kind) DO UPDATE SET
    id = EXCLUDED.id, auth_identity_id = EXCLUDED.auth_identity_id,
    code_digest = EXCLUDED.code_digest, delivery_address = EXCLUDED.delivery_address,
    attempt_count = 0, created_by_account_id = EXCLUDED.created_by_account_id,
    expires_at = EXCLUDED.expires_at, used_at = NULL, cancelled_at = NULL,
    delivery_status = 'pending', delivery_attempted_at = NULL,
    delivery_failure_code = NULL, created_at = now()
RETURNING id, kind, account_id, auth_identity_id, code_digest, delivery_address, attempt_count, created_by_account_id, expires_at, used_at, cancelled_at, delivery_status, delivery_attempted_at, delivery_failure_code, created_at
`

type UpsertAuthChallengeParams struct {
	ID                 uuid.UUID
	Kind               string
	AccountID          uuid.UUID
	AuthIdentityID     *uuid.UUID
	CodeDigest         []byte
	DeliveryAddress    *string
	CreatedByAccountID *uuid.UUID
	ExpiresAt          time.Time
}

func (q *Queries) UpsertAuthChallenge(ctx context.Context, arg UpsertAuthChallengeParams) (AuthChallenge, error) {
	row := q.db.QueryRow(ctx, upsertAuthChallenge,
		arg.ID,
		arg.Kind,
		arg.AccountID,
		arg.AuthIdentityID,
		arg.CodeDigest,
		arg.DeliveryAddress,
		arg.CreatedByAccountID,
		arg.ExpiresAt,
	)
	var i AuthChallenge
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.AccountID,
		&i.AuthIdentityID,
		&i.CodeDigest,
		&i.DeliveryAddress,
		&i.AttemptCount,
		&i.CreatedByAccountID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CancelledAt,
		&i.DeliveryStatus,
		&i.DeliveryAttemptedAt,
		&i.DeliveryFailureCode,
		&i.CreatedAt,
	)
	return i, err
}

const upsertPasswordCredential = `-- name: UpsertPasswordCredential :exec
INSERT INTO password_credentials (auth_identity_id, password_hash, reset_required, changed_at)
VALUES ($1, $2, false, now())
ON CONFLICT (auth_identity_id) DO UPDATE
SET password_hash = EXCLUDED.password_hash, reset_required = false, changed_at = now()
`

type UpsertPasswordCredentialParams struct {
	AuthIdentityID uuid.UUID
	PasswordHash   string
}

func (q *Queries) UpsertPasswordCredential(ctx context.Context, arg UpsertPasswordCredentialParams) error {
	_, err := q.db.Exec(ctx, upsertPasswordCredential, arg.AuthIdentityID, arg.PasswordHash)
	return err
}

const verifyPasswordIdentity = `-- name: VerifyPasswordIdentity :exec
UPDATE auth_identities
SET verified_at = COALESCE(verified_at, now()), disabled_at = NULL, updated_at = now()
WHERE id = $1 AND kind = 'password'
`

func (q *Queries) VerifyPasswordIdentity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, verifyPasswordIdentity, id)
	return err
}
