// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package accountsdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AcquireMasterInvariantLock(ctx context.Context) error
	AssignAccountRole(ctx context.Context, arg AssignAccountRoleParams) (int64, error)
	BumpAccountVersion(ctx context.Context, arg BumpAccountVersionParams) (Account, error)
	CountEnabledMasters(ctx context.Context) (int64, error)
	CountMasterAssignments(ctx context.Context) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateAuthIdentity(ctx context.Context, arg CreateAuthIdentityParams) (AuthIdentity, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error)
	DeleteAccount(ctx context.Context, arg DeleteAccountParams) (uuid.UUID, error)
	DeletePasswordResetForAccount(ctx context.Context, accountID uuid.UUID) error
	GetAccountByPerson(ctx context.Context, personID uuid.UUID) (Account, error)
	GetAccountByPersonForMutation(ctx context.Context, personID uuid.UUID) (Account, error)
	GetAccountForMutation(ctx context.Context, id uuid.UUID) (Account, error)
	GetAccountIdentityByLoginEmail(ctx context.Context, identifierNormalized string) (GetAccountIdentityByLoginEmailRow, error)
	GetAccountView(ctx context.Context, id uuid.UUID) (GetAccountViewRow, error)
	GetIdentityByAccount(ctx context.Context, accountID uuid.UUID) (AuthIdentity, error)
	GetMasterRole(ctx context.Context) (Role, error)
	GetPersonVersionForAccountCreation(ctx context.Context, personID uuid.UUID) (int64, error)
	GetRoleForAssignment(ctx context.Context, id uuid.UUID) (Role, error)
	GetRolePermissionGrantsForAssignment(ctx context.Context, roleID uuid.UUID) ([]GetRolePermissionGrantsForAssignmentRow, error)
	IsAccountMaster(ctx context.Context, accountID uuid.UUID) (bool, error)
	IsAccountRoleAssigned(ctx context.Context, arg IsAccountRoleAssignedParams) (bool, error)
	ListAccountRoles(ctx context.Context, accountID uuid.UUID) ([]Role, error)
	LockMasterRole(ctx context.Context) (uuid.UUID, error)
	MarkPasswordResetRequired(ctx context.Context, authIdentityID uuid.UUID) error
	RecoverAccount(ctx context.Context, id uuid.UUID) (Account, error)
	RemoveAccountRole(ctx context.Context, arg RemoveAccountRoleParams) (int64, error)
	RevokeSessionsForAccount(ctx context.Context, arg RevokeSessionsForAccountParams) error
	UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) (Account, error)
	UpdateLoginEmail(ctx context.Context, arg UpdateLoginEmailParams) (AuthIdentity, error)
	UpsertPasswordCredential(ctx context.Context, arg UpsertPasswordCredentialParams) error
}

var _ Querier = (*Queries)(nil)
