// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package accountsdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acquireMasterInvariantLock = `-- name: AcquireMasterInvariantLock :exec
SELECT pg_advisory_xact_lock(5577006791947779410)
`

func (q *Queries) AcquireMasterInvariantLock(ctx context.Context) error {
	_, err := q.db.Exec(ctx, acquireMasterInvariantLock)
	return err
}

const assignAccountRole = `-- name: AssignAccountRole :execrows
INSERT INTO account_roles (account_id, role_id, assigned_by_account_id)
VALUES ($1, $2, $3)
ON CONFLICT (account_id, role_id) DO NOTHING
`

type AssignAccountRoleParams struct {
	AccountID           uuid.UUID
	RoleID              uuid.UUID
	AssignedByAccountID *uuid.UUID
}

func (q *Queries) AssignAccountRole(ctx context.Context, arg AssignAccountRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, assignAccountRole, arg.AccountID, arg.RoleID, arg.AssignedByAccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bumpAccountVersion = `-- name: BumpAccountVersion :one
UPDATE accounts SET version = version + 1, updated_at = now()
WHERE id = $1 AND version = $2 RETURNING id, person_id, status, version, created_at, updated_at
`

type BumpAccountVersionParams struct {
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) BumpAccountVersion(ctx context.Context, arg BumpAccountVersionParams) (Account, error) {
	row := q.db.QueryRow(ctx, bumpAccountVersion, arg.ID, arg.ExpectedVersion)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countEnabledMasters = `-- name: CountEnabledMasters :one
SELECT count(*) FROM accounts a
JOIN account_roles ar ON ar.account_id = a.id JOIN roles r ON r.id = ar.role_id
WHERE a.status = 'enabled' AND r.system_key = 'master'
`

func (q *Queries) CountEnabledMasters(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEnabledMasters)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMasterAssignments = `-- name: CountMasterAssignments :one
SELECT count(*) FROM account_roles ar JOIN roles r ON r.id = ar.role_id WHERE r.system_key = 'master'
`

func (q *Queries) CountMasterAssignments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMasterAssignments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (id, person_id, status)
VALUES ($1, $2, $3) RETURNING id, person_id, status, version, created_at, updated_at
`

type CreateAccountParams struct {
	ID       uuid.UUID
	PersonID uuid.UUID
	Status   string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.ID, arg.PersonID, arg.Status)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAuthIdentity = `-- name: CreateAuthIdentity :one
INSERT INTO auth_identities (id, account_id, kind, identifier_display, identifier_normalized)
VALUES ($1, $2, 'email_password', $3, $4)
RETURNING id, account_id, kind, identifier_display, identifier_normalized, created_at, updated_at
`

type CreateAuthIdentityParams struct {
	ID                   uuid.UUID
	AccountID            uuid.UUID
	IdentifierDisplay    string
	IdentifierNormalized string
}

func (q *Queries) CreateAuthIdentity(ctx context.Context, arg CreateAuthIdentityParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, createAuthIdentity,
		arg.ID,
		arg.AccountID,
		arg.IdentifierDisplay,
		arg.IdentifierNormalized,
	)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Kind,
		&i.IdentifierDisplay,
		&i.IdentifierNormalized,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (id, account_id, token_digest, created_by_account_id, expires_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (account_id) DO UPDATE SET id = EXCLUDED.id, token_digest = EXCLUDED.token_digest,
    created_by_account_id = EXCLUDED.created_by_account_id, created_at = now(), expires_at = EXCLUDED.expires_at
RETURNING id, account_id, token_digest, created_by_account_id, created_at, expires_at
`

type CreatePasswordResetTokenParams struct {
	ID                 uuid.UUID
	AccountID          uuid.UUID
	TokenDigest        []byte
	CreatedByAccountID *uuid.UUID
	ExpiresAt          time.Time
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken,
		arg.ID,
		arg.AccountID,
		arg.TokenDigest,
		arg.CreatedByAccountID,
		arg.ExpiresAt,
	)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenDigest,
		&i.CreatedByAccountID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :one
DELETE FROM accounts WHERE id = $1 AND version = $2 RETURNING id
`

type DeleteAccountParams struct {
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) DeleteAccount(ctx context.Context, arg DeleteAccountParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteAccount, arg.ID, arg.ExpectedVersion)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deletePasswordResetForAccount = `-- name: DeletePasswordResetForAccount :exec
DELETE FROM password_reset_tokens WHERE account_id = $1
`

func (q *Queries) DeletePasswordResetForAccount(ctx context.Context, accountID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePasswordResetForAccount, accountID)
	return err
}

const getAccountByPerson = `-- name: GetAccountByPerson :one
SELECT id, person_id, status, version, created_at, updated_at FROM accounts WHERE person_id = $1
`

func (q *Queries) GetAccountByPerson(ctx context.Context, personID uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByPerson, personID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByPersonForMutation = `-- name: GetAccountByPersonForMutation :one
SELECT id, person_id, status, version, created_at, updated_at FROM accounts WHERE person_id = $1 FOR UPDATE
`

func (q *Queries) GetAccountByPersonForMutation(ctx context.Context, personID uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByPersonForMutation, personID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountForMutation = `-- name: GetAccountForMutation :one
SELECT id, person_id, status, version, created_at, updated_at FROM accounts WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetAccountForMutation(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountForMutation, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountIdentityByLoginEmail = `-- name: GetAccountIdentityByLoginEmail :one
SELECT a.id, a.person_id, a.status, a.version, a.created_at, a.updated_at, i.id AS auth_identity_id FROM accounts a
JOIN auth_identities i ON i.account_id = a.id AND i.kind = 'email_password'
WHERE i.identifier_normalized = $1
`

type GetAccountIdentityByLoginEmailRow struct {
	ID             uuid.UUID
	PersonID       uuid.UUID
	Status         string
	Version        int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
	AuthIdentityID uuid.UUID
}

func (q *Queries) GetAccountIdentityByLoginEmail(ctx context.Context, identifierNormalized string) (GetAccountIdentityByLoginEmailRow, error) {
	row := q.db.QueryRow(ctx, getAccountIdentityByLoginEmail, identifierNormalized)
	var i GetAccountIdentityByLoginEmailRow
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthIdentityID,
	)
	return i, err
}

const getAccountView = `-- name: GetAccountView :one
SELECT a.id, a.person_id, a.status, a.version, a.created_at, a.updated_at,
       i.id AS auth_identity_id, i.identifier_display AS login_email,
       CASE WHEN prt.id IS NOT NULL OR pc.reset_required THEN 'reset_required'
            WHEN pc.auth_identity_id IS NULL THEN 'not_set' ELSE 'active' END AS password_status
FROM accounts a
JOIN auth_identities i ON i.account_id = a.id AND i.kind = 'email_password'
LEFT JOIN password_credentials pc ON pc.auth_identity_id = i.id
LEFT JOIN password_reset_tokens prt ON prt.account_id = a.id AND prt.expires_at > now()
WHERE a.id = $1
`

type GetAccountViewRow struct {
	ID             uuid.UUID
	PersonID       uuid.UUID
	Status         string
	Version        int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
	AuthIdentityID uuid.UUID
	LoginEmail     string
	PasswordStatus string
}

func (q *Queries) GetAccountView(ctx context.Context, id uuid.UUID) (GetAccountViewRow, error) {
	row := q.db.QueryRow(ctx, getAccountView, id)
	var i GetAccountViewRow
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthIdentityID,
		&i.LoginEmail,
		&i.PasswordStatus,
	)
	return i, err
}

const getIdentityByAccount = `-- name: GetIdentityByAccount :one
SELECT id, account_id, kind, identifier_display, identifier_normalized, created_at, updated_at FROM auth_identities WHERE account_id = $1 AND kind = 'email_password'
`

func (q *Queries) GetIdentityByAccount(ctx context.Context, accountID uuid.UUID) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, getIdentityByAccount, accountID)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Kind,
		&i.IdentifierDisplay,
		&i.IdentifierNormalized,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMasterRole = `-- name: GetMasterRole :one
SELECT id, name, description, system_key, version, created_at, updated_at FROM roles WHERE system_key = 'master'
`

func (q *Queries) GetMasterRole(ctx context.Context) (Role, error) {
	row := q.db.QueryRow(ctx, getMasterRole)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SystemKey,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPersonVersionForAccountCreation = `-- name: GetPersonVersionForAccountCreation :one
SELECT version FROM people WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetPersonVersionForAccountCreation(ctx context.Context, personID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getPersonVersionForAccountCreation, personID)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const getRoleForAssignment = `-- name: GetRoleForAssignment :one
SELECT id, name, description, system_key, version, created_at, updated_at FROM roles WHERE id = $1 FOR SHARE
`

func (q *Queries) GetRoleForAssignment(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleForAssignment, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SystemKey,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRolePermissionsForAssignment = `-- name: GetRolePermissionsForAssignment :many
SELECT permission_id FROM role_permissions WHERE role_id = $1 ORDER BY permission_id
`

func (q *Queries) GetRolePermissionsForAssignment(ctx context.Context, roleID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getRolePermissionsForAssignment, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var permission_id string
		if err := rows.Scan(&permission_id); err != nil {
			return nil, err
		}
		items = append(items, permission_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isAccountMaster = `-- name: IsAccountMaster :one
SELECT EXISTS (SELECT 1 FROM account_roles ar JOIN roles r ON r.id = ar.role_id
WHERE ar.account_id = $1 AND r.system_key = 'master')
`

func (q *Queries) IsAccountMaster(ctx context.Context, accountID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isAccountMaster, accountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isAccountRoleAssigned = `-- name: IsAccountRoleAssigned :one
SELECT EXISTS (SELECT 1 FROM account_roles WHERE account_id = $1 AND role_id = $2)
`

type IsAccountRoleAssignedParams struct {
	AccountID uuid.UUID
	RoleID    uuid.UUID
}

func (q *Queries) IsAccountRoleAssigned(ctx context.Context, arg IsAccountRoleAssignedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isAccountRoleAssigned, arg.AccountID, arg.RoleID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAccountRoles = `-- name: ListAccountRoles :many
SELECT r.id, r.name, r.description, r.system_key, r.version, r.created_at, r.updated_at FROM roles r JOIN account_roles ar ON ar.role_id = r.id
WHERE ar.account_id = $1
ORDER BY r.system_key DESC NULLS LAST, lower(r.name), r.id
`

func (q *Queries) ListAccountRoles(ctx context.Context, accountID uuid.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, listAccountRoles, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SystemKey,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMasterRole = `-- name: LockMasterRole :one
SELECT id FROM roles WHERE system_key = 'master' FOR UPDATE
`

func (q *Queries) LockMasterRole(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockMasterRole)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const markPasswordResetRequired = `-- name: MarkPasswordResetRequired :exec
UPDATE password_credentials SET reset_required = true, changed_at = now()
WHERE auth_identity_id = $1
`

func (q *Queries) MarkPasswordResetRequired(ctx context.Context, authIdentityID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPasswordResetRequired, authIdentityID)
	return err
}

const recoverAccount = `-- name: RecoverAccount :one
UPDATE accounts SET status = 'enabled', version = version + 1, updated_at = now()
WHERE id = $1 RETURNING id, person_id, status, version, created_at, updated_at
`

func (q *Queries) RecoverAccount(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, recoverAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const removeAccountRole = `-- name: RemoveAccountRole :execrows
DELETE FROM account_roles WHERE account_id = $1 AND role_id = $2
`

type RemoveAccountRoleParams struct {
	AccountID uuid.UUID
	RoleID    uuid.UUID
}

func (q *Queries) RemoveAccountRole(ctx context.Context, arg RemoveAccountRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeAccountRole, arg.AccountID, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSessionsForAccount = `-- name: RevokeSessionsForAccount :exec
UPDATE sessions
SET revoked_at = COALESCE(revoked_at, now()), revocation_reason = COALESCE(revocation_reason, $1)
WHERE account_id = $2 AND revoked_at IS NULL
`

type RevokeSessionsForAccountParams struct {
	Reason    *string
	AccountID uuid.UUID
}

func (q *Queries) RevokeSessionsForAccount(ctx context.Context, arg RevokeSessionsForAccountParams) error {
	_, err := q.db.Exec(ctx, revokeSessionsForAccount, arg.Reason, arg.AccountID)
	return err
}

const updateAccountStatus = `-- name: UpdateAccountStatus :one
UPDATE accounts SET status = $1, version = version + 1, updated_at = now()
WHERE id = $2 AND version = $3 RETURNING id, person_id, status, version, created_at, updated_at
`

type UpdateAccountStatusParams struct {
	Status          string
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountStatus, arg.Status, arg.ID, arg.ExpectedVersion)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLoginEmail = `-- name: UpdateLoginEmail :one
UPDATE auth_identities SET identifier_display = $1,
    identifier_normalized = $2, updated_at = now()
WHERE account_id = $3 AND kind = 'email_password' RETURNING id, account_id, kind, identifier_display, identifier_normalized, created_at, updated_at
`

type UpdateLoginEmailParams struct {
	IdentifierDisplay    string
	IdentifierNormalized string
	AccountID            uuid.UUID
}

func (q *Queries) UpdateLoginEmail(ctx context.Context, arg UpdateLoginEmailParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, updateLoginEmail, arg.IdentifierDisplay, arg.IdentifierNormalized, arg.AccountID)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Kind,
		&i.IdentifierDisplay,
		&i.IdentifierNormalized,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPasswordCredential = `-- name: UpsertPasswordCredential :exec
INSERT INTO password_credentials (auth_identity_id, password_hash, reset_required, changed_at)
VALUES ($1, $2, false, now())
ON CONFLICT (auth_identity_id) DO UPDATE
SET password_hash = EXCLUDED.password_hash, reset_required = false, changed_at = now()
`

type UpsertPasswordCredentialParams struct {
	AuthIdentityID uuid.UUID
	PasswordHash   string
}

func (q *Queries) UpsertPasswordCredential(ctx context.Context, arg UpsertPasswordCredentialParams) error {
	_, err := q.db.Exec(ctx, upsertPasswordCredential, arg.AuthIdentityID, arg.PasswordHash)
	return err
}
