// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package supervisorsdb

import (
	"context"
)

type Querier interface {
	ListOpenPeriods(ctx context.Context) ([]ListOpenPeriodsRow, error)
	ListSupervisorAssignmentCounts(ctx context.Context) ([]ListSupervisorAssignmentCountsRow, error)
	ListSupervisors(ctx context.Context) ([]ListSupervisorsRow, error)
}

var _ Querier = (*Queries)(nil)
