// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package surveysdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelSurveyInvitationsForSurvey = `-- name: CancelSurveyInvitationsForSurvey :execrows
UPDATE survey_invitations si SET status = 'cancelled', person_id = NULL, visit_id = NULL,
  recipient_email = NULL, delivery_claimed_at = NULL
FROM survey_versions sv
WHERE si.survey_version_id = sv.id AND sv.survey_id = $1
  AND si.status IN ('pending', 'delivering', 'sent', 'failed')
`

func (q *Queries) CancelSurveyInvitationsForSurvey(ctx context.Context, surveyID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelSurveyInvitationsForSurvey, surveyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelSurveyInvitationsForVisit = `-- name: CancelSurveyInvitationsForVisit :execrows
UPDATE survey_invitations SET status = 'cancelled', person_id = NULL, visit_id = NULL,
  recipient_email = NULL, delivery_claimed_at = NULL
WHERE visit_id = $1 AND status IN ('pending', 'delivering', 'sent', 'failed')
`

func (q *Queries) CancelSurveyInvitationsForVisit(ctx context.Context, visitID *uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelSurveyInvitationsForVisit, visitID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimDueSurveyInvitations = `-- name: ClaimDueSurveyInvitations :many
WITH candidates AS (
  SELECT si.id FROM survey_invitations si
  WHERE (si.status IN ('pending', 'failed') OR (si.status = 'delivering' AND si.delivery_claimed_at < now() - interval '15 minutes'))
    AND si.due_at <= now() AND si.expires_at > now() AND si.delivery_attempts < 5 AND si.recipient_email IS NOT NULL
  ORDER BY si.due_at, si.id LIMIT $1
  FOR UPDATE OF si SKIP LOCKED
), claimed AS (
  UPDATE survey_invitations si SET status = 'delivering', delivery_claimed_at = now(),
    delivery_attempts = delivery_attempts + 1
  FROM candidates c WHERE si.id = c.id RETURNING si.id, si.survey_version_id, si.person_id, si.visit_id, si.token_digest, si.recipient_email, si.status, si.due_at, si.expires_at, si.sent_at, si.redeemed_at, si.delivery_attempts, si.delivery_claimed_at, si.delivery_failure_code, si.created_at
)
SELECT claimed.id, claimed.survey_version_id, claimed.person_id, claimed.visit_id, claimed.token_digest, claimed.recipient_email, claimed.status, claimed.due_at, claimed.expires_at, claimed.sent_at, claimed.redeemed_at, claimed.delivery_attempts, claimed.delivery_claimed_at, claimed.delivery_failure_code, claimed.created_at, sv.title, s.name AS survey_name
FROM claimed
JOIN survey_versions sv ON sv.id = claimed.survey_version_id
JOIN surveys s ON s.id = sv.survey_id
ORDER BY claimed.due_at, claimed.id
`

type ClaimDueSurveyInvitationsRow struct {
	ID                  uuid.UUID
	SurveyVersionID     uuid.UUID
	PersonID            *uuid.UUID
	VisitID             *uuid.UUID
	TokenDigest         []byte
	RecipientEmail      *string
	Status              string
	DueAt               time.Time
	ExpiresAt           time.Time
	SentAt              pgtype.Timestamptz
	RedeemedAt          pgtype.Timestamptz
	DeliveryAttempts    int32
	DeliveryClaimedAt   pgtype.Timestamptz
	DeliveryFailureCode *string
	CreatedAt           time.Time
	Title               string
	SurveyName          string
}

func (q *Queries) ClaimDueSurveyInvitations(ctx context.Context, pageLimit int32) ([]ClaimDueSurveyInvitationsRow, error) {
	rows, err := q.db.Query(ctx, claimDueSurveyInvitations, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimDueSurveyInvitationsRow{}
	for rows.Next() {
		var i ClaimDueSurveyInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.SurveyVersionID,
			&i.PersonID,
			&i.VisitID,
			&i.TokenDigest,
			&i.RecipientEmail,
			&i.Status,
			&i.DueAt,
			&i.ExpiresAt,
			&i.SentAt,
			&i.RedeemedAt,
			&i.DeliveryAttempts,
			&i.DeliveryClaimedAt,
			&i.DeliveryFailureCode,
			&i.CreatedAt,
			&i.Title,
			&i.SurveyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const closeSurvey = `-- name: CloseSurvey :one
UPDATE surveys SET status = 'closed', version = version + 1, updated_at = now()
WHERE id = $1 AND version = $2 AND status = 'published' RETURNING id, name, description, status, anonymous, version, created_at, updated_at
`

type CloseSurveyParams struct {
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) CloseSurvey(ctx context.Context, arg CloseSurveyParams) (Survey, error) {
	row := q.db.QueryRow(ctx, closeSurvey, arg.ID, arg.ExpectedVersion)
	var i Survey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Anonymous,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const consumeSurveyInvitation = `-- name: ConsumeSurveyInvitation :execrows
UPDATE survey_invitations SET status = 'redeemed', redeemed_at = now(),
  person_id = NULL, visit_id = NULL, recipient_email = NULL
WHERE id = $1 AND status IN ('pending', 'sent', 'failed') AND expires_at > now()
`

func (q *Queries) ConsumeSurveyInvitation(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, consumeSurveyInvitation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createSurvey = `-- name: CreateSurvey :one
INSERT INTO surveys (id, name, description, anonymous)
VALUES ($1, $2, $3, $4) RETURNING id, name, description, status, anonymous, version, created_at, updated_at
`

type CreateSurveyParams struct {
	ID          uuid.UUID
	Name        string
	Description *string
	Anonymous   bool
}

func (q *Queries) CreateSurvey(ctx context.Context, arg CreateSurveyParams) (Survey, error) {
	row := q.db.QueryRow(ctx, createSurvey,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Anonymous,
	)
	var i Survey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Anonymous,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSurveyAnswer = `-- name: CreateSurveyAnswer :exec
INSERT INTO survey_answers (id, response_id, question_id, option_id, text_value, numeric_value, boolean_value, position)
VALUES ($1, $2, $3, $4,
  $5, $6, $7, $8)
`

type CreateSurveyAnswerParams struct {
	ID           uuid.UUID
	ResponseID   uuid.UUID
	QuestionID   uuid.UUID
	OptionID     *uuid.UUID
	TextValue    *string
	NumericValue *int32
	BooleanValue *bool
	Position     int32
}

func (q *Queries) CreateSurveyAnswer(ctx context.Context, arg CreateSurveyAnswerParams) error {
	_, err := q.db.Exec(ctx, createSurveyAnswer,
		arg.ID,
		arg.ResponseID,
		arg.QuestionID,
		arg.OptionID,
		arg.TextValue,
		arg.NumericValue,
		arg.BooleanValue,
		arg.Position,
	)
	return err
}

const createSurveyInvitation = `-- name: CreateSurveyInvitation :one
INSERT INTO survey_invitations (id, survey_version_id, person_id, visit_id, token_digest,
  recipient_email, due_at, expires_at)
VALUES ($1, $2, $3, $4,
  $5, $6, $7, $8)
RETURNING id, survey_version_id, person_id, visit_id, token_digest, recipient_email, status, due_at, expires_at, sent_at, redeemed_at, delivery_attempts, delivery_claimed_at, delivery_failure_code, created_at
`

type CreateSurveyInvitationParams struct {
	ID              uuid.UUID
	SurveyVersionID uuid.UUID
	PersonID        *uuid.UUID
	VisitID         *uuid.UUID
	TokenDigest     []byte
	RecipientEmail  *string
	DueAt           time.Time
	ExpiresAt       time.Time
}

func (q *Queries) CreateSurveyInvitation(ctx context.Context, arg CreateSurveyInvitationParams) (SurveyInvitation, error) {
	row := q.db.QueryRow(ctx, createSurveyInvitation,
		arg.ID,
		arg.SurveyVersionID,
		arg.PersonID,
		arg.VisitID,
		arg.TokenDigest,
		arg.RecipientEmail,
		arg.DueAt,
		arg.ExpiresAt,
	)
	var i SurveyInvitation
	err := row.Scan(
		&i.ID,
		&i.SurveyVersionID,
		&i.PersonID,
		&i.VisitID,
		&i.TokenDigest,
		&i.RecipientEmail,
		&i.Status,
		&i.DueAt,
		&i.ExpiresAt,
		&i.SentAt,
		&i.RedeemedAt,
		&i.DeliveryAttempts,
		&i.DeliveryClaimedAt,
		&i.DeliveryFailureCode,
		&i.CreatedAt,
	)
	return i, err
}

const createSurveyOption = `-- name: CreateSurveyOption :one
INSERT INTO survey_question_options (id, question_id, label, position)
VALUES ($1, $2, $3, $4) RETURNING id, question_id, label, position
`

type CreateSurveyOptionParams struct {
	ID         uuid.UUID
	QuestionID uuid.UUID
	Label      string
	Position   int32
}

func (q *Queries) CreateSurveyOption(ctx context.Context, arg CreateSurveyOptionParams) (SurveyQuestionOption, error) {
	row := q.db.QueryRow(ctx, createSurveyOption,
		arg.ID,
		arg.QuestionID,
		arg.Label,
		arg.Position,
	)
	var i SurveyQuestionOption
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Label,
		&i.Position,
	)
	return i, err
}

const createSurveyQuestion = `-- name: CreateSurveyQuestion :one
INSERT INTO survey_questions (id, survey_version_id, kind, prompt, required, position, rating_min, rating_max)
VALUES ($1, $2, $3, $4, $5,
  $6, $7, $8) RETURNING id, survey_version_id, kind, prompt, required, position, rating_min, rating_max
`

type CreateSurveyQuestionParams struct {
	ID              uuid.UUID
	SurveyVersionID uuid.UUID
	Kind            string
	Prompt          string
	Required        bool
	Position        int32
	RatingMin       *int32
	RatingMax       *int32
}

func (q *Queries) CreateSurveyQuestion(ctx context.Context, arg CreateSurveyQuestionParams) (SurveyQuestion, error) {
	row := q.db.QueryRow(ctx, createSurveyQuestion,
		arg.ID,
		arg.SurveyVersionID,
		arg.Kind,
		arg.Prompt,
		arg.Required,
		arg.Position,
		arg.RatingMin,
		arg.RatingMax,
	)
	var i SurveyQuestion
	err := row.Scan(
		&i.ID,
		&i.SurveyVersionID,
		&i.Kind,
		&i.Prompt,
		&i.Required,
		&i.Position,
		&i.RatingMin,
		&i.RatingMax,
	)
	return i, err
}

const createSurveyResponse = `-- name: CreateSurveyResponse :one
INSERT INTO survey_responses (id, survey_version_id, submitted_on, identified_person_id)
VALUES ($1, $2, $3, $4) RETURNING id, survey_version_id, submitted_on, identified_person_id
`

type CreateSurveyResponseParams struct {
	ID                 uuid.UUID
	SurveyVersionID    uuid.UUID
	SubmittedOn        pgtype.Date
	IdentifiedPersonID *uuid.UUID
}

func (q *Queries) CreateSurveyResponse(ctx context.Context, arg CreateSurveyResponseParams) (SurveyResponse, error) {
	row := q.db.QueryRow(ctx, createSurveyResponse,
		arg.ID,
		arg.SurveyVersionID,
		arg.SubmittedOn,
		arg.IdentifiedPersonID,
	)
	var i SurveyResponse
	err := row.Scan(
		&i.ID,
		&i.SurveyVersionID,
		&i.SubmittedOn,
		&i.IdentifiedPersonID,
	)
	return i, err
}

const createSurveyTrigger = `-- name: CreateSurveyTrigger :one
INSERT INTO survey_triggers (id, survey_id, kind, enabled, delay_seconds, cooldown_days)
VALUES ($1, $2, 'visit_checked_out', $3,
  $4, $5) RETURNING id, survey_id, kind, enabled, delay_seconds, cooldown_days, version, created_at, updated_at
`

type CreateSurveyTriggerParams struct {
	ID           uuid.UUID
	SurveyID     uuid.UUID
	Enabled      bool
	DelaySeconds int32
	CooldownDays int32
}

func (q *Queries) CreateSurveyTrigger(ctx context.Context, arg CreateSurveyTriggerParams) (SurveyTrigger, error) {
	row := q.db.QueryRow(ctx, createSurveyTrigger,
		arg.ID,
		arg.SurveyID,
		arg.Enabled,
		arg.DelaySeconds,
		arg.CooldownDays,
	)
	var i SurveyTrigger
	err := row.Scan(
		&i.ID,
		&i.SurveyID,
		&i.Kind,
		&i.Enabled,
		&i.DelaySeconds,
		&i.CooldownDays,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSurveyVersion = `-- name: CreateSurveyVersion :one
INSERT INTO survey_versions (id, survey_id, revision, title, introduction)
VALUES ($1, $2, $3, $4, $5) RETURNING id, survey_id, revision, title, introduction, published_at, created_at
`

type CreateSurveyVersionParams struct {
	ID           uuid.UUID
	SurveyID     uuid.UUID
	Revision     int32
	Title        string
	Introduction *string
}

func (q *Queries) CreateSurveyVersion(ctx context.Context, arg CreateSurveyVersionParams) (SurveyVersion, error) {
	row := q.db.QueryRow(ctx, createSurveyVersion,
		arg.ID,
		arg.SurveyID,
		arg.Revision,
		arg.Title,
		arg.Introduction,
	)
	var i SurveyVersion
	err := row.Scan(
		&i.ID,
		&i.SurveyID,
		&i.Revision,
		&i.Title,
		&i.Introduction,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSurveyInvitationPII = `-- name: DeleteExpiredSurveyInvitationPII :execrows
UPDATE survey_invitations SET
  status = CASE
    WHEN expires_at < $1 AND status IN ('pending', 'delivering', 'sent', 'failed') THEN 'expired'
    ELSE status
  END,
  person_id = NULL,
  visit_id = NULL,
  recipient_email = NULL,
  delivery_claimed_at = NULL
WHERE (expires_at < $1 OR redeemed_at < $1)
  AND (person_id IS NOT NULL OR visit_id IS NOT NULL OR recipient_email IS NOT NULL)
`

func (q *Queries) DeleteExpiredSurveyInvitationPII(ctx context.Context, beforeTime time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSurveyInvitationPII, beforeTime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSurveyQuestions = `-- name: DeleteSurveyQuestions :exec
DELETE FROM survey_questions WHERE survey_version_id = $1
`

func (q *Queries) DeleteSurveyQuestions(ctx context.Context, surveyVersionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSurveyQuestions, surveyVersionID)
	return err
}

const disableSurveyTriggers = `-- name: DisableSurveyTriggers :exec
UPDATE survey_triggers SET enabled = false, version = version + 1, updated_at = now()
WHERE survey_id = $1 AND enabled
`

func (q *Queries) DisableSurveyTriggers(ctx context.Context, surveyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, disableSurveyTriggers, surveyID)
	return err
}

const getLatestSurveyVersionForUpdate = `-- name: GetLatestSurveyVersionForUpdate :one
SELECT id, survey_id, revision, title, introduction, published_at, created_at FROM survey_versions WHERE survey_id = $1
ORDER BY revision DESC LIMIT 1 FOR UPDATE
`

func (q *Queries) GetLatestSurveyVersionForUpdate(ctx context.Context, surveyID uuid.UUID) (SurveyVersion, error) {
	row := q.db.QueryRow(ctx, getLatestSurveyVersionForUpdate, surveyID)
	var i SurveyVersion
	err := row.Scan(
		&i.ID,
		&i.SurveyID,
		&i.Revision,
		&i.Title,
		&i.Introduction,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPublicSurveyInvitation = `-- name: GetPublicSurveyInvitation :one
SELECT si.id AS invitation_id, si.expires_at, si.status, si.person_id,
  s.anonymous, sv.id AS survey_version_id, sv.title, sv.introduction
FROM survey_invitations si
JOIN survey_versions sv ON sv.id = si.survey_version_id
JOIN surveys s ON s.id = sv.survey_id
WHERE si.token_digest = $1
`

type GetPublicSurveyInvitationRow struct {
	InvitationID    uuid.UUID
	ExpiresAt       time.Time
	Status          string
	PersonID        *uuid.UUID
	Anonymous       bool
	SurveyVersionID uuid.UUID
	Title           string
	Introduction    *string
}

func (q *Queries) GetPublicSurveyInvitation(ctx context.Context, tokenDigest []byte) (GetPublicSurveyInvitationRow, error) {
	row := q.db.QueryRow(ctx, getPublicSurveyInvitation, tokenDigest)
	var i GetPublicSurveyInvitationRow
	err := row.Scan(
		&i.InvitationID,
		&i.ExpiresAt,
		&i.Status,
		&i.PersonID,
		&i.Anonymous,
		&i.SurveyVersionID,
		&i.Title,
		&i.Introduction,
	)
	return i, err
}

const getPublicSurveyInvitationForUpdate = `-- name: GetPublicSurveyInvitationForUpdate :one
SELECT si.id AS invitation_id, si.expires_at, si.status, si.person_id,
  s.anonymous, sv.id AS survey_version_id
FROM survey_invitations si
JOIN survey_versions sv ON sv.id = si.survey_version_id
JOIN surveys s ON s.id = sv.survey_id
WHERE si.token_digest = $1
FOR UPDATE OF si
`

type GetPublicSurveyInvitationForUpdateRow struct {
	InvitationID    uuid.UUID
	ExpiresAt       time.Time
	Status          string
	PersonID        *uuid.UUID
	Anonymous       bool
	SurveyVersionID uuid.UUID
}

func (q *Queries) GetPublicSurveyInvitationForUpdate(ctx context.Context, tokenDigest []byte) (GetPublicSurveyInvitationForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getPublicSurveyInvitationForUpdate, tokenDigest)
	var i GetPublicSurveyInvitationForUpdateRow
	err := row.Scan(
		&i.InvitationID,
		&i.ExpiresAt,
		&i.Status,
		&i.PersonID,
		&i.Anonymous,
		&i.SurveyVersionID,
	)
	return i, err
}

const getSurvey = `-- name: GetSurvey :one
SELECT s.id, s.name, s.description, s.status, s.anonymous, s.version, s.created_at, s.updated_at, sv.id AS survey_version_id, sv.revision, sv.title, sv.introduction
FROM surveys s
JOIN LATERAL (
  SELECT id, survey_id, revision, title, introduction, published_at, created_at FROM survey_versions WHERE survey_id = s.id ORDER BY revision DESC LIMIT 1
) sv ON true
WHERE s.id = $1
`

type GetSurveyRow struct {
	ID              uuid.UUID
	Name            string
	Description     *string
	Status          string
	Anonymous       bool
	Version         int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
	SurveyVersionID uuid.UUID
	Revision        int32
	Title           string
	Introduction    *string
}

func (q *Queries) GetSurvey(ctx context.Context, id uuid.UUID) (GetSurveyRow, error) {
	row := q.db.QueryRow(ctx, getSurvey, id)
	var i GetSurveyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Anonymous,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SurveyVersionID,
		&i.Revision,
		&i.Title,
		&i.Introduction,
	)
	return i, err
}

const getSurveyForUpdate = `-- name: GetSurveyForUpdate :one
SELECT id, name, description, status, anonymous, version, created_at, updated_at FROM surveys WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetSurveyForUpdate(ctx context.Context, id uuid.UUID) (Survey, error) {
	row := q.db.QueryRow(ctx, getSurveyForUpdate, id)
	var i Survey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Anonymous,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSurveyTrigger = `-- name: GetSurveyTrigger :one
SELECT id, survey_id, kind, enabled, delay_seconds, cooldown_days, version, created_at, updated_at FROM survey_triggers WHERE survey_id = $1 AND kind = 'visit_checked_out'
`

func (q *Queries) GetSurveyTrigger(ctx context.Context, surveyID uuid.UUID) (SurveyTrigger, error) {
	row := q.db.QueryRow(ctx, getSurveyTrigger, surveyID)
	var i SurveyTrigger
	err := row.Scan(
		&i.ID,
		&i.SurveyID,
		&i.Kind,
		&i.Enabled,
		&i.DelaySeconds,
		&i.CooldownDays,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEligiblePostVisitTriggers = `-- name: ListEligiblePostVisitTriggers :many
SELECT st.id AS trigger_id, sv.id AS survey_version_id, st.delay_seconds, st.cooldown_days, p.email
FROM survey_triggers st
JOIN surveys s ON s.id = st.survey_id AND s.status = 'published'
JOIN LATERAL (
  SELECT id FROM survey_versions WHERE survey_id = s.id AND published_at IS NOT NULL
  ORDER BY revision DESC LIMIT 1
) sv ON true
JOIN people p ON p.id = $1 AND p.email IS NOT NULL
WHERE st.kind = 'visit_checked_out' AND st.enabled
  AND NOT EXISTS (
    SELECT 1 FROM survey_invitations si JOIN survey_versions previous ON previous.id = si.survey_version_id
    WHERE previous.survey_id = s.id AND si.person_id = $1
      AND si.created_at > now() - make_interval(days => st.cooldown_days)
  )
`

type ListEligiblePostVisitTriggersRow struct {
	TriggerID       uuid.UUID
	SurveyVersionID uuid.UUID
	DelaySeconds    int32
	CooldownDays    int32
	Email           *string
}

func (q *Queries) ListEligiblePostVisitTriggers(ctx context.Context, personID uuid.UUID) ([]ListEligiblePostVisitTriggersRow, error) {
	rows, err := q.db.Query(ctx, listEligiblePostVisitTriggers, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEligiblePostVisitTriggersRow{}
	for rows.Next() {
		var i ListEligiblePostVisitTriggersRow
		if err := rows.Scan(
			&i.TriggerID,
			&i.SurveyVersionID,
			&i.DelaySeconds,
			&i.CooldownDays,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSurveyOptions = `-- name: ListSurveyOptions :many
SELECT id, question_id, label, position FROM survey_question_options WHERE question_id = $1
ORDER BY position, id
`

func (q *Queries) ListSurveyOptions(ctx context.Context, questionID uuid.UUID) ([]SurveyQuestionOption, error) {
	rows, err := q.db.Query(ctx, listSurveyOptions, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SurveyQuestionOption{}
	for rows.Next() {
		var i SurveyQuestionOption
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Label,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSurveyQuestions = `-- name: ListSurveyQuestions :many
SELECT id, survey_version_id, kind, prompt, required, position, rating_min, rating_max FROM survey_questions WHERE survey_version_id = $1
ORDER BY position, id
`

func (q *Queries) ListSurveyQuestions(ctx context.Context, surveyVersionID uuid.UUID) ([]SurveyQuestion, error) {
	rows, err := q.db.Query(ctx, listSurveyQuestions, surveyVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SurveyQuestion{}
	for rows.Next() {
		var i SurveyQuestion
		if err := rows.Scan(
			&i.ID,
			&i.SurveyVersionID,
			&i.Kind,
			&i.Prompt,
			&i.Required,
			&i.Position,
			&i.RatingMin,
			&i.RatingMax,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSurveys = `-- name: ListSurveys :many
SELECT s.id, s.name, s.description, s.status, s.anonymous, s.version, s.created_at, s.updated_at, sv.id AS survey_version_id, sv.revision, sv.title, sv.introduction
FROM surveys s
JOIN LATERAL (
  SELECT id, survey_id, revision, title, introduction, published_at, created_at FROM survey_versions WHERE survey_id = s.id ORDER BY revision DESC LIMIT 1
) sv ON true
ORDER BY s.updated_at DESC, s.id
`

type ListSurveysRow struct {
	ID              uuid.UUID
	Name            string
	Description     *string
	Status          string
	Anonymous       bool
	Version         int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
	SurveyVersionID uuid.UUID
	Revision        int32
	Title           string
	Introduction    *string
}

func (q *Queries) ListSurveys(ctx context.Context) ([]ListSurveysRow, error) {
	rows, err := q.db.Query(ctx, listSurveys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSurveysRow{}
	for rows.Next() {
		var i ListSurveysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.Anonymous,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SurveyVersionID,
			&i.Revision,
			&i.Title,
			&i.Introduction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSurveyInvitationFailed = `-- name: MarkSurveyInvitationFailed :exec
UPDATE survey_invitations SET status = 'failed', delivery_claimed_at = NULL,
  delivery_failure_code = $1 WHERE id = $2 AND status = 'delivering'
`

type MarkSurveyInvitationFailedParams struct {
	DeliveryFailureCode *string
	ID                  uuid.UUID
}

func (q *Queries) MarkSurveyInvitationFailed(ctx context.Context, arg MarkSurveyInvitationFailedParams) error {
	_, err := q.db.Exec(ctx, markSurveyInvitationFailed, arg.DeliveryFailureCode, arg.ID)
	return err
}

const markSurveyInvitationSent = `-- name: MarkSurveyInvitationSent :exec
UPDATE survey_invitations SET status = 'sent', sent_at = now(), delivery_claimed_at = NULL,
  delivery_failure_code = NULL WHERE id = $1 AND status = 'delivering'
`

func (q *Queries) MarkSurveyInvitationSent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markSurveyInvitationSent, id)
	return err
}

const markSurveyVersionPublished = `-- name: MarkSurveyVersionPublished :exec
UPDATE survey_versions SET published_at = now() WHERE id = $1 AND published_at IS NULL
`

func (q *Queries) MarkSurveyVersionPublished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markSurveyVersionPublished, id)
	return err
}

const publishSurvey = `-- name: PublishSurvey :one
UPDATE surveys SET status = 'published', version = version + 1, updated_at = now()
WHERE id = $1 AND version = $2 AND status = 'draft' RETURNING id, name, description, status, anonymous, version, created_at, updated_at
`

type PublishSurveyParams struct {
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) PublishSurvey(ctx context.Context, arg PublishSurveyParams) (Survey, error) {
	row := q.db.QueryRow(ctx, publishSurvey, arg.ID, arg.ExpectedVersion)
	var i Survey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Anonymous,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSurveyDraft = `-- name: UpdateSurveyDraft :one
UPDATE surveys SET name = $1, description = $2, anonymous = $3,
  version = version + 1, updated_at = now()
WHERE id = $4 AND version = $5 AND status = 'draft' RETURNING id, name, description, status, anonymous, version, created_at, updated_at
`

type UpdateSurveyDraftParams struct {
	Name            string
	Description     *string
	Anonymous       bool
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) UpdateSurveyDraft(ctx context.Context, arg UpdateSurveyDraftParams) (Survey, error) {
	row := q.db.QueryRow(ctx, updateSurveyDraft,
		arg.Name,
		arg.Description,
		arg.Anonymous,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i Survey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Anonymous,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSurveyTrigger = `-- name: UpdateSurveyTrigger :one
UPDATE survey_triggers SET enabled = $1, delay_seconds = $2,
  cooldown_days = $3, version = version + 1, updated_at = now()
WHERE survey_id = $4 AND kind = 'visit_checked_out'
  AND version = $5 RETURNING id, survey_id, kind, enabled, delay_seconds, cooldown_days, version, created_at, updated_at
`

type UpdateSurveyTriggerParams struct {
	Enabled         bool
	DelaySeconds    int32
	CooldownDays    int32
	SurveyID        uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) UpdateSurveyTrigger(ctx context.Context, arg UpdateSurveyTriggerParams) (SurveyTrigger, error) {
	row := q.db.QueryRow(ctx, updateSurveyTrigger,
		arg.Enabled,
		arg.DelaySeconds,
		arg.CooldownDays,
		arg.SurveyID,
		arg.ExpectedVersion,
	)
	var i SurveyTrigger
	err := row.Scan(
		&i.ID,
		&i.SurveyID,
		&i.Kind,
		&i.Enabled,
		&i.DelaySeconds,
		&i.CooldownDays,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSurveyVersionDraft = `-- name: UpdateSurveyVersionDraft :exec
UPDATE survey_versions SET title = $1, introduction = $2
WHERE id = $3 AND published_at IS NULL
`

type UpdateSurveyVersionDraftParams struct {
	Title        string
	Introduction *string
	ID           uuid.UUID
}

func (q *Queries) UpdateSurveyVersionDraft(ctx context.Context, arg UpdateSurveyVersionDraftParams) error {
	_, err := q.db.Exec(ctx, updateSurveyVersionDraft, arg.Title, arg.Introduction, arg.ID)
	return err
}
