// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package surveysdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	CancelSurveyInvitationsForSurvey(ctx context.Context, surveyID uuid.UUID) (int64, error)
	CancelSurveyInvitationsForVisit(ctx context.Context, visitID *uuid.UUID) (int64, error)
	ClaimDueSurveyInvitations(ctx context.Context, pageLimit int32) ([]ClaimDueSurveyInvitationsRow, error)
	CloseSurvey(ctx context.Context, arg CloseSurveyParams) (Survey, error)
	ConsumeSurveyInvitation(ctx context.Context, id uuid.UUID) (int64, error)
	CreateSurvey(ctx context.Context, arg CreateSurveyParams) (Survey, error)
	CreateSurveyAnswer(ctx context.Context, arg CreateSurveyAnswerParams) error
	CreateSurveyInvitation(ctx context.Context, arg CreateSurveyInvitationParams) (SurveyInvitation, error)
	CreateSurveyOption(ctx context.Context, arg CreateSurveyOptionParams) (SurveyQuestionOption, error)
	CreateSurveyQuestion(ctx context.Context, arg CreateSurveyQuestionParams) (SurveyQuestion, error)
	CreateSurveyResponse(ctx context.Context, arg CreateSurveyResponseParams) (SurveyResponse, error)
	CreateSurveyTrigger(ctx context.Context, arg CreateSurveyTriggerParams) (SurveyTrigger, error)
	CreateSurveyVersion(ctx context.Context, arg CreateSurveyVersionParams) (SurveyVersion, error)
	DeleteExpiredSurveyInvitationPII(ctx context.Context, beforeTime time.Time) (int64, error)
	DeleteSurveyQuestions(ctx context.Context, surveyVersionID uuid.UUID) error
	DisableSurveyTriggers(ctx context.Context, surveyID uuid.UUID) error
	GetLatestSurveyVersionForUpdate(ctx context.Context, surveyID uuid.UUID) (SurveyVersion, error)
	GetPublicSurveyInvitation(ctx context.Context, tokenDigest []byte) (GetPublicSurveyInvitationRow, error)
	GetPublicSurveyInvitationForUpdate(ctx context.Context, tokenDigest []byte) (GetPublicSurveyInvitationForUpdateRow, error)
	GetSurvey(ctx context.Context, id uuid.UUID) (GetSurveyRow, error)
	GetSurveyForUpdate(ctx context.Context, id uuid.UUID) (Survey, error)
	GetSurveyTrigger(ctx context.Context, surveyID uuid.UUID) (SurveyTrigger, error)
	ListEligiblePostVisitTriggers(ctx context.Context, personID uuid.UUID) ([]ListEligiblePostVisitTriggersRow, error)
	ListSurveyOptions(ctx context.Context, questionID uuid.UUID) ([]SurveyQuestionOption, error)
	ListSurveyQuestions(ctx context.Context, surveyVersionID uuid.UUID) ([]SurveyQuestion, error)
	ListSurveys(ctx context.Context) ([]ListSurveysRow, error)
	MarkSurveyInvitationFailed(ctx context.Context, arg MarkSurveyInvitationFailedParams) error
	MarkSurveyInvitationSent(ctx context.Context, id uuid.UUID) error
	MarkSurveyVersionPublished(ctx context.Context, id uuid.UUID) error
	PublishSurvey(ctx context.Context, arg PublishSurveyParams) (Survey, error)
	UpdateSurveyDraft(ctx context.Context, arg UpdateSurveyDraftParams) (Survey, error)
	UpdateSurveyTrigger(ctx context.Context, arg UpdateSurveyTriggerParams) (SurveyTrigger, error)
	UpdateSurveyVersionDraft(ctx context.Context, arg UpdateSurveyVersionDraftParams) error
}

var _ Querier = (*Queries)(nil)
