// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package eventsdb

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                         uuid.UUID
	PersonID                   uuid.UUID
	Status                     string
	Version                    int64
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	ProvisioningSource         string
	FirstAuthenticatedAt       pgtype.Timestamptz
	AdministrativelyDisabledAt pgtype.Timestamptz
}

type AttendanceDailyStatistic struct {
	Day                   pgtype.Date
	VisitorCount          int64
	DailyUniqueVisitors   int64
	VisitorSeconds        int64
	CompletedVisitCount   int64
	CompletedVisitSeconds int64
	PeakOccupancy         int64
	UpdatedAt             time.Time
}

type AuditEvent struct {
	ID             uuid.UUID
	ActorAccountID *uuid.UUID
	Action         string
	ResourceType   string
	ResourceID     *uuid.UUID
	OccurredAt     time.Time
	RequestID      *uuid.UUID
	ChangedFields  []string
	Metadata       []byte
	Source         string
	ActorType      string
}

type AuthChallenge struct {
	ID                  uuid.UUID
	Kind                string
	AccountID           uuid.UUID
	AuthIdentityID      *uuid.UUID
	CodeDigest          []byte
	DeliveryAddress     *string
	AttemptCount        int16
	CreatedByAccountID  *uuid.UUID
	ExpiresAt           time.Time
	UsedAt              pgtype.Timestamptz
	CancelledAt         pgtype.Timestamptz
	DeliveryStatus      string
	DeliveryAttemptedAt pgtype.Timestamptz
	DeliveryFailureCode *string
	CreatedAt           time.Time
}

type AuthIdentity struct {
	ID                   uuid.UUID
	AccountID            uuid.UUID
	Kind                 string
	IdentifierDisplay    *string
	IdentifierNormalized *string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	ProviderID           *uuid.UUID
	Issuer               *string
	Subject              *string
	VerifiedAt           pgtype.Timestamptz
	DisabledAt           pgtype.Timestamptz
	LastUsedAt           pgtype.Timestamptz
}

type AuthRateLimit struct {
	Action          string
	KeyDigest       []byte
	WindowStartedAt time.Time
	AttemptCount    int32
	BlockedUntil    pgtype.Timestamptz
	UpdatedAt       time.Time
}

type BrandingAssetOverride struct {
	Slot               string
	Mode               string
	FileID             *uuid.UUID
	UpdatedByAccountID *uuid.UUID
	UpdatedAt          time.Time
}

type BrandingConfiguration struct {
	Singleton             bool
	LegalOrganizationName string
	DisplayName           string
	ApplicationName       string
	Tagline               *string
	PrimaryColor          string
	SecondaryColor        string
	AccentColor           string
	BackgroundColor       string
	ImprintMode           string
	ImprintMarkdown       string
	ImprintExternalUrl    string
	PrivacyMode           string
	PrivacyMarkdown       string
	PrivacyExternalUrl    string
	Version               int64
	UpdatedByAccountID    *uuid.UUID
	UpdatedAt             time.Time
}

type DeviceType struct {
	ID          uuid.UUID
	Name        string
	Description *string
	Version     int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Event struct {
	ID                  uuid.UUID
	Name                string
	InternalDescription *string
	Location            *string
	OwnerPersonID       *uuid.UUID
	Status              string
	PublicTitle         *string
	PublicDescription   *string
	PublicLocation      *string
	PublicID            string
	IsPublic            bool
	PublicSignupEnabled bool
	ClosedAt            pgtype.Timestamptz
	CreatedByAccountID  *uuid.UUID
	Version             int32
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type EventFile struct {
	ID          uuid.UUID
	EventID     uuid.UUID
	FileID      uuid.UUID
	Description *string
	Visibility  string
	Version     int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	IsBanner    bool
}

type EventSession struct {
	ID          uuid.UUID
	EventID     uuid.UUID
	Name        *string
	Location    *string
	Description *string
	StartsAt    time.Time
	EndsAt      time.Time
	IsPublic    bool
	Status      string
	Version     int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type EventShift struct {
	ID             uuid.UUID
	EventID        uuid.UUID
	SessionID      *uuid.UUID
	Name           string
	Description    *string
	StartsAt       time.Time
	EndsAt         time.Time
	SignupOpensAt  pgtype.Timestamptz
	SignupClosesAt pgtype.Timestamptz
	IsPublic       bool
	Status         string
	Version        int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type EventShiftAssignment struct {
	ID                            uuid.UUID
	EventID                       uuid.UUID
	ShiftID                       uuid.UUID
	RequirementID                 uuid.UUID
	PersonID                      *uuid.UUID
	FirstNameSnapshot             *string
	LastNameSnapshot              *string
	EmailSnapshot                 *string
	EmailNormalized               *string
	PhoneSnapshot                 *string
	PhoneNormalized               *string
	Source                        string
	Status                        string
	CreatedByAccountID            *uuid.UUID
	ManagementTokenDigest         []byte
	ConflictOverriddenByAccountID *uuid.UUID
	CancelledAt                   pgtype.Timestamptz
	CancelledByAccountID          *uuid.UUID
	PersonalDataErasedAt          pgtype.Timestamptz
	Version                       int32
	CreatedAt                     time.Time
	UpdatedAt                     time.Time
}

type EventShiftRequirement struct {
	ID              uuid.UUID
	EventID         uuid.UUID
	ShiftID         uuid.UUID
	Name            string
	Description     *string
	RequiredCount   int32
	EligibilityMode string
	Version         int32
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type EventShiftRequirementRole struct {
	RequirementID uuid.UUID
	RoleID        uuid.UUID
}

type EventTask struct {
	ID                   uuid.UUID
	EventID              uuid.UUID
	TaskListID           *uuid.UUID
	Title                string
	Description          *string
	Status               string
	Priority             string
	AssigneePersonID     *uuid.UUID
	DueAt                pgtype.Timestamptz
	CompletedAt          pgtype.Timestamptz
	CompletedByAccountID *uuid.UUID
	SortOrder            int32
	CreatedByAccountID   *uuid.UUID
	Version              int32
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type EventTaskList struct {
	ID          uuid.UUID
	EventID     uuid.UUID
	Name        string
	Description *string
	SortOrder   int32
	Version     int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ExternalInvoiceRequest struct {
	ID                  uuid.UUID
	Reference           string
	OrderID             *uuid.UUID
	OrderReference      string
	Provider            string
	State               string
	Currency            string
	RequestedAmount     pgtype.Numeric
	SupersedesRequestID *uuid.UUID
	Version             int64
	CreatedAt           time.Time
}

type ExternalInvoiceRequestDetail struct {
	RequestID                     uuid.UUID
	RecipientKind                 string
	RecipientName                 string
	RecipientPersonID             *uuid.UUID
	RecipientOrganizationID       *uuid.UUID
	AddressLine1                  string
	AddressLine2                  string
	PostalCode                    string
	Locality                      string
	Region                        string
	CountryCode                   string
	ContactPersonID               *uuid.UUID
	ContactName                   string
	ContactChannel                string
	ServiceStartsOn               pgtype.Date
	ServiceEndsOn                 pgtype.Date
	ServiceDescription            string
	PurchaseOrderReference        string
	RequirementsVersion           int64
	RequirePurchaseOrderReference bool
	ItemSummary                   []byte
	SnapshotSchemaVersion         int32
}

type ExternalInvoiceRequestEvent struct {
	ID                 uuid.UUID
	RequestID          uuid.UUID
	Kind               string
	ExternalReference  string
	ReconciliationKind string
	Reason             string
	EffectiveAt        time.Time
	RecordedAt         time.Time
	ActorAccountID     *uuid.UUID
}

type File struct {
	ID                 uuid.UUID
	StorageKey         string
	OriginalFilename   string
	ContentType        string
	SizeBytes          int64
	Sha256             []byte
	CreatedByAccountID *uuid.UUID
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type InventoryTransaction struct {
	ID                  uuid.UUID
	MaterialID          uuid.UUID
	Kind                string
	QuantityDelta       pgtype.Numeric
	UnitAcquisitionCost pgtype.Numeric
	InventoryValueDelta pgtype.Numeric
	TotalPurchasePrice  pgtype.Numeric
	OccurredAt          time.Time
	Supplier            *string
	Note                *string
	AdjustmentReason    *string
	MachineJobUsageID   *uuid.UUID
	ActorAccountID      *uuid.UUID
	CreatedAt           time.Time
}

type LaborordnungRequest struct {
	ID                        uuid.UUID
	PersonID                  uuid.UUID
	RequiredVersionID         uuid.UUID
	PreviousVersionID         *uuid.UUID
	Status                    string
	RequestedAt               time.Time
	CompletedAt               pgtype.Timestamptz
	SupersededAt              pgtype.Timestamptz
	ConfirmedByAccountID      *uuid.UUID
	PhysicalDocumentReference *string
	SignedDate                pgtype.Date
	ArchiveNote               *string
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
}

type LaborordnungVersion struct {
	ID                 uuid.UUID
	Status             string
	HumanRevision      string
	PdfFileID          uuid.UUID
	PdfSha256          []byte
	EffectiveAt        pgtype.Timestamptz
	PublishedAt        pgtype.Timestamptz
	CreatedByAccountID *uuid.UUID
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type Machine struct {
	ID                         uuid.UUID
	MachineTypeID              uuid.UUID
	Name                       string
	Status                     string
	ExternalIdentifier         *string
	AutomaticCollectionEnabled bool
	LastIngestedAt             pgtype.Timestamptz
	Version                    int64
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
}

type MachineJob struct {
	ID                         uuid.UUID
	DisplayID                  string
	MachineID                  uuid.UUID
	StartsAt                   time.Time
	EndsAt                     time.Time
	Source                     string
	ExternalID                 *string
	ExternalMetadata           []byte
	ReviewState                string
	CustomerPersonID           *uuid.UUID
	CustomerOrganizationID     *uuid.UUID
	OperatorPersonID           *uuid.UUID
	Outcome                    string
	Notes                      *string
	PricingStatus              string
	CalculatedPrice            pgtype.Numeric
	FinalPrice                 pgtype.Numeric
	PriceOverrideReason        *string
	PriceOverriddenByAccountID *uuid.UUID
	PriceOverriddenAt          pgtype.Timestamptz
	ActivePricingSnapshotID    *uuid.UUID
	Version                    int64
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
}

type MachineJobMaterialUsage struct {
	ID           uuid.UUID
	MachineJobID uuid.UUID
	MaterialID   uuid.UUID
	Quantity     pgtype.Numeric
	Active       bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type MachineJobPricingSnapshot struct {
	ID                  uuid.UUID
	MachineJobID        uuid.UUID
	Revision            int32
	PricingGroupID      *uuid.UUID
	PricingGroupName    string
	Currency            string
	Reason              string
	Complete            bool
	CalculatedAmount    pgtype.Numeric
	CapturedByAccountID *uuid.UUID
	CapturedAt          time.Time
}

type MachineJobPricingSnapshotRule struct {
	ID           uuid.UUID
	SnapshotID   uuid.UUID
	SourceRuleID *uuid.UUID
	Kind         string
	Label        string
	Selector     string
	Unit         string
	Rate         pgtype.Numeric
	Missing      bool
}

type MachineType struct {
	ID        uuid.UUID
	Name      string
	Active    bool
	Version   int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type MailConfiguration struct {
	Singleton             bool
	Enabled               bool
	Provider              string
	SmtpHost              string
	SmtpPort              int32
	SmtpTlsMode           string
	SmtpUsername          string
	EncryptedSmtpPassword []byte
	FromAddress           string
	FromName              string
	BaseUrl               string
	Version               int64
	UpdatedByAccountID    *uuid.UUID
	UpdatedAt             time.Time
}

type ManagedDevice struct {
	ID                uuid.UUID
	Name              string
	DeviceTypeID      uuid.UUID
	TokenDigest       []byte
	ExpiresAt         pgtype.Timestamptz
	RevokedAt         pgtype.Timestamptz
	LastSeenAt        pgtype.Timestamptz
	Version           int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
	SessionPolicyID   *uuid.UUID
	TerminalEnabled   bool
	CheckInAssurance  string
	CheckOutAssurance string
	CheckoutMode      string
	AllowedAppModes   []string
}

type ManagedDeviceCapability struct {
	ManagedDeviceID uuid.UUID
	Capability      string
	Enabled         bool
	Version         int64
	UpdatedAt       time.Time
}

type ManagedDeviceHardwareReport struct {
	ManagedDeviceID uuid.UUID
	Platform        string
	BridgeVersion   string
	ReportedAt      time.Time
}

type ManagedDeviceReportedCapability struct {
	ManagedDeviceID uuid.UUID
	Capability      string
}

type Material struct {
	ID                uuid.UUID
	Name              string
	Category          string
	Color             *string
	Unit              string
	Active            bool
	LowStockThreshold pgtype.Numeric
	Version           int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type MaterialBalance struct {
	MaterialID      uuid.UUID
	Quantity        pgtype.Numeric
	InventoryValue  pgtype.Numeric
	AverageUnitCost pgtype.Numeric
	Version         int64
	UpdatedAt       time.Time
}

type OidcFlow struct {
	ID                    uuid.UUID
	ProviderID            uuid.UUID
	Kind                  string
	AccountID             *uuid.UUID
	StateDigest           []byte
	BrowserTokenDigest    []byte
	EncryptedNonce        []byte
	EncryptedPkceVerifier []byte
	ExpiresAt             time.Time
	UsedAt                pgtype.Timestamptz
	CreatedAt             time.Time
	SessionID             *uuid.UUID
}

type OidcProvider struct {
	ID                    uuid.UUID
	Slug                  string
	DisplayName           string
	Issuer                string
	ClientID              string
	EncryptedClientSecret []byte
	Enabled               bool
	JitEnabled            bool
	AcrAssuranceMappings  []byte
	Version               int64
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type OpenDay struct {
	ID           uuid.UUID
	PeriodID     uuid.UUID
	StartsAt     time.Time
	EndsAt       time.Time
	InternalNote *string
	Status       string
	Version      int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type OpenDayAcademicBreak struct {
	ID        uuid.UUID
	Name      string
	StartsOn  pgtype.Date
	EndsOn    pgtype.Date
	Version   int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type OpenDayAssignment struct {
	ID                 uuid.UUID
	OpenDayID          uuid.UUID
	RequirementID      uuid.UUID
	PersonID           uuid.UUID
	CreatedByAccountID *uuid.UUID
	CreatedAt          time.Time
}

type OpenDayPeriod struct {
	ID        uuid.UUID
	Name      string
	StartsOn  pgtype.Date
	EndsOn    pgtype.Date
	Status    string
	Version   int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type OpenDayStaffRequirement struct {
	ID            uuid.UUID
	OpenDayID     uuid.UUID
	Kind          string
	RequiredCount int32
}

type OpenDayStaffRequirementRole struct {
	RequirementID uuid.UUID
	RoleID        uuid.UUID
}

type Order struct {
	ID                     uuid.UUID
	Reference              string
	Status                 string
	Currency               string
	CustomerKind           string
	CustomerPersonID       *uuid.UUID
	CustomerOrganizationID *uuid.UUID
	FulfillmentMode        string
	TotalAmount            pgtype.Numeric
	ReplacesOrderID        *uuid.UUID
	ReplacesOrderReference *string
	Version                int64
	CreatedAt              time.Time
	UpdatedAt              time.Time
	CreatedByAccountID     *uuid.UUID
	FinalizedAt            pgtype.Timestamptz
	CancelledAt            pgtype.Timestamptz
	ReversedAt             pgtype.Timestamptz
}

type OrderAdjustment struct {
	ID             uuid.UUID
	Reference      string
	OrderID        *uuid.UUID
	OrderReference string
	Kind           string
	Currency       string
	Amount         pgtype.Numeric
	Reason         string
	ActorAccountID *uuid.UUID
	CreatedAt      time.Time
}

type OrderAdjustmentItem struct {
	ID                   uuid.UUID
	AdjustmentID         uuid.UUID
	OriginalOrderItemID  *uuid.UUID
	OriginalItemPosition int32
	Amount               pgtype.Numeric
}

type OrderCustomerSnapshot struct {
	OrderID          uuid.UUID
	DisplayName      string
	OrganizationKind *string
	CapturedAt       time.Time
}

type OrderItem struct {
	ID                    uuid.UUID
	OrderID               uuid.UUID
	Position              int32
	Kind                  string
	Description           string
	Quantity              pgtype.Numeric
	Unit                  string
	UnitPrice             pgtype.Numeric
	Amount                pgtype.Numeric
	SourceMachineJobID    *uuid.UUID
	SourceJobVersion      *int64
	MachineJobSnapshot    []byte
	SnapshotSchemaVersion int32
	CreatedAt             time.Time
	CreatedByAccountID    *uuid.UUID
	RemovedAt             pgtype.Timestamptz
	RemovedByAccountID    *uuid.UUID
}

type OrderJobClaim struct {
	MachineJobID uuid.UUID
	OrderItemID  uuid.UUID
	CreatedAt    time.Time
}

type OrderOperation struct {
	ID                 uuid.UUID
	OperationKey       uuid.UUID
	Kind               string
	RequestFingerprint []byte
	ActorAccountID     *uuid.UUID
	OrderID            *uuid.UUID
	PaymentID          *uuid.UUID
	RequestID          *uuid.UUID
	CompletedAt        time.Time
}

type Organization struct {
	ID        uuid.UUID
	Name      string
	Kind      string
	Active    bool
	Version   int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type OrganizationInvoicingRequirement struct {
	OrganizationID                uuid.UUID
	RequirePurchaseOrderReference bool
	Version                       int64
	UpdatedAt                     time.Time
	UpdatedByAccountID            *uuid.UUID
}

type OrganizationPricingGroupAssignment struct {
	OrganizationID      uuid.UUID
	PricingGroupID      uuid.UUID
	AssignedByAccountID *uuid.UUID
	Version             int64
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type PasswordCredential struct {
	AuthIdentityID uuid.UUID
	PasswordHash   string
	ResetRequired  bool
	ChangedAt      time.Time
}

type PasswordResetToken struct {
	ID                 uuid.UUID
	AccountID          uuid.UUID
	TokenDigest        []byte
	CreatedByAccountID *uuid.UUID
	CreatedAt          time.Time
	ExpiresAt          time.Time
}

type Payment struct {
	ID                       uuid.UUID
	Reference                string
	EntryKind                string
	Method                   string
	Amount                   pgtype.Numeric
	Currency                 string
	OccurredAt               time.Time
	RecordedAt               time.Time
	ActorAccountID           *uuid.UUID
	ReversesPaymentID        *uuid.UUID
	ReversedPaymentReference *string
	ReversalReasonKind       *string
	Reason                   string
	ExternalSource           string
	ExternalReference        string
	ExternalInvoiceRequestID *uuid.UUID
}

type PaymentAllocation struct {
	ID                   uuid.UUID
	PaymentID            *uuid.UUID
	PaymentReference     string
	OrderID              *uuid.UUID
	OrderReference       string
	Amount               pgtype.Numeric
	Currency             string
	OperationID          uuid.UUID
	ReversesAllocationID *uuid.UUID
	ActorAccountID       *uuid.UUID
	CreatedAt            time.Time
}

type Person struct {
	ID                  uuid.UUID
	FirstName           string
	LastName            string
	Email               *string
	Phone               *string
	MatriculationNumber *string
	PhotoReference      *string
	Version             int64
	CreatedAt           time.Time
	UpdatedAt           time.Time
	ProfileImageFileID  *uuid.UUID
	ProfileImageSource  *string
}

type PersonPricingGroupAssignment struct {
	PersonID            uuid.UUID
	PricingGroupID      uuid.UUID
	AssignedByAccountID *uuid.UUID
	Version             int64
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type PersonRole struct {
	PersonID            uuid.UUID
	RoleID              uuid.UUID
	AssignedByAccountID *uuid.UUID
	AssignedAt          time.Time
}

type PinCredential struct {
	AuthIdentityID uuid.UUID
	PinHash        string
	ChangedAt      time.Time
}

type PinLoginThrottle struct {
	Dimension    string
	KeyDigest    []byte
	FailureCount int32
	BlockedUntil pgtype.Timestamptz
	UpdatedAt    time.Time
}

type PricingGroup struct {
	ID          uuid.UUID
	Name        string
	Description *string
	Active      bool
	IsDefault   bool
	Version     int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type PricingRule struct {
	ID               uuid.UUID
	PricingGroupID   uuid.UUID
	Kind             string
	MachineTypeID    *uuid.UUID
	MaterialCategory *string
	MaterialUnit     *string
	Rate             pgtype.Numeric
	Active           bool
	Version          int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Role struct {
	ID                   uuid.UUID
	Name                 string
	Description          *string
	SystemKey            *string
	Version              int64
	CreatedAt            time.Time
	UpdatedAt            time.Time
	ProfileImageRequired bool
	LaborordnungMode     string
	SupervisorDashboard  bool
}

type RolePermissionGrant struct {
	ID               uuid.UUID
	RoleID           uuid.UUID
	PermissionID     string
	Scope            string
	MinimumAssurance string
}

type RolePermissionGrantDeviceType struct {
	GrantID      uuid.UUID
	DeviceTypeID uuid.UUID
}

type ScimConnector struct {
	ID             uuid.UUID
	Name           string
	OidcProviderID *uuid.UUID
	Enabled        bool
	Version        int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type ScimConnectorToken struct {
	ID                 uuid.UUID
	ConnectorID        uuid.UUID
	TokenDigest        []byte
	ExpiresAt          time.Time
	RevokedAt          pgtype.Timestamptz
	LastUsedAt         pgtype.Timestamptz
	CreatedByAccountID *uuid.UUID
	CreatedAt          time.Time
}

type ScimUser struct {
	ID               uuid.UUID
	ConnectorID      uuid.UUID
	PersonID         uuid.UUID
	AccountID        uuid.UUID
	ExternalID       *string
	UserName         string
	ProvisioningData []byte
	Version          int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Session struct {
	ID                     uuid.UUID
	AccountID              uuid.UUID
	AuthIdentityID         uuid.UUID
	TokenDigest            []byte
	CsrfDigest             []byte
	AuthMethod             string
	CreatedAt              time.Time
	LastSeenAt             time.Time
	IdleExpiresAt          time.Time
	AbsoluteExpiresAt      time.Time
	RevokedAt              pgtype.Timestamptz
	RevocationReason       *string
	BaseAssurance          string
	CurrentAssurance       string
	AuthenticatedAt        time.Time
	AssuranceExpiresAt     pgtype.Timestamptz
	ManagedDeviceID        *uuid.UUID
	SessionPolicyID        *uuid.UUID
	SessionPolicyVersion   int64
	IdleTimeoutSeconds     int32
	PostSessionDestination string
}

type SessionPolicy struct {
	ID                      uuid.UUID
	Name                    string
	IdleTimeoutSeconds      int32
	AbsoluteLifetimeSeconds int32
	PostSessionDestination  string
	IsDefault               bool
	Version                 int64
	CreatedAt               time.Time
	UpdatedAt               time.Time
}

type Survey struct {
	ID          uuid.UUID
	Name        string
	Description *string
	Status      string
	Anonymous   bool
	Version     int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type SurveyAnswer struct {
	ID           uuid.UUID
	ResponseID   uuid.UUID
	QuestionID   uuid.UUID
	OptionID     *uuid.UUID
	TextValue    *string
	NumericValue *int32
	BooleanValue *bool
	Position     int32
}

type SurveyInvitation struct {
	ID                  uuid.UUID
	SurveyVersionID     uuid.UUID
	PersonID            *uuid.UUID
	VisitID             *uuid.UUID
	TokenDigest         []byte
	RecipientEmail      *string
	Status              string
	DueAt               time.Time
	ExpiresAt           time.Time
	SentAt              pgtype.Timestamptz
	RedeemedAt          pgtype.Timestamptz
	DeliveryAttempts    int32
	DeliveryClaimedAt   pgtype.Timestamptz
	DeliveryFailureCode *string
	CreatedAt           time.Time
}

type SurveyQuestion struct {
	ID              uuid.UUID
	SurveyVersionID uuid.UUID
	Kind            string
	Prompt          string
	Required        bool
	Position        int32
	RatingMin       *int32
	RatingMax       *int32
}

type SurveyQuestionOption struct {
	ID         uuid.UUID
	QuestionID uuid.UUID
	Label      string
	Position   int32
}

type SurveyResponse struct {
	ID                 uuid.UUID
	SurveyVersionID    uuid.UUID
	SubmittedOn        pgtype.Date
	IdentifiedPersonID *uuid.UUID
}

type SurveyTrigger struct {
	ID           uuid.UUID
	SurveyID     uuid.UUID
	Kind         string
	Enabled      bool
	DelaySeconds int32
	CooldownDays int32
	Version      int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type SurveyVersion struct {
	ID           uuid.UUID
	SurveyID     uuid.UUID
	Revision     int32
	Title        string
	Introduction *string
	PublishedAt  pgtype.Timestamptz
	CreatedAt    time.Time
}

type Visit struct {
	ID                    uuid.UUID
	PersonID              uuid.UUID
	CheckedInAt           time.Time
	CheckedOutAt          pgtype.Timestamptz
	CheckInDeviceID       *uuid.UUID
	CheckOutDeviceID      *uuid.UUID
	Status                string
	CheckInMethod         string
	CheckOutMethod        *string
	CheckInAssurance      string
	CheckOutAssurance     *string
	AdmissionDecision     string
	LaborordnungVersionID *uuid.UUID
	CheckedInByAccountID  *uuid.UUID
	CheckedOutByAccountID *uuid.UUID
	CorrectionReason      *string
	Version               int64
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type VisitorEnrollmentConfiguration struct {
	Singleton          bool
	Enabled            bool
	InitialRoleID      *uuid.UUID
	AllowedMethods     []string
	Version            int64
	UpdatedByAccountID *uuid.UUID
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type VisitorEnrollmentContext struct {
	ID                uuid.UUID
	ManagedDeviceID   uuid.UUID
	TokenDigest       []byte
	CsrfDigest        []byte
	ExpiresAt         time.Time
	UsedAt            pgtype.Timestamptz
	CreatedAt         time.Time
	LabRulesVersionID *uuid.UUID
}

type VisitorEnrollmentDeviceType struct {
	DeviceTypeID uuid.UUID
}
