// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package eventsdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addEventRequirementRole = `-- name: AddEventRequirementRole :exec
INSERT INTO event_shift_requirement_roles (requirement_id, role_id)
VALUES ($1, $2)
`

type AddEventRequirementRoleParams struct {
	RequirementID uuid.UUID
	RoleID        uuid.UUID
}

func (q *Queries) AddEventRequirementRole(ctx context.Context, arg AddEventRequirementRoleParams) error {
	_, err := q.db.Exec(ctx, addEventRequirementRole, arg.RequirementID, arg.RoleID)
	return err
}

const advisoryLockEventContact = `-- name: AdvisoryLockEventContact :exec
SELECT pg_advisory_xact_lock($1)
`

func (q *Queries) AdvisoryLockEventContact(ctx context.Context, lockKey int64) error {
	_, err := q.db.Exec(ctx, advisoryLockEventContact, lockKey)
	return err
}

const cancelEventAssignment = `-- name: CancelEventAssignment :one
UPDATE event_shift_assignments
SET status = 'cancelled', cancelled_at = now(), cancelled_by_account_id = $1,
    version = version + 1, updated_at = now()
WHERE id = $2 AND version = $3 AND status = 'active'
RETURNING id, event_id, shift_id, requirement_id, person_id, first_name_snapshot, last_name_snapshot, email_snapshot, email_normalized, phone_snapshot, phone_normalized, source, status, created_by_account_id, management_token_digest, conflict_overridden_by_account_id, cancelled_at, cancelled_by_account_id, personal_data_erased_at, version, created_at, updated_at
`

type CancelEventAssignmentParams struct {
	CancelledByAccountID *uuid.UUID
	ID                   uuid.UUID
	ExpectedVersion      int32
}

func (q *Queries) CancelEventAssignment(ctx context.Context, arg CancelEventAssignmentParams) (EventShiftAssignment, error) {
	row := q.db.QueryRow(ctx, cancelEventAssignment, arg.CancelledByAccountID, arg.ID, arg.ExpectedVersion)
	var i EventShiftAssignment
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ShiftID,
		&i.RequirementID,
		&i.PersonID,
		&i.FirstNameSnapshot,
		&i.LastNameSnapshot,
		&i.EmailSnapshot,
		&i.EmailNormalized,
		&i.PhoneSnapshot,
		&i.PhoneNormalized,
		&i.Source,
		&i.Status,
		&i.CreatedByAccountID,
		&i.ManagementTokenDigest,
		&i.ConflictOverriddenByAccountID,
		&i.CancelledAt,
		&i.CancelledByAccountID,
		&i.PersonalDataErasedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clearOtherEventBanners = `-- name: ClearOtherEventBanners :exec
UPDATE event_files
SET is_banner = false, version = version + 1, updated_at = now()
WHERE event_id = $1 AND is_banner AND id <> $2
`

type ClearOtherEventBannersParams struct {
	EventID    uuid.UUID
	ExcludedID uuid.UUID
}

func (q *Queries) ClearOtherEventBanners(ctx context.Context, arg ClearOtherEventBannersParams) error {
	_, err := q.db.Exec(ctx, clearOtherEventBanners, arg.EventID, arg.ExcludedID)
	return err
}

const countActiveEventRequirementAssignments = `-- name: CountActiveEventRequirementAssignments :one
SELECT count(*) FROM event_shift_assignments WHERE requirement_id = $1 AND status = 'active'
`

func (q *Queries) CountActiveEventRequirementAssignments(ctx context.Context, requirementID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveEventRequirementAssignments, requirementID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEventAssignmentHistory = `-- name: CountEventAssignmentHistory :one
SELECT count(*) FROM event_shift_assignments WHERE event_id = $1
`

func (q *Queries) CountEventAssignmentHistory(ctx context.Context, eventID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEventAssignmentHistory, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEventRequirementRoles = `-- name: CountEventRequirementRoles :one
SELECT count(*) FROM event_shift_requirement_roles WHERE requirement_id = $1
`

func (q *Queries) CountEventRequirementRoles(ctx context.Context, requirementID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEventRequirementRoles, requirementID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    id, name, internal_description, location, owner_person_id, public_id, created_by_account_id
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
) RETURNING id, name, internal_description, location, owner_person_id, status, public_title, public_description, public_location, public_id, is_public, public_signup_enabled, closed_at, created_by_account_id, version, created_at, updated_at
`

type CreateEventParams struct {
	ID                  uuid.UUID
	Name                string
	InternalDescription *string
	Location            *string
	OwnerPersonID       *uuid.UUID
	PublicID            string
	CreatedByAccountID  *uuid.UUID
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.ID,
		arg.Name,
		arg.InternalDescription,
		arg.Location,
		arg.OwnerPersonID,
		arg.PublicID,
		arg.CreatedByAccountID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InternalDescription,
		&i.Location,
		&i.OwnerPersonID,
		&i.Status,
		&i.PublicTitle,
		&i.PublicDescription,
		&i.PublicLocation,
		&i.PublicID,
		&i.IsPublic,
		&i.PublicSignupEnabled,
		&i.ClosedAt,
		&i.CreatedByAccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEventAssignment = `-- name: CreateEventAssignment :one
INSERT INTO event_shift_assignments (
    id, event_id, shift_id, requirement_id, person_id,
    first_name_snapshot, last_name_snapshot, email_snapshot, email_normalized, phone_snapshot, phone_normalized,
    source, created_by_account_id, management_token_digest, conflict_overridden_by_account_id
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13,
    $14, $15
) RETURNING id, event_id, shift_id, requirement_id, person_id, first_name_snapshot, last_name_snapshot, email_snapshot, email_normalized, phone_snapshot, phone_normalized, source, status, created_by_account_id, management_token_digest, conflict_overridden_by_account_id, cancelled_at, cancelled_by_account_id, personal_data_erased_at, version, created_at, updated_at
`

type CreateEventAssignmentParams struct {
	ID                            uuid.UUID
	EventID                       uuid.UUID
	ShiftID                       uuid.UUID
	RequirementID                 uuid.UUID
	PersonID                      *uuid.UUID
	FirstNameSnapshot             *string
	LastNameSnapshot              *string
	EmailSnapshot                 *string
	EmailNormalized               *string
	PhoneSnapshot                 *string
	PhoneNormalized               *string
	Source                        string
	CreatedByAccountID            *uuid.UUID
	ManagementTokenDigest         []byte
	ConflictOverriddenByAccountID *uuid.UUID
}

func (q *Queries) CreateEventAssignment(ctx context.Context, arg CreateEventAssignmentParams) (EventShiftAssignment, error) {
	row := q.db.QueryRow(ctx, createEventAssignment,
		arg.ID,
		arg.EventID,
		arg.ShiftID,
		arg.RequirementID,
		arg.PersonID,
		arg.FirstNameSnapshot,
		arg.LastNameSnapshot,
		arg.EmailSnapshot,
		arg.EmailNormalized,
		arg.PhoneSnapshot,
		arg.PhoneNormalized,
		arg.Source,
		arg.CreatedByAccountID,
		arg.ManagementTokenDigest,
		arg.ConflictOverriddenByAccountID,
	)
	var i EventShiftAssignment
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ShiftID,
		&i.RequirementID,
		&i.PersonID,
		&i.FirstNameSnapshot,
		&i.LastNameSnapshot,
		&i.EmailSnapshot,
		&i.EmailNormalized,
		&i.PhoneSnapshot,
		&i.PhoneNormalized,
		&i.Source,
		&i.Status,
		&i.CreatedByAccountID,
		&i.ManagementTokenDigest,
		&i.ConflictOverriddenByAccountID,
		&i.CancelledAt,
		&i.CancelledByAccountID,
		&i.PersonalDataErasedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEventFile = `-- name: CreateEventFile :one
INSERT INTO event_files (id, event_id, file_id, description, visibility, is_banner)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, event_id, file_id, description, visibility, version, created_at, updated_at, is_banner
`

type CreateEventFileParams struct {
	ID          uuid.UUID
	EventID     uuid.UUID
	FileID      uuid.UUID
	Description *string
	Visibility  string
	IsBanner    bool
}

func (q *Queries) CreateEventFile(ctx context.Context, arg CreateEventFileParams) (EventFile, error) {
	row := q.db.QueryRow(ctx, createEventFile,
		arg.ID,
		arg.EventID,
		arg.FileID,
		arg.Description,
		arg.Visibility,
		arg.IsBanner,
	)
	var i EventFile
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.FileID,
		&i.Description,
		&i.Visibility,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsBanner,
	)
	return i, err
}

const createEventRequirement = `-- name: CreateEventRequirement :one
INSERT INTO event_shift_requirements (id, event_id, shift_id, name, description, required_count, eligibility_mode)
VALUES ($1, $2, $3, $4, $5,
        $6, $7) RETURNING id, event_id, shift_id, name, description, required_count, eligibility_mode, version, created_at, updated_at
`

type CreateEventRequirementParams struct {
	ID              uuid.UUID
	EventID         uuid.UUID
	ShiftID         uuid.UUID
	Name            string
	Description     *string
	RequiredCount   int32
	EligibilityMode string
}

func (q *Queries) CreateEventRequirement(ctx context.Context, arg CreateEventRequirementParams) (EventShiftRequirement, error) {
	row := q.db.QueryRow(ctx, createEventRequirement,
		arg.ID,
		arg.EventID,
		arg.ShiftID,
		arg.Name,
		arg.Description,
		arg.RequiredCount,
		arg.EligibilityMode,
	)
	var i EventShiftRequirement
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ShiftID,
		&i.Name,
		&i.Description,
		&i.RequiredCount,
		&i.EligibilityMode,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEventSession = `-- name: CreateEventSession :one
INSERT INTO event_sessions (id, event_id, name, location, description, starts_at, ends_at, is_public, status)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9)
RETURNING id, event_id, name, location, description, starts_at, ends_at, is_public, status, version, created_at, updated_at
`

type CreateEventSessionParams struct {
	ID          uuid.UUID
	EventID     uuid.UUID
	Name        *string
	Location    *string
	Description *string
	StartsAt    time.Time
	EndsAt      time.Time
	IsPublic    bool
	Status      string
}

func (q *Queries) CreateEventSession(ctx context.Context, arg CreateEventSessionParams) (EventSession, error) {
	row := q.db.QueryRow(ctx, createEventSession,
		arg.ID,
		arg.EventID,
		arg.Name,
		arg.Location,
		arg.Description,
		arg.StartsAt,
		arg.EndsAt,
		arg.IsPublic,
		arg.Status,
	)
	var i EventSession
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Location,
		&i.Description,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsPublic,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEventShift = `-- name: CreateEventShift :one
INSERT INTO event_shifts (
    id, event_id, session_id, name, description, starts_at, ends_at,
    signup_opens_at, signup_closes_at, is_public, status
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11
) RETURNING id, event_id, session_id, name, description, starts_at, ends_at, signup_opens_at, signup_closes_at, is_public, status, version, created_at, updated_at
`

type CreateEventShiftParams struct {
	ID             uuid.UUID
	EventID        uuid.UUID
	SessionID      *uuid.UUID
	Name           string
	Description    *string
	StartsAt       time.Time
	EndsAt         time.Time
	SignupOpensAt  pgtype.Timestamptz
	SignupClosesAt pgtype.Timestamptz
	IsPublic       bool
	Status         string
}

func (q *Queries) CreateEventShift(ctx context.Context, arg CreateEventShiftParams) (EventShift, error) {
	row := q.db.QueryRow(ctx, createEventShift,
		arg.ID,
		arg.EventID,
		arg.SessionID,
		arg.Name,
		arg.Description,
		arg.StartsAt,
		arg.EndsAt,
		arg.SignupOpensAt,
		arg.SignupClosesAt,
		arg.IsPublic,
		arg.Status,
	)
	var i EventShift
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.SessionID,
		&i.Name,
		&i.Description,
		&i.StartsAt,
		&i.EndsAt,
		&i.SignupOpensAt,
		&i.SignupClosesAt,
		&i.IsPublic,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEventTask = `-- name: CreateEventTask :one
INSERT INTO event_tasks (
    id, event_id, task_list_id, title, description, status, priority, assignee_person_id,
    due_at, completed_at, completed_by_account_id, sort_order, created_by_account_id
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13
) RETURNING id, event_id, task_list_id, title, description, status, priority, assignee_person_id, due_at, completed_at, completed_by_account_id, sort_order, created_by_account_id, version, created_at, updated_at
`

type CreateEventTaskParams struct {
	ID                   uuid.UUID
	EventID              uuid.UUID
	TaskListID           *uuid.UUID
	Title                string
	Description          *string
	Status               string
	Priority             string
	AssigneePersonID     *uuid.UUID
	DueAt                pgtype.Timestamptz
	CompletedAt          pgtype.Timestamptz
	CompletedByAccountID *uuid.UUID
	SortOrder            int32
	CreatedByAccountID   *uuid.UUID
}

func (q *Queries) CreateEventTask(ctx context.Context, arg CreateEventTaskParams) (EventTask, error) {
	row := q.db.QueryRow(ctx, createEventTask,
		arg.ID,
		arg.EventID,
		arg.TaskListID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.AssigneePersonID,
		arg.DueAt,
		arg.CompletedAt,
		arg.CompletedByAccountID,
		arg.SortOrder,
		arg.CreatedByAccountID,
	)
	var i EventTask
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.TaskListID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneePersonID,
		&i.DueAt,
		&i.CompletedAt,
		&i.CompletedByAccountID,
		&i.SortOrder,
		&i.CreatedByAccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEventTaskList = `-- name: CreateEventTaskList :one
INSERT INTO event_task_lists (id, event_id, name, description, sort_order)
VALUES ($1, $2, $3, $4, $5) RETURNING id, event_id, name, description, sort_order, version, created_at, updated_at
`

type CreateEventTaskListParams struct {
	ID          uuid.UUID
	EventID     uuid.UUID
	Name        string
	Description *string
	SortOrder   int32
}

func (q *Queries) CreateEventTaskList(ctx context.Context, arg CreateEventTaskListParams) (EventTaskList, error) {
	row := q.db.QueryRow(ctx, createEventTaskList,
		arg.ID,
		arg.EventID,
		arg.Name,
		arg.Description,
		arg.SortOrder,
	)
	var i EventTaskList
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDraftEvent = `-- name: DeleteDraftEvent :one
DELETE FROM events
WHERE id = $1 AND version = $2 AND status = 'draft'
RETURNING id
`

type DeleteDraftEventParams struct {
	ID              uuid.UUID
	ExpectedVersion int32
}

func (q *Queries) DeleteDraftEvent(ctx context.Context, arg DeleteDraftEventParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteDraftEvent, arg.ID, arg.ExpectedVersion)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteEventFile = `-- name: DeleteEventFile :one
DELETE FROM event_files
WHERE id = $1 AND event_id = $2 AND version = $3
RETURNING file_id
`

type DeleteEventFileParams struct {
	ID              uuid.UUID
	EventID         uuid.UUID
	ExpectedVersion int32
}

func (q *Queries) DeleteEventFile(ctx context.Context, arg DeleteEventFileParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteEventFile, arg.ID, arg.EventID, arg.ExpectedVersion)
	var file_id uuid.UUID
	err := row.Scan(&file_id)
	return file_id, err
}

const deleteEventRequirement = `-- name: DeleteEventRequirement :one
DELETE FROM event_shift_requirements
WHERE id = $1 AND shift_id = $2 AND event_id = $3
  AND version = $4
RETURNING id
`

type DeleteEventRequirementParams struct {
	ID              uuid.UUID
	ShiftID         uuid.UUID
	EventID         uuid.UUID
	ExpectedVersion int32
}

func (q *Queries) DeleteEventRequirement(ctx context.Context, arg DeleteEventRequirementParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteEventRequirement,
		arg.ID,
		arg.ShiftID,
		arg.EventID,
		arg.ExpectedVersion,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteEventSession = `-- name: DeleteEventSession :one
DELETE FROM event_sessions
WHERE id = $1 AND event_id = $2 AND version = $3
RETURNING id
`

type DeleteEventSessionParams struct {
	ID              uuid.UUID
	EventID         uuid.UUID
	ExpectedVersion int32
}

func (q *Queries) DeleteEventSession(ctx context.Context, arg DeleteEventSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteEventSession, arg.ID, arg.EventID, arg.ExpectedVersion)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteEventShift = `-- name: DeleteEventShift :one
DELETE FROM event_shifts
WHERE id = $1 AND event_id = $2 AND version = $3
RETURNING id
`

type DeleteEventShiftParams struct {
	ID              uuid.UUID
	EventID         uuid.UUID
	ExpectedVersion int32
}

func (q *Queries) DeleteEventShift(ctx context.Context, arg DeleteEventShiftParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteEventShift, arg.ID, arg.EventID, arg.ExpectedVersion)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteEventTask = `-- name: DeleteEventTask :one
DELETE FROM event_tasks
WHERE id = $1 AND event_id = $2 AND version = $3
RETURNING id
`

type DeleteEventTaskParams struct {
	ID              uuid.UUID
	EventID         uuid.UUID
	ExpectedVersion int32
}

func (q *Queries) DeleteEventTask(ctx context.Context, arg DeleteEventTaskParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteEventTask, arg.ID, arg.EventID, arg.ExpectedVersion)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteEventTaskList = `-- name: DeleteEventTaskList :one
DELETE FROM event_task_lists
WHERE id = $1 AND event_id = $2 AND version = $3
RETURNING id
`

type DeleteEventTaskListParams struct {
	ID              uuid.UUID
	EventID         uuid.UUID
	ExpectedVersion int32
}

func (q *Queries) DeleteEventTaskList(ctx context.Context, arg DeleteEventTaskListParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteEventTaskList, arg.ID, arg.EventID, arg.ExpectedVersion)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const eraseEventAssignmentPersonalData = `-- name: EraseEventAssignmentPersonalData :one
UPDATE event_shift_assignments
SET first_name_snapshot = NULL, last_name_snapshot = NULL,
    email_snapshot = NULL, email_normalized = NULL, phone_snapshot = NULL, phone_normalized = NULL,
    management_token_digest = NULL, personal_data_erased_at = now(),
    version = version + 1, updated_at = now()
WHERE id = $1 AND personal_data_erased_at IS NULL
RETURNING id, event_id, shift_id, requirement_id, person_id, first_name_snapshot, last_name_snapshot, email_snapshot, email_normalized, phone_snapshot, phone_normalized, source, status, created_by_account_id, management_token_digest, conflict_overridden_by_account_id, cancelled_at, cancelled_by_account_id, personal_data_erased_at, version, created_at, updated_at
`

func (q *Queries) EraseEventAssignmentPersonalData(ctx context.Context, id uuid.UUID) (EventShiftAssignment, error) {
	row := q.db.QueryRow(ctx, eraseEventAssignmentPersonalData, id)
	var i EventShiftAssignment
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ShiftID,
		&i.RequirementID,
		&i.PersonID,
		&i.FirstNameSnapshot,
		&i.LastNameSnapshot,
		&i.EmailSnapshot,
		&i.EmailNormalized,
		&i.PhoneSnapshot,
		&i.PhoneNormalized,
		&i.Source,
		&i.Status,
		&i.CreatedByAccountID,
		&i.ManagementTokenDigest,
		&i.ConflictOverriddenByAccountID,
		&i.CancelledAt,
		&i.CancelledByAccountID,
		&i.PersonalDataErasedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const eventBannerExists = `-- name: EventBannerExists :one
SELECT EXISTS (
    SELECT 1 FROM event_files WHERE event_id = $1 AND is_banner
)
`

func (q *Queries) EventBannerExists(ctx context.Context, eventID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, eventBannerExists, eventID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const eventPublicationFacts = `-- name: EventPublicationFacts :one
SELECT
    EXISTS (SELECT 1 FROM event_sessions es WHERE es.event_id = $1 AND es.status = 'scheduled') AS has_session,
    EXISTS (SELECT 1 FROM event_shifts esh WHERE esh.event_id = $1 AND esh.status <> 'cancelled') AS has_shift,
    EXISTS (SELECT 1 FROM event_sessions es WHERE es.event_id = $1 AND es.status = 'scheduled' AND es.is_public) AS has_public_session,
    EXISTS (SELECT 1 FROM event_shifts esh WHERE esh.event_id = $1 AND esh.status <> 'cancelled' AND esh.is_public) AS has_public_shift,
    EXISTS (
        SELECT 1 FROM event_shifts sh
        JOIN event_shift_requirements r ON r.shift_id = sh.id
        WHERE sh.event_id = $1 AND sh.status <> 'cancelled' AND sh.is_public
    ) AS has_public_requirement
`

type EventPublicationFactsRow struct {
	HasSession           bool
	HasShift             bool
	HasPublicSession     bool
	HasPublicShift       bool
	HasPublicRequirement bool
}

func (q *Queries) EventPublicationFacts(ctx context.Context, eventID uuid.UUID) (EventPublicationFactsRow, error) {
	row := q.db.QueryRow(ctx, eventPublicationFacts, eventID)
	var i EventPublicationFactsRow
	err := row.Scan(
		&i.HasSession,
		&i.HasShift,
		&i.HasPublicSession,
		&i.HasPublicShift,
		&i.HasPublicRequirement,
	)
	return i, err
}

const eventTaskSummary = `-- name: EventTaskSummary :one
SELECT count(*)::bigint AS total,
       count(*) FILTER (WHERE status = 'done')::bigint AS completed
FROM event_tasks WHERE event_id = $1
`

type EventTaskSummaryRow struct {
	Total     int64
	Completed int64
}

func (q *Queries) EventTaskSummary(ctx context.Context, eventID uuid.UUID) (EventTaskSummaryRow, error) {
	row := q.db.QueryRow(ctx, eventTaskSummary, eventID)
	var i EventTaskSummaryRow
	err := row.Scan(&i.Total, &i.Completed)
	return i, err
}

const findContactEventShiftConflicts = `-- name: FindContactEventShiftConflicts :many
SELECT a.id, sh.starts_at, sh.ends_at
FROM event_shift_assignments a
JOIN event_shifts sh ON sh.id = a.shift_id
WHERE a.status = 'active' AND a.id <> $1
  AND sh.status <> 'cancelled'
  AND (($2::text IS NOT NULL AND a.email_normalized = $2)
       OR ($3::text IS NOT NULL AND a.phone_normalized = $3))
  AND sh.starts_at < $4 AND sh.ends_at > $5
ORDER BY sh.starts_at, a.id
`

type FindContactEventShiftConflictsParams struct {
	ExcludeAssignmentID uuid.UUID
	EmailNormalized     *string
	PhoneNormalized     *string
	EndsAt              time.Time
	StartsAt            time.Time
}

type FindContactEventShiftConflictsRow struct {
	ID       uuid.UUID
	StartsAt time.Time
	EndsAt   time.Time
}

func (q *Queries) FindContactEventShiftConflicts(ctx context.Context, arg FindContactEventShiftConflictsParams) ([]FindContactEventShiftConflictsRow, error) {
	rows, err := q.db.Query(ctx, findContactEventShiftConflicts,
		arg.ExcludeAssignmentID,
		arg.EmailNormalized,
		arg.PhoneNormalized,
		arg.EndsAt,
		arg.StartsAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindContactEventShiftConflictsRow{}
	for rows.Next() {
		var i FindContactEventShiftConflictsRow
		if err := rows.Scan(&i.ID, &i.StartsAt, &i.EndsAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findEventPeople = `-- name: FindEventPeople :many
SELECT p.id, p.first_name, p.last_name, p.email, p.phone
FROM people p
WHERE $1::text = ''
   OR lower(p.first_name || ' ' || p.last_name) LIKE '%' || lower($1::text) || '%'
   OR lower(COALESCE(p.email, '')) = lower($1::text)
   OR COALESCE(p.phone, '') = $1::text
ORDER BY p.last_name, p.first_name, p.id
LIMIT $2
`

type FindEventPeopleParams struct {
	Search    string
	PageLimit int32
}

type FindEventPeopleRow struct {
	ID        uuid.UUID
	FirstName string
	LastName  string
	Email     *string
	Phone     *string
}

func (q *Queries) FindEventPeople(ctx context.Context, arg FindEventPeopleParams) ([]FindEventPeopleRow, error) {
	rows, err := q.db.Query(ctx, findEventPeople, arg.Search, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindEventPeopleRow{}
	for rows.Next() {
		var i FindEventPeopleRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findEventPeopleByExactContact = `-- name: FindEventPeopleByExactContact :many
WITH normalized_people AS (
    SELECT p.id, p.first_name, p.last_name, p.email, p.phone, p.matriculation_number, p.photo_reference, p.version, p.created_at, p.updated_at, p.profile_image_file_id, p.profile_image_source,
           lower(btrim(p.email)) AS normalized_email,
           CASE
               WHEN regexp_replace(p.phone, '[^0-9+]', '', 'g') LIKE '00%'
                   THEN '+' || substr(regexp_replace(p.phone, '[^0-9+]', '', 'g'), 3)
               ELSE regexp_replace(p.phone, '[^0-9+]', '', 'g')
           END AS normalized_phone
    FROM people p
)
SELECT p.id, p.first_name, p.last_name, p.email, p.phone
FROM normalized_people p
WHERE ($1::text IS NOT NULL AND p.normalized_email = $1)
   OR ($2::text IS NOT NULL AND p.normalized_phone = $2)
ORDER BY p.last_name, p.first_name, p.id
LIMIT 20
`

type FindEventPeopleByExactContactParams struct {
	EmailNormalized *string
	PhoneNormalized *string
}

type FindEventPeopleByExactContactRow struct {
	ID        uuid.UUID
	FirstName string
	LastName  string
	Email     *string
	Phone     *string
}

func (q *Queries) FindEventPeopleByExactContact(ctx context.Context, arg FindEventPeopleByExactContactParams) ([]FindEventPeopleByExactContactRow, error) {
	rows, err := q.db.Query(ctx, findEventPeopleByExactContact, arg.EmailNormalized, arg.PhoneNormalized)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindEventPeopleByExactContactRow{}
	for rows.Next() {
		var i FindEventPeopleByExactContactRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPersonEventShiftConflicts = `-- name: FindPersonEventShiftConflicts :many
SELECT a.id, sh.starts_at, sh.ends_at
FROM event_shift_assignments a
JOIN event_shifts sh ON sh.id = a.shift_id
WHERE a.person_id = $1 AND a.status = 'active'
  AND a.id <> $2
  AND sh.status <> 'cancelled'
  AND sh.starts_at < $3 AND sh.ends_at > $4
ORDER BY sh.starts_at, a.id
`

type FindPersonEventShiftConflictsParams struct {
	PersonID            *uuid.UUID
	ExcludeAssignmentID uuid.UUID
	EndsAt              time.Time
	StartsAt            time.Time
}

type FindPersonEventShiftConflictsRow struct {
	ID       uuid.UUID
	StartsAt time.Time
	EndsAt   time.Time
}

func (q *Queries) FindPersonEventShiftConflicts(ctx context.Context, arg FindPersonEventShiftConflictsParams) ([]FindPersonEventShiftConflictsRow, error) {
	rows, err := q.db.Query(ctx, findPersonEventShiftConflicts,
		arg.PersonID,
		arg.ExcludeAssignmentID,
		arg.EndsAt,
		arg.StartsAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindPersonEventShiftConflictsRow{}
	for rows.Next() {
		var i FindPersonEventShiftConflictsRow
		if err := rows.Scan(&i.ID, &i.StartsAt, &i.EndsAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEvent = `-- name: GetEvent :one
SELECT id, name, internal_description, location, owner_person_id, status, public_title, public_description, public_location, public_id, is_public, public_signup_enabled, closed_at, created_by_account_id, version, created_at, updated_at FROM events WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InternalDescription,
		&i.Location,
		&i.OwnerPersonID,
		&i.Status,
		&i.PublicTitle,
		&i.PublicDescription,
		&i.PublicLocation,
		&i.PublicID,
		&i.IsPublic,
		&i.PublicSignupEnabled,
		&i.ClosedAt,
		&i.CreatedByAccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventAssignment = `-- name: GetEventAssignment :one
SELECT id, event_id, shift_id, requirement_id, person_id, first_name_snapshot, last_name_snapshot, email_snapshot, email_normalized, phone_snapshot, phone_normalized, source, status, created_by_account_id, management_token_digest, conflict_overridden_by_account_id, cancelled_at, cancelled_by_account_id, personal_data_erased_at, version, created_at, updated_at FROM event_shift_assignments WHERE id = $1 AND event_id = $2
`

type GetEventAssignmentParams struct {
	ID      uuid.UUID
	EventID uuid.UUID
}

func (q *Queries) GetEventAssignment(ctx context.Context, arg GetEventAssignmentParams) (EventShiftAssignment, error) {
	row := q.db.QueryRow(ctx, getEventAssignment, arg.ID, arg.EventID)
	var i EventShiftAssignment
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ShiftID,
		&i.RequirementID,
		&i.PersonID,
		&i.FirstNameSnapshot,
		&i.LastNameSnapshot,
		&i.EmailSnapshot,
		&i.EmailNormalized,
		&i.PhoneSnapshot,
		&i.PhoneNormalized,
		&i.Source,
		&i.Status,
		&i.CreatedByAccountID,
		&i.ManagementTokenDigest,
		&i.ConflictOverriddenByAccountID,
		&i.CancelledAt,
		&i.CancelledByAccountID,
		&i.PersonalDataErasedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventAssignmentByTokenDigest = `-- name: GetEventAssignmentByTokenDigest :one
SELECT id, event_id, shift_id, requirement_id, person_id, first_name_snapshot, last_name_snapshot, email_snapshot, email_normalized, phone_snapshot, phone_normalized, source, status, created_by_account_id, management_token_digest, conflict_overridden_by_account_id, cancelled_at, cancelled_by_account_id, personal_data_erased_at, version, created_at, updated_at FROM event_shift_assignments WHERE management_token_digest = $1
`

func (q *Queries) GetEventAssignmentByTokenDigest(ctx context.Context, managementTokenDigest []byte) (EventShiftAssignment, error) {
	row := q.db.QueryRow(ctx, getEventAssignmentByTokenDigest, managementTokenDigest)
	var i EventShiftAssignment
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ShiftID,
		&i.RequirementID,
		&i.PersonID,
		&i.FirstNameSnapshot,
		&i.LastNameSnapshot,
		&i.EmailSnapshot,
		&i.EmailNormalized,
		&i.PhoneSnapshot,
		&i.PhoneNormalized,
		&i.Source,
		&i.Status,
		&i.CreatedByAccountID,
		&i.ManagementTokenDigest,
		&i.ConflictOverriddenByAccountID,
		&i.CancelledAt,
		&i.CancelledByAccountID,
		&i.PersonalDataErasedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventAssignmentByTokenDigestForUpdate = `-- name: GetEventAssignmentByTokenDigestForUpdate :one
SELECT id, event_id, shift_id, requirement_id, person_id, first_name_snapshot, last_name_snapshot, email_snapshot, email_normalized, phone_snapshot, phone_normalized, source, status, created_by_account_id, management_token_digest, conflict_overridden_by_account_id, cancelled_at, cancelled_by_account_id, personal_data_erased_at, version, created_at, updated_at FROM event_shift_assignments WHERE management_token_digest = $1 FOR UPDATE
`

func (q *Queries) GetEventAssignmentByTokenDigestForUpdate(ctx context.Context, managementTokenDigest []byte) (EventShiftAssignment, error) {
	row := q.db.QueryRow(ctx, getEventAssignmentByTokenDigestForUpdate, managementTokenDigest)
	var i EventShiftAssignment
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ShiftID,
		&i.RequirementID,
		&i.PersonID,
		&i.FirstNameSnapshot,
		&i.LastNameSnapshot,
		&i.EmailSnapshot,
		&i.EmailNormalized,
		&i.PhoneSnapshot,
		&i.PhoneNormalized,
		&i.Source,
		&i.Status,
		&i.CreatedByAccountID,
		&i.ManagementTokenDigest,
		&i.ConflictOverriddenByAccountID,
		&i.CancelledAt,
		&i.CancelledByAccountID,
		&i.PersonalDataErasedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventAssignmentForUpdate = `-- name: GetEventAssignmentForUpdate :one
SELECT id, event_id, shift_id, requirement_id, person_id, first_name_snapshot, last_name_snapshot, email_snapshot, email_normalized, phone_snapshot, phone_normalized, source, status, created_by_account_id, management_token_digest, conflict_overridden_by_account_id, cancelled_at, cancelled_by_account_id, personal_data_erased_at, version, created_at, updated_at FROM event_shift_assignments WHERE id = $1 AND event_id = $2 FOR UPDATE
`

type GetEventAssignmentForUpdateParams struct {
	ID      uuid.UUID
	EventID uuid.UUID
}

func (q *Queries) GetEventAssignmentForUpdate(ctx context.Context, arg GetEventAssignmentForUpdateParams) (EventShiftAssignment, error) {
	row := q.db.QueryRow(ctx, getEventAssignmentForUpdate, arg.ID, arg.EventID)
	var i EventShiftAssignment
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ShiftID,
		&i.RequirementID,
		&i.PersonID,
		&i.FirstNameSnapshot,
		&i.LastNameSnapshot,
		&i.EmailSnapshot,
		&i.EmailNormalized,
		&i.PhoneSnapshot,
		&i.PhoneNormalized,
		&i.Source,
		&i.Status,
		&i.CreatedByAccountID,
		&i.ManagementTokenDigest,
		&i.ConflictOverriddenByAccountID,
		&i.CancelledAt,
		&i.CancelledByAccountID,
		&i.PersonalDataErasedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventBanner = `-- name: GetEventBanner :one
SELECT ef.id, ef.event_id, ef.file_id, ef.description, ef.visibility, ef.version, ef.created_at, ef.updated_at, ef.is_banner, f.original_filename, f.content_type, f.size_bytes, f.storage_key
FROM event_files ef JOIN files f ON f.id = ef.file_id
WHERE ef.event_id = $1 AND ef.is_banner
`

type GetEventBannerRow struct {
	ID               uuid.UUID
	EventID          uuid.UUID
	FileID           uuid.UUID
	Description      *string
	Visibility       string
	Version          int32
	CreatedAt        time.Time
	UpdatedAt        time.Time
	IsBanner         bool
	OriginalFilename string
	ContentType      string
	SizeBytes        int64
	StorageKey       string
}

func (q *Queries) GetEventBanner(ctx context.Context, eventID uuid.UUID) (GetEventBannerRow, error) {
	row := q.db.QueryRow(ctx, getEventBanner, eventID)
	var i GetEventBannerRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.FileID,
		&i.Description,
		&i.Visibility,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsBanner,
		&i.OriginalFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
	)
	return i, err
}

const getEventByPublicID = `-- name: GetEventByPublicID :one
SELECT id, name, internal_description, location, owner_person_id, status, public_title, public_description, public_location, public_id, is_public, public_signup_enabled, closed_at, created_by_account_id, version, created_at, updated_at FROM events WHERE public_id = $1 AND is_public
`

func (q *Queries) GetEventByPublicID(ctx context.Context, publicID string) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByPublicID, publicID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InternalDescription,
		&i.Location,
		&i.OwnerPersonID,
		&i.Status,
		&i.PublicTitle,
		&i.PublicDescription,
		&i.PublicLocation,
		&i.PublicID,
		&i.IsPublic,
		&i.PublicSignupEnabled,
		&i.ClosedAt,
		&i.CreatedByAccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventFile = `-- name: GetEventFile :one
SELECT ef.id, ef.event_id, ef.file_id, ef.description, ef.visibility, ef.version, ef.created_at, ef.updated_at, ef.is_banner, f.original_filename, f.content_type, f.size_bytes, f.storage_key
FROM event_files ef JOIN files f ON f.id = ef.file_id
WHERE ef.id = $1 AND ef.event_id = $2
`

type GetEventFileParams struct {
	ID      uuid.UUID
	EventID uuid.UUID
}

type GetEventFileRow struct {
	ID               uuid.UUID
	EventID          uuid.UUID
	FileID           uuid.UUID
	Description      *string
	Visibility       string
	Version          int32
	CreatedAt        time.Time
	UpdatedAt        time.Time
	IsBanner         bool
	OriginalFilename string
	ContentType      string
	SizeBytes        int64
	StorageKey       string
}

func (q *Queries) GetEventFile(ctx context.Context, arg GetEventFileParams) (GetEventFileRow, error) {
	row := q.db.QueryRow(ctx, getEventFile, arg.ID, arg.EventID)
	var i GetEventFileRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.FileID,
		&i.Description,
		&i.Visibility,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsBanner,
		&i.OriginalFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
	)
	return i, err
}

const getEventForUpdate = `-- name: GetEventForUpdate :one
SELECT id, name, internal_description, location, owner_person_id, status, public_title, public_description, public_location, public_id, is_public, public_signup_enabled, closed_at, created_by_account_id, version, created_at, updated_at FROM events WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetEventForUpdate(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEventForUpdate, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InternalDescription,
		&i.Location,
		&i.OwnerPersonID,
		&i.Status,
		&i.PublicTitle,
		&i.PublicDescription,
		&i.PublicLocation,
		&i.PublicID,
		&i.IsPublic,
		&i.PublicSignupEnabled,
		&i.ClosedAt,
		&i.CreatedByAccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventPerson = `-- name: GetEventPerson :one
SELECT id, first_name, last_name, email, phone FROM people WHERE id = $1
`

type GetEventPersonRow struct {
	ID        uuid.UUID
	FirstName string
	LastName  string
	Email     *string
	Phone     *string
}

func (q *Queries) GetEventPerson(ctx context.Context, id uuid.UUID) (GetEventPersonRow, error) {
	row := q.db.QueryRow(ctx, getEventPerson, id)
	var i GetEventPersonRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
	)
	return i, err
}

const getEventRequirement = `-- name: GetEventRequirement :one
SELECT id, event_id, shift_id, name, description, required_count, eligibility_mode, version, created_at, updated_at FROM event_shift_requirements
WHERE id = $1 AND shift_id = $2 AND event_id = $3
`

type GetEventRequirementParams struct {
	ID      uuid.UUID
	ShiftID uuid.UUID
	EventID uuid.UUID
}

func (q *Queries) GetEventRequirement(ctx context.Context, arg GetEventRequirementParams) (EventShiftRequirement, error) {
	row := q.db.QueryRow(ctx, getEventRequirement, arg.ID, arg.ShiftID, arg.EventID)
	var i EventShiftRequirement
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ShiftID,
		&i.Name,
		&i.Description,
		&i.RequiredCount,
		&i.EligibilityMode,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventRequirementForUpdate = `-- name: GetEventRequirementForUpdate :one
SELECT id, event_id, shift_id, name, description, required_count, eligibility_mode, version, created_at, updated_at FROM event_shift_requirements
WHERE id = $1 AND shift_id = $2 AND event_id = $3
FOR UPDATE
`

type GetEventRequirementForUpdateParams struct {
	ID      uuid.UUID
	ShiftID uuid.UUID
	EventID uuid.UUID
}

func (q *Queries) GetEventRequirementForUpdate(ctx context.Context, arg GetEventRequirementForUpdateParams) (EventShiftRequirement, error) {
	row := q.db.QueryRow(ctx, getEventRequirementForUpdate, arg.ID, arg.ShiftID, arg.EventID)
	var i EventShiftRequirement
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ShiftID,
		&i.Name,
		&i.Description,
		&i.RequiredCount,
		&i.EligibilityMode,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventSession = `-- name: GetEventSession :one
SELECT id, event_id, name, location, description, starts_at, ends_at, is_public, status, version, created_at, updated_at FROM event_sessions WHERE id = $1 AND event_id = $2
`

type GetEventSessionParams struct {
	ID      uuid.UUID
	EventID uuid.UUID
}

func (q *Queries) GetEventSession(ctx context.Context, arg GetEventSessionParams) (EventSession, error) {
	row := q.db.QueryRow(ctx, getEventSession, arg.ID, arg.EventID)
	var i EventSession
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Location,
		&i.Description,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsPublic,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventShift = `-- name: GetEventShift :one
SELECT sh.id, sh.event_id, sh.session_id, sh.name, sh.description, sh.starts_at, sh.ends_at, sh.signup_opens_at, sh.signup_closes_at, sh.is_public, sh.status, sh.version, sh.created_at, sh.updated_at, s.status AS session_status
FROM event_shifts sh
LEFT JOIN event_sessions s ON s.id = sh.session_id
WHERE sh.id = $1 AND sh.event_id = $2
`

type GetEventShiftParams struct {
	ID      uuid.UUID
	EventID uuid.UUID
}

type GetEventShiftRow struct {
	ID             uuid.UUID
	EventID        uuid.UUID
	SessionID      *uuid.UUID
	Name           string
	Description    *string
	StartsAt       time.Time
	EndsAt         time.Time
	SignupOpensAt  pgtype.Timestamptz
	SignupClosesAt pgtype.Timestamptz
	IsPublic       bool
	Status         string
	Version        int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
	SessionStatus  *string
}

func (q *Queries) GetEventShift(ctx context.Context, arg GetEventShiftParams) (GetEventShiftRow, error) {
	row := q.db.QueryRow(ctx, getEventShift, arg.ID, arg.EventID)
	var i GetEventShiftRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.SessionID,
		&i.Name,
		&i.Description,
		&i.StartsAt,
		&i.EndsAt,
		&i.SignupOpensAt,
		&i.SignupClosesAt,
		&i.IsPublic,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SessionStatus,
	)
	return i, err
}

const getEventTask = `-- name: GetEventTask :one
SELECT id, event_id, task_list_id, title, description, status, priority, assignee_person_id, due_at, completed_at, completed_by_account_id, sort_order, created_by_account_id, version, created_at, updated_at FROM event_tasks WHERE id = $1 AND event_id = $2
`

type GetEventTaskParams struct {
	ID      uuid.UUID
	EventID uuid.UUID
}

func (q *Queries) GetEventTask(ctx context.Context, arg GetEventTaskParams) (EventTask, error) {
	row := q.db.QueryRow(ctx, getEventTask, arg.ID, arg.EventID)
	var i EventTask
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.TaskListID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneePersonID,
		&i.DueAt,
		&i.CompletedAt,
		&i.CompletedByAccountID,
		&i.SortOrder,
		&i.CreatedByAccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventTaskList = `-- name: GetEventTaskList :one
SELECT id, event_id, name, description, sort_order, version, created_at, updated_at FROM event_task_lists WHERE id = $1 AND event_id = $2
`

type GetEventTaskListParams struct {
	ID      uuid.UUID
	EventID uuid.UUID
}

func (q *Queries) GetEventTaskList(ctx context.Context, arg GetEventTaskListParams) (EventTaskList, error) {
	row := q.db.QueryRow(ctx, getEventTaskList, arg.ID, arg.EventID)
	var i EventTaskList
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublicEventBanner = `-- name: GetPublicEventBanner :one
SELECT ef.id, ef.event_id, ef.file_id, ef.description, ef.visibility, ef.version, ef.created_at, ef.updated_at, ef.is_banner, f.original_filename, f.content_type, f.size_bytes, f.storage_key
FROM event_files ef JOIN files f ON f.id = ef.file_id JOIN events e ON e.id = ef.event_id
WHERE e.public_id = $1 AND e.is_public AND ef.is_banner AND ef.visibility = 'public'
`

type GetPublicEventBannerRow struct {
	ID               uuid.UUID
	EventID          uuid.UUID
	FileID           uuid.UUID
	Description      *string
	Visibility       string
	Version          int32
	CreatedAt        time.Time
	UpdatedAt        time.Time
	IsBanner         bool
	OriginalFilename string
	ContentType      string
	SizeBytes        int64
	StorageKey       string
}

func (q *Queries) GetPublicEventBanner(ctx context.Context, publicID string) (GetPublicEventBannerRow, error) {
	row := q.db.QueryRow(ctx, getPublicEventBanner, publicID)
	var i GetPublicEventBannerRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.FileID,
		&i.Description,
		&i.Visibility,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsBanner,
		&i.OriginalFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
	)
	return i, err
}

const getPublicEventFile = `-- name: GetPublicEventFile :one
SELECT ef.id, ef.event_id, ef.file_id, ef.description, ef.visibility, ef.version, ef.created_at, ef.updated_at, ef.is_banner, f.original_filename, f.content_type, f.size_bytes, f.storage_key
FROM event_files ef JOIN files f ON f.id = ef.file_id JOIN events e ON e.id = ef.event_id
WHERE ef.id = $1 AND e.public_id = $2 AND e.is_public AND ef.visibility = 'public'
`

type GetPublicEventFileParams struct {
	ID       uuid.UUID
	PublicID string
}

type GetPublicEventFileRow struct {
	ID               uuid.UUID
	EventID          uuid.UUID
	FileID           uuid.UUID
	Description      *string
	Visibility       string
	Version          int32
	CreatedAt        time.Time
	UpdatedAt        time.Time
	IsBanner         bool
	OriginalFilename string
	ContentType      string
	SizeBytes        int64
	StorageKey       string
}

func (q *Queries) GetPublicEventFile(ctx context.Context, arg GetPublicEventFileParams) (GetPublicEventFileRow, error) {
	row := q.db.QueryRow(ctx, getPublicEventFile, arg.ID, arg.PublicID)
	var i GetPublicEventFileRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.FileID,
		&i.Description,
		&i.Visibility,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsBanner,
		&i.OriginalFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
	)
	return i, err
}

const linkEventAssignmentPerson = `-- name: LinkEventAssignmentPerson :one
UPDATE event_shift_assignments
SET person_id = $1, version = version + 1, updated_at = now()
WHERE id = $2 AND version = $3 AND status = 'active' AND personal_data_erased_at IS NULL
RETURNING id, event_id, shift_id, requirement_id, person_id, first_name_snapshot, last_name_snapshot, email_snapshot, email_normalized, phone_snapshot, phone_normalized, source, status, created_by_account_id, management_token_digest, conflict_overridden_by_account_id, cancelled_at, cancelled_by_account_id, personal_data_erased_at, version, created_at, updated_at
`

type LinkEventAssignmentPersonParams struct {
	PersonID        *uuid.UUID
	ID              uuid.UUID
	ExpectedVersion int32
}

func (q *Queries) LinkEventAssignmentPerson(ctx context.Context, arg LinkEventAssignmentPersonParams) (EventShiftAssignment, error) {
	row := q.db.QueryRow(ctx, linkEventAssignmentPerson, arg.PersonID, arg.ID, arg.ExpectedVersion)
	var i EventShiftAssignment
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ShiftID,
		&i.RequirementID,
		&i.PersonID,
		&i.FirstNameSnapshot,
		&i.LastNameSnapshot,
		&i.EmailSnapshot,
		&i.EmailNormalized,
		&i.PhoneSnapshot,
		&i.PhoneNormalized,
		&i.Source,
		&i.Status,
		&i.CreatedByAccountID,
		&i.ManagementTokenDigest,
		&i.ConflictOverriddenByAccountID,
		&i.CancelledAt,
		&i.CancelledByAccountID,
		&i.PersonalDataErasedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEventAssignments = `-- name: ListEventAssignments :many
SELECT a.id, a.event_id, a.shift_id, a.requirement_id, a.person_id, a.first_name_snapshot, a.last_name_snapshot, a.email_snapshot, a.email_normalized, a.phone_snapshot, a.phone_normalized, a.source, a.status, a.created_by_account_id, a.management_token_digest, a.conflict_overridden_by_account_id, a.cancelled_at, a.cancelled_by_account_id, a.personal_data_erased_at, a.version, a.created_at, a.updated_at, p.first_name AS person_first_name, p.last_name AS person_last_name
FROM event_shift_assignments a
LEFT JOIN people p ON p.id = a.person_id
WHERE a.event_id = $1
ORDER BY a.created_at, a.id
`

type ListEventAssignmentsRow struct {
	ID                            uuid.UUID
	EventID                       uuid.UUID
	ShiftID                       uuid.UUID
	RequirementID                 uuid.UUID
	PersonID                      *uuid.UUID
	FirstNameSnapshot             *string
	LastNameSnapshot              *string
	EmailSnapshot                 *string
	EmailNormalized               *string
	PhoneSnapshot                 *string
	PhoneNormalized               *string
	Source                        string
	Status                        string
	CreatedByAccountID            *uuid.UUID
	ManagementTokenDigest         []byte
	ConflictOverriddenByAccountID *uuid.UUID
	CancelledAt                   pgtype.Timestamptz
	CancelledByAccountID          *uuid.UUID
	PersonalDataErasedAt          pgtype.Timestamptz
	Version                       int32
	CreatedAt                     time.Time
	UpdatedAt                     time.Time
	PersonFirstName               *string
	PersonLastName                *string
}

func (q *Queries) ListEventAssignments(ctx context.Context, eventID uuid.UUID) ([]ListEventAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listEventAssignments, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventAssignmentsRow{}
	for rows.Next() {
		var i ListEventAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.ShiftID,
			&i.RequirementID,
			&i.PersonID,
			&i.FirstNameSnapshot,
			&i.LastNameSnapshot,
			&i.EmailSnapshot,
			&i.EmailNormalized,
			&i.PhoneSnapshot,
			&i.PhoneNormalized,
			&i.Source,
			&i.Status,
			&i.CreatedByAccountID,
			&i.ManagementTokenDigest,
			&i.ConflictOverriddenByAccountID,
			&i.CancelledAt,
			&i.CancelledByAccountID,
			&i.PersonalDataErasedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PersonFirstName,
			&i.PersonLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventEligibilityRoles = `-- name: ListEventEligibilityRoles :many
SELECT id, name FROM roles ORDER BY system_key DESC NULLS LAST, lower(name), id
`

type ListEventEligibilityRolesRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) ListEventEligibilityRoles(ctx context.Context) ([]ListEventEligibilityRolesRow, error) {
	rows, err := q.db.Query(ctx, listEventEligibilityRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventEligibilityRolesRow{}
	for rows.Next() {
		var i ListEventEligibilityRolesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventFileIDsForDelete = `-- name: ListEventFileIDsForDelete :many
SELECT file_id FROM event_files WHERE event_id = $1 ORDER BY id
`

func (q *Queries) ListEventFileIDsForDelete(ctx context.Context, eventID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listEventFileIDsForDelete, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var file_id uuid.UUID
		if err := rows.Scan(&file_id); err != nil {
			return nil, err
		}
		items = append(items, file_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventFiles = `-- name: ListEventFiles :many
SELECT ef.id, ef.event_id, ef.file_id, ef.description, ef.visibility, ef.version, ef.created_at, ef.updated_at, ef.is_banner, f.original_filename, f.content_type, f.size_bytes, f.created_at AS file_created_at
FROM event_files ef JOIN files f ON f.id = ef.file_id
WHERE ef.event_id = $1
ORDER BY ef.created_at, ef.id
`

type ListEventFilesRow struct {
	ID               uuid.UUID
	EventID          uuid.UUID
	FileID           uuid.UUID
	Description      *string
	Visibility       string
	Version          int32
	CreatedAt        time.Time
	UpdatedAt        time.Time
	IsBanner         bool
	OriginalFilename string
	ContentType      string
	SizeBytes        int64
	FileCreatedAt    time.Time
}

func (q *Queries) ListEventFiles(ctx context.Context, eventID uuid.UUID) ([]ListEventFilesRow, error) {
	rows, err := q.db.Query(ctx, listEventFiles, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventFilesRow{}
	for rows.Next() {
		var i ListEventFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.FileID,
			&i.Description,
			&i.Visibility,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsBanner,
			&i.OriginalFilename,
			&i.ContentType,
			&i.SizeBytes,
			&i.FileCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventRequirementRoleIDs = `-- name: ListEventRequirementRoleIDs :many
SELECT role_id FROM event_shift_requirement_roles WHERE requirement_id = $1 ORDER BY role_id
`

func (q *Queries) ListEventRequirementRoleIDs(ctx context.Context, requirementID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listEventRequirementRoleIDs, requirementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var role_id uuid.UUID
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventRequirements = `-- name: ListEventRequirements :many
SELECT r.id, r.event_id, r.shift_id, r.name, r.description, r.required_count, r.eligibility_mode, r.version, r.created_at, r.updated_at,
       count(a.id) FILTER (WHERE a.status = 'active')::bigint AS filled_count
FROM event_shift_requirements r
LEFT JOIN event_shift_assignments a ON a.requirement_id = r.id
WHERE r.event_id = $1
GROUP BY r.id
ORDER BY r.shift_id, lower(r.name), r.id
`

type ListEventRequirementsRow struct {
	ID              uuid.UUID
	EventID         uuid.UUID
	ShiftID         uuid.UUID
	Name            string
	Description     *string
	RequiredCount   int32
	EligibilityMode string
	Version         int32
	CreatedAt       time.Time
	UpdatedAt       time.Time
	FilledCount     int64
}

func (q *Queries) ListEventRequirements(ctx context.Context, eventID uuid.UUID) ([]ListEventRequirementsRow, error) {
	rows, err := q.db.Query(ctx, listEventRequirements, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventRequirementsRow{}
	for rows.Next() {
		var i ListEventRequirementsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.ShiftID,
			&i.Name,
			&i.Description,
			&i.RequiredCount,
			&i.EligibilityMode,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FilledCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventSessions = `-- name: ListEventSessions :many
SELECT id, event_id, name, location, description, starts_at, ends_at, is_public, status, version, created_at, updated_at FROM event_sessions WHERE event_id = $1 ORDER BY starts_at, id
`

func (q *Queries) ListEventSessions(ctx context.Context, eventID uuid.UUID) ([]EventSession, error) {
	rows, err := q.db.Query(ctx, listEventSessions, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventSession{}
	for rows.Next() {
		var i EventSession
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.Location,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.IsPublic,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventShifts = `-- name: ListEventShifts :many
SELECT sh.id, sh.event_id, sh.session_id, sh.name, sh.description, sh.starts_at, sh.ends_at, sh.signup_opens_at, sh.signup_closes_at, sh.is_public, sh.status, sh.version, sh.created_at, sh.updated_at, s.status AS session_status
FROM event_shifts sh
LEFT JOIN event_sessions s ON s.id = sh.session_id
WHERE sh.event_id = $1
ORDER BY sh.starts_at, sh.id
`

type ListEventShiftsRow struct {
	ID             uuid.UUID
	EventID        uuid.UUID
	SessionID      *uuid.UUID
	Name           string
	Description    *string
	StartsAt       time.Time
	EndsAt         time.Time
	SignupOpensAt  pgtype.Timestamptz
	SignupClosesAt pgtype.Timestamptz
	IsPublic       bool
	Status         string
	Version        int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
	SessionStatus  *string
}

func (q *Queries) ListEventShifts(ctx context.Context, eventID uuid.UUID) ([]ListEventShiftsRow, error) {
	rows, err := q.db.Query(ctx, listEventShifts, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventShiftsRow{}
	for rows.Next() {
		var i ListEventShiftsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.SessionID,
			&i.Name,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.SignupOpensAt,
			&i.SignupClosesAt,
			&i.IsPublic,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SessionStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventTaskLists = `-- name: ListEventTaskLists :many
SELECT id, event_id, name, description, sort_order, version, created_at, updated_at FROM event_task_lists WHERE event_id = $1 ORDER BY sort_order, id
`

func (q *Queries) ListEventTaskLists(ctx context.Context, eventID uuid.UUID) ([]EventTaskList, error) {
	rows, err := q.db.Query(ctx, listEventTaskLists, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventTaskList{}
	for rows.Next() {
		var i EventTaskList
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.Description,
			&i.SortOrder,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventTasks = `-- name: ListEventTasks :many
SELECT id, event_id, task_list_id, title, description, status, priority, assignee_person_id, due_at, completed_at, completed_by_account_id, sort_order, created_by_account_id, version, created_at, updated_at FROM event_tasks WHERE event_id = $1 ORDER BY task_list_id NULLS FIRST, sort_order, id
`

func (q *Queries) ListEventTasks(ctx context.Context, eventID uuid.UUID) ([]EventTask, error) {
	rows, err := q.db.Query(ctx, listEventTasks, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventTask{}
	for rows.Next() {
		var i EventTask
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.TaskListID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.AssigneePersonID,
			&i.DueAt,
			&i.CompletedAt,
			&i.CompletedByAccountID,
			&i.SortOrder,
			&i.CreatedByAccountID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT e.id, e.name, e.internal_description, e.location, e.owner_person_id, e.status, e.public_title, e.public_description, e.public_location, e.public_id, e.is_public, e.public_signup_enabled, e.closed_at, e.created_by_account_id, e.version, e.created_at, e.updated_at,
       p.first_name AS owner_first_name, p.last_name AS owner_last_name
FROM events e
LEFT JOIN people p ON p.id = e.owner_person_id
ORDER BY e.updated_at DESC, e.id DESC
`

type ListEventsRow struct {
	Event          Event
	OwnerFirstName *string
	OwnerLastName  *string
}

func (q *Queries) ListEvents(ctx context.Context) ([]ListEventsRow, error) {
	rows, err := q.db.Query(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsRow{}
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.Event.ID,
			&i.Event.Name,
			&i.Event.InternalDescription,
			&i.Event.Location,
			&i.Event.OwnerPersonID,
			&i.Event.Status,
			&i.Event.PublicTitle,
			&i.Event.PublicDescription,
			&i.Event.PublicLocation,
			&i.Event.PublicID,
			&i.Event.IsPublic,
			&i.Event.PublicSignupEnabled,
			&i.Event.ClosedAt,
			&i.Event.CreatedByAccountID,
			&i.Event.Version,
			&i.Event.CreatedAt,
			&i.Event.UpdatedAt,
			&i.OwnerFirstName,
			&i.OwnerLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredEventAssignmentsForUpdate = `-- name: ListExpiredEventAssignmentsForUpdate :many
SELECT a.id, a.event_id
FROM event_shift_assignments a
JOIN events e ON e.id = a.event_id
WHERE e.closed_at IS NOT NULL AND e.closed_at < $1
  AND a.personal_data_erased_at IS NULL
ORDER BY a.id
FOR UPDATE OF a
`

type ListExpiredEventAssignmentsForUpdateRow struct {
	ID      uuid.UUID
	EventID uuid.UUID
}

func (q *Queries) ListExpiredEventAssignmentsForUpdate(ctx context.Context, cutoff pgtype.Timestamptz) ([]ListExpiredEventAssignmentsForUpdateRow, error) {
	rows, err := q.db.Query(ctx, listExpiredEventAssignmentsForUpdate, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredEventAssignmentsForUpdateRow{}
	for rows.Next() {
		var i ListExpiredEventAssignmentsForUpdateRow
		if err := rows.Scan(&i.ID, &i.EventID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnEventAssignments = `-- name: ListOwnEventAssignments :many
SELECT a.id, a.event_id, a.shift_id, a.requirement_id, a.person_id, a.first_name_snapshot, a.last_name_snapshot, a.email_snapshot, a.email_normalized, a.phone_snapshot, a.phone_normalized, a.source, a.status, a.created_by_account_id, a.management_token_digest, a.conflict_overridden_by_account_id, a.cancelled_at, a.cancelled_by_account_id, a.personal_data_erased_at, a.version, a.created_at, a.updated_at FROM event_shift_assignments a
JOIN events e ON e.id = a.event_id
WHERE e.public_id = $1 AND e.is_public AND a.person_id = $2
ORDER BY a.created_at, a.id
`

type ListOwnEventAssignmentsParams struct {
	PublicID string
	PersonID *uuid.UUID
}

func (q *Queries) ListOwnEventAssignments(ctx context.Context, arg ListOwnEventAssignmentsParams) ([]EventShiftAssignment, error) {
	rows, err := q.db.Query(ctx, listOwnEventAssignments, arg.PublicID, arg.PersonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventShiftAssignment{}
	for rows.Next() {
		var i EventShiftAssignment
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.ShiftID,
			&i.RequirementID,
			&i.PersonID,
			&i.FirstNameSnapshot,
			&i.LastNameSnapshot,
			&i.EmailSnapshot,
			&i.EmailNormalized,
			&i.PhoneSnapshot,
			&i.PhoneNormalized,
			&i.Source,
			&i.Status,
			&i.CreatedByAccountID,
			&i.ManagementTokenDigest,
			&i.ConflictOverriddenByAccountID,
			&i.CancelledAt,
			&i.CancelledByAccountID,
			&i.PersonalDataErasedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEventRequirement = `-- name: LockEventRequirement :one
SELECT id, event_id, shift_id, name, description, required_count, eligibility_mode, version, created_at, updated_at FROM event_shift_requirements
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockEventRequirement(ctx context.Context, id uuid.UUID) (EventShiftRequirement, error) {
	row := q.db.QueryRow(ctx, lockEventRequirement, id)
	var i EventShiftRequirement
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ShiftID,
		&i.Name,
		&i.Description,
		&i.RequiredCount,
		&i.EligibilityMode,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockPersonForEventAssignment = `-- name: LockPersonForEventAssignment :one
SELECT id FROM people WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockPersonForEventAssignment(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockPersonForEventAssignment, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const moveEventAssignment = `-- name: MoveEventAssignment :one
UPDATE event_shift_assignments
SET shift_id = $1, requirement_id = $2,
    conflict_overridden_by_account_id = $3,
    version = version + 1, updated_at = now()
WHERE id = $4 AND version = $5 AND status = 'active' AND personal_data_erased_at IS NULL
RETURNING id, event_id, shift_id, requirement_id, person_id, first_name_snapshot, last_name_snapshot, email_snapshot, email_normalized, phone_snapshot, phone_normalized, source, status, created_by_account_id, management_token_digest, conflict_overridden_by_account_id, cancelled_at, cancelled_by_account_id, personal_data_erased_at, version, created_at, updated_at
`

type MoveEventAssignmentParams struct {
	ShiftID                       uuid.UUID
	RequirementID                 uuid.UUID
	ConflictOverriddenByAccountID *uuid.UUID
	ID                            uuid.UUID
	ExpectedVersion               int32
}

func (q *Queries) MoveEventAssignment(ctx context.Context, arg MoveEventAssignmentParams) (EventShiftAssignment, error) {
	row := q.db.QueryRow(ctx, moveEventAssignment,
		arg.ShiftID,
		arg.RequirementID,
		arg.ConflictOverriddenByAccountID,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i EventShiftAssignment
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ShiftID,
		&i.RequirementID,
		&i.PersonID,
		&i.FirstNameSnapshot,
		&i.LastNameSnapshot,
		&i.EmailSnapshot,
		&i.EmailNormalized,
		&i.PhoneSnapshot,
		&i.PhoneNormalized,
		&i.Source,
		&i.Status,
		&i.CreatedByAccountID,
		&i.ManagementTokenDigest,
		&i.ConflictOverriddenByAccountID,
		&i.CancelledAt,
		&i.CancelledByAccountID,
		&i.PersonalDataErasedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const personEligibleForEventRequirement = `-- name: PersonEligibleForEventRequirement :one
SELECT r.eligibility_mode = 'anyone' OR EXISTS (
    SELECT 1 FROM event_shift_requirement_roles rr
    JOIN person_roles pr ON pr.role_id = rr.role_id
    WHERE rr.requirement_id = r.id AND pr.person_id = $1
) AS eligible
FROM event_shift_requirements r WHERE r.id = $2
`

type PersonEligibleForEventRequirementParams struct {
	PersonID      uuid.UUID
	RequirementID uuid.UUID
}

func (q *Queries) PersonEligibleForEventRequirement(ctx context.Context, arg PersonEligibleForEventRequirementParams) (*bool, error) {
	row := q.db.QueryRow(ctx, personEligibleForEventRequirement, arg.PersonID, arg.RequirementID)
	var eligible *bool
	err := row.Scan(&eligible)
	return eligible, err
}

const replaceEventRequirementRoles = `-- name: ReplaceEventRequirementRoles :exec
DELETE FROM event_shift_requirement_roles WHERE requirement_id = $1
`

func (q *Queries) ReplaceEventRequirementRoles(ctx context.Context, requirementID uuid.UUID) error {
	_, err := q.db.Exec(ctx, replaceEventRequirementRoles, requirementID)
	return err
}

const rotateEventPublicID = `-- name: RotateEventPublicID :one
UPDATE events SET public_id = $1, version = version + 1, updated_at = now()
WHERE id = $2 AND version = $3 AND status NOT IN ('completed', 'cancelled', 'archived')
RETURNING id, name, internal_description, location, owner_person_id, status, public_title, public_description, public_location, public_id, is_public, public_signup_enabled, closed_at, created_by_account_id, version, created_at, updated_at
`

type RotateEventPublicIDParams struct {
	PublicID        string
	ID              uuid.UUID
	ExpectedVersion int32
}

func (q *Queries) RotateEventPublicID(ctx context.Context, arg RotateEventPublicIDParams) (Event, error) {
	row := q.db.QueryRow(ctx, rotateEventPublicID, arg.PublicID, arg.ID, arg.ExpectedVersion)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InternalDescription,
		&i.Location,
		&i.OwnerPersonID,
		&i.Status,
		&i.PublicTitle,
		&i.PublicDescription,
		&i.PublicLocation,
		&i.PublicID,
		&i.IsPublic,
		&i.PublicSignupEnabled,
		&i.ClosedAt,
		&i.CreatedByAccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const scrubEventAssignmentsForPerson = `-- name: ScrubEventAssignmentsForPerson :many
UPDATE event_shift_assignments
SET person_id = NULL, first_name_snapshot = NULL, last_name_snapshot = NULL,
    email_snapshot = NULL, email_normalized = NULL, phone_snapshot = NULL, phone_normalized = NULL,
    management_token_digest = NULL, personal_data_erased_at = COALESCE(personal_data_erased_at, now()),
    version = version + 1, updated_at = now()
WHERE person_id = $1
RETURNING id, event_id
`

type ScrubEventAssignmentsForPersonRow struct {
	ID      uuid.UUID
	EventID uuid.UUID
}

func (q *Queries) ScrubEventAssignmentsForPerson(ctx context.Context, personID *uuid.UUID) ([]ScrubEventAssignmentsForPersonRow, error) {
	rows, err := q.db.Query(ctx, scrubEventAssignmentsForPerson, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScrubEventAssignmentsForPersonRow{}
	for rows.Next() {
		var i ScrubEventAssignmentsForPersonRow
		if err := rows.Scan(&i.ID, &i.EventID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEventPublication = `-- name: SetEventPublication :one
UPDATE events
SET is_public = $1,
    version = version + 1, updated_at = now()
WHERE id = $2 AND version = $3
RETURNING id, name, internal_description, location, owner_person_id, status, public_title, public_description, public_location, public_id, is_public, public_signup_enabled, closed_at, created_by_account_id, version, created_at, updated_at
`

type SetEventPublicationParams struct {
	IsPublic        bool
	ID              uuid.UUID
	ExpectedVersion int32
}

func (q *Queries) SetEventPublication(ctx context.Context, arg SetEventPublicationParams) (Event, error) {
	row := q.db.QueryRow(ctx, setEventPublication, arg.IsPublic, arg.ID, arg.ExpectedVersion)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InternalDescription,
		&i.Location,
		&i.OwnerPersonID,
		&i.Status,
		&i.PublicTitle,
		&i.PublicDescription,
		&i.PublicLocation,
		&i.PublicID,
		&i.IsPublic,
		&i.PublicSignupEnabled,
		&i.ClosedAt,
		&i.CreatedByAccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const transitionEvent = `-- name: TransitionEvent :one
UPDATE events
SET status = $1, closed_at = $2,
    is_public = CASE WHEN $1::text = 'archived' THEN false ELSE is_public END,
    version = version + 1, updated_at = now()
WHERE id = $3 AND version = $4
RETURNING id, name, internal_description, location, owner_person_id, status, public_title, public_description, public_location, public_id, is_public, public_signup_enabled, closed_at, created_by_account_id, version, created_at, updated_at
`

type TransitionEventParams struct {
	Status          string
	ClosedAt        pgtype.Timestamptz
	ID              uuid.UUID
	ExpectedVersion int32
}

func (q *Queries) TransitionEvent(ctx context.Context, arg TransitionEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, transitionEvent,
		arg.Status,
		arg.ClosedAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InternalDescription,
		&i.Location,
		&i.OwnerPersonID,
		&i.Status,
		&i.PublicTitle,
		&i.PublicDescription,
		&i.PublicLocation,
		&i.PublicID,
		&i.IsPublic,
		&i.PublicSignupEnabled,
		&i.ClosedAt,
		&i.CreatedByAccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET name = $1, internal_description = $2,
    location = $3, owner_person_id = $4,
    public_title = $5, public_description = $6,
    public_location = $7, public_signup_enabled = $8,
    version = version + 1, updated_at = now()
WHERE id = $9 AND version = $10 AND status NOT IN ('completed', 'cancelled', 'archived')
RETURNING id, name, internal_description, location, owner_person_id, status, public_title, public_description, public_location, public_id, is_public, public_signup_enabled, closed_at, created_by_account_id, version, created_at, updated_at
`

type UpdateEventParams struct {
	Name                string
	InternalDescription *string
	Location            *string
	OwnerPersonID       *uuid.UUID
	PublicTitle         *string
	PublicDescription   *string
	PublicLocation      *string
	PublicSignupEnabled bool
	ID                  uuid.UUID
	ExpectedVersion     int32
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.Name,
		arg.InternalDescription,
		arg.Location,
		arg.OwnerPersonID,
		arg.PublicTitle,
		arg.PublicDescription,
		arg.PublicLocation,
		arg.PublicSignupEnabled,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InternalDescription,
		&i.Location,
		&i.OwnerPersonID,
		&i.Status,
		&i.PublicTitle,
		&i.PublicDescription,
		&i.PublicLocation,
		&i.PublicID,
		&i.IsPublic,
		&i.PublicSignupEnabled,
		&i.ClosedAt,
		&i.CreatedByAccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEventAssignmentContact = `-- name: UpdateEventAssignmentContact :one
UPDATE event_shift_assignments
SET first_name_snapshot = $1, last_name_snapshot = $2,
    email_snapshot = $3, email_normalized = $4,
    phone_snapshot = $5, phone_normalized = $6,
    version = version + 1, updated_at = now()
WHERE id = $7 AND version = $8 AND status = 'active' AND personal_data_erased_at IS NULL
RETURNING id, event_id, shift_id, requirement_id, person_id, first_name_snapshot, last_name_snapshot, email_snapshot, email_normalized, phone_snapshot, phone_normalized, source, status, created_by_account_id, management_token_digest, conflict_overridden_by_account_id, cancelled_at, cancelled_by_account_id, personal_data_erased_at, version, created_at, updated_at
`

type UpdateEventAssignmentContactParams struct {
	FirstNameSnapshot *string
	LastNameSnapshot  *string
	EmailSnapshot     *string
	EmailNormalized   *string
	PhoneSnapshot     *string
	PhoneNormalized   *string
	ID                uuid.UUID
	ExpectedVersion   int32
}

func (q *Queries) UpdateEventAssignmentContact(ctx context.Context, arg UpdateEventAssignmentContactParams) (EventShiftAssignment, error) {
	row := q.db.QueryRow(ctx, updateEventAssignmentContact,
		arg.FirstNameSnapshot,
		arg.LastNameSnapshot,
		arg.EmailSnapshot,
		arg.EmailNormalized,
		arg.PhoneSnapshot,
		arg.PhoneNormalized,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i EventShiftAssignment
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ShiftID,
		&i.RequirementID,
		&i.PersonID,
		&i.FirstNameSnapshot,
		&i.LastNameSnapshot,
		&i.EmailSnapshot,
		&i.EmailNormalized,
		&i.PhoneSnapshot,
		&i.PhoneNormalized,
		&i.Source,
		&i.Status,
		&i.CreatedByAccountID,
		&i.ManagementTokenDigest,
		&i.ConflictOverriddenByAccountID,
		&i.CancelledAt,
		&i.CancelledByAccountID,
		&i.PersonalDataErasedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEventFile = `-- name: UpdateEventFile :one
UPDATE event_files
SET description = $1, visibility = $2, is_banner = $3,
    version = version + 1, updated_at = now()
WHERE id = $4 AND event_id = $5 AND version = $6
RETURNING id, event_id, file_id, description, visibility, version, created_at, updated_at, is_banner
`

type UpdateEventFileParams struct {
	Description     *string
	Visibility      string
	IsBanner        bool
	ID              uuid.UUID
	EventID         uuid.UUID
	ExpectedVersion int32
}

func (q *Queries) UpdateEventFile(ctx context.Context, arg UpdateEventFileParams) (EventFile, error) {
	row := q.db.QueryRow(ctx, updateEventFile,
		arg.Description,
		arg.Visibility,
		arg.IsBanner,
		arg.ID,
		arg.EventID,
		arg.ExpectedVersion,
	)
	var i EventFile
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.FileID,
		&i.Description,
		&i.Visibility,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsBanner,
	)
	return i, err
}

const updateEventRequirement = `-- name: UpdateEventRequirement :one
UPDATE event_shift_requirements
SET name = $1, description = $2, required_count = $3,
    eligibility_mode = $4, version = version + 1, updated_at = now()
WHERE id = $5 AND shift_id = $6 AND event_id = $7
  AND version = $8
RETURNING id, event_id, shift_id, name, description, required_count, eligibility_mode, version, created_at, updated_at
`

type UpdateEventRequirementParams struct {
	Name            string
	Description     *string
	RequiredCount   int32
	EligibilityMode string
	ID              uuid.UUID
	ShiftID         uuid.UUID
	EventID         uuid.UUID
	ExpectedVersion int32
}

func (q *Queries) UpdateEventRequirement(ctx context.Context, arg UpdateEventRequirementParams) (EventShiftRequirement, error) {
	row := q.db.QueryRow(ctx, updateEventRequirement,
		arg.Name,
		arg.Description,
		arg.RequiredCount,
		arg.EligibilityMode,
		arg.ID,
		arg.ShiftID,
		arg.EventID,
		arg.ExpectedVersion,
	)
	var i EventShiftRequirement
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ShiftID,
		&i.Name,
		&i.Description,
		&i.RequiredCount,
		&i.EligibilityMode,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEventSession = `-- name: UpdateEventSession :one
UPDATE event_sessions
SET name = $1, location = $2, description = $3,
    starts_at = $4, ends_at = $5, is_public = $6,
    status = $7, version = version + 1, updated_at = now()
WHERE id = $8 AND event_id = $9 AND version = $10
RETURNING id, event_id, name, location, description, starts_at, ends_at, is_public, status, version, created_at, updated_at
`

type UpdateEventSessionParams struct {
	Name            *string
	Location        *string
	Description     *string
	StartsAt        time.Time
	EndsAt          time.Time
	IsPublic        bool
	Status          string
	ID              uuid.UUID
	EventID         uuid.UUID
	ExpectedVersion int32
}

func (q *Queries) UpdateEventSession(ctx context.Context, arg UpdateEventSessionParams) (EventSession, error) {
	row := q.db.QueryRow(ctx, updateEventSession,
		arg.Name,
		arg.Location,
		arg.Description,
		arg.StartsAt,
		arg.EndsAt,
		arg.IsPublic,
		arg.Status,
		arg.ID,
		arg.EventID,
		arg.ExpectedVersion,
	)
	var i EventSession
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Location,
		&i.Description,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsPublic,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEventShift = `-- name: UpdateEventShift :one
UPDATE event_shifts
SET session_id = $1, name = $2, description = $3,
    starts_at = $4, ends_at = $5,
    signup_opens_at = $6, signup_closes_at = $7,
    is_public = $8, status = $9, version = version + 1, updated_at = now()
WHERE id = $10 AND event_id = $11 AND version = $12
RETURNING id, event_id, session_id, name, description, starts_at, ends_at, signup_opens_at, signup_closes_at, is_public, status, version, created_at, updated_at
`

type UpdateEventShiftParams struct {
	SessionID       *uuid.UUID
	Name            string
	Description     *string
	StartsAt        time.Time
	EndsAt          time.Time
	SignupOpensAt   pgtype.Timestamptz
	SignupClosesAt  pgtype.Timestamptz
	IsPublic        bool
	Status          string
	ID              uuid.UUID
	EventID         uuid.UUID
	ExpectedVersion int32
}

func (q *Queries) UpdateEventShift(ctx context.Context, arg UpdateEventShiftParams) (EventShift, error) {
	row := q.db.QueryRow(ctx, updateEventShift,
		arg.SessionID,
		arg.Name,
		arg.Description,
		arg.StartsAt,
		arg.EndsAt,
		arg.SignupOpensAt,
		arg.SignupClosesAt,
		arg.IsPublic,
		arg.Status,
		arg.ID,
		arg.EventID,
		arg.ExpectedVersion,
	)
	var i EventShift
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.SessionID,
		&i.Name,
		&i.Description,
		&i.StartsAt,
		&i.EndsAt,
		&i.SignupOpensAt,
		&i.SignupClosesAt,
		&i.IsPublic,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEventTask = `-- name: UpdateEventTask :one
UPDATE event_tasks
SET task_list_id = $1, title = $2, description = $3,
    status = $4, priority = $5, assignee_person_id = $6,
    due_at = $7, completed_at = $8,
    completed_by_account_id = $9, sort_order = $10,
    version = version + 1, updated_at = now()
WHERE id = $11 AND event_id = $12 AND version = $13
RETURNING id, event_id, task_list_id, title, description, status, priority, assignee_person_id, due_at, completed_at, completed_by_account_id, sort_order, created_by_account_id, version, created_at, updated_at
`

type UpdateEventTaskParams struct {
	TaskListID           *uuid.UUID
	Title                string
	Description          *string
	Status               string
	Priority             string
	AssigneePersonID     *uuid.UUID
	DueAt                pgtype.Timestamptz
	CompletedAt          pgtype.Timestamptz
	CompletedByAccountID *uuid.UUID
	SortOrder            int32
	ID                   uuid.UUID
	EventID              uuid.UUID
	ExpectedVersion      int32
}

func (q *Queries) UpdateEventTask(ctx context.Context, arg UpdateEventTaskParams) (EventTask, error) {
	row := q.db.QueryRow(ctx, updateEventTask,
		arg.TaskListID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.AssigneePersonID,
		arg.DueAt,
		arg.CompletedAt,
		arg.CompletedByAccountID,
		arg.SortOrder,
		arg.ID,
		arg.EventID,
		arg.ExpectedVersion,
	)
	var i EventTask
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.TaskListID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneePersonID,
		&i.DueAt,
		&i.CompletedAt,
		&i.CompletedByAccountID,
		&i.SortOrder,
		&i.CreatedByAccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEventTaskList = `-- name: UpdateEventTaskList :one
UPDATE event_task_lists
SET name = $1, description = $2, sort_order = $3,
    version = version + 1, updated_at = now()
WHERE id = $4 AND event_id = $5 AND version = $6
RETURNING id, event_id, name, description, sort_order, version, created_at, updated_at
`

type UpdateEventTaskListParams struct {
	Name            string
	Description     *string
	SortOrder       int32
	ID              uuid.UUID
	EventID         uuid.UUID
	ExpectedVersion int32
}

func (q *Queries) UpdateEventTaskList(ctx context.Context, arg UpdateEventTaskListParams) (EventTaskList, error) {
	row := q.db.QueryRow(ctx, updateEventTaskList,
		arg.Name,
		arg.Description,
		arg.SortOrder,
		arg.ID,
		arg.EventID,
		arg.ExpectedVersion,
	)
	var i EventTaskList
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
